// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-block-format"
	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockDownloader creates a new instance of MockBlockDownloader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockDownloader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockDownloader {
	mock := &MockBlockDownloader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockDownloader is an autogenerated mock type for the BlockDownloader type
type MockBlockDownloader struct {
	mock.Mock
}

type MockBlockDownloader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockDownloader) EXPECT() *MockBlockDownloader_Expecter {
	return &MockBlockDownloader_Expecter{mock: &_m.Mock}
}

// Get provides a mock function for the type MockBlockDownloader
func (_mock *MockBlockDownloader) Get(ctx context.Context, c cid.Cid) (blocks.Block, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 blocks.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (blocks.Block, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) blocks.Block); ok {
		r0 = returnFunc(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blocks.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockDownloader_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockBlockDownloader_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockBlockDownloader_Expecter) Get(ctx interface{}, c interface{}) *MockBlockDownloader_Get_Call {
	return &MockBlockDownloader_Get_Call{Call: _e.mock.On("Get", ctx, c)}
}

func (_c *MockBlockDownloader_Get_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockBlockDownloader_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockDownloader_Get_Call) Return(block blocks.Block, err error) *MockBlockDownloader_Get_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockBlockDownloader_Get_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (blocks.Block, error)) *MockBlockDownloader_Get_Call {
	_c.Call.Return(run)
	return _c
}
