// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockBlockService creates a new instance of MockBlockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockService {
	mock := &MockBlockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockService is an autogenerated mock type for the BlockService type
type MockBlockService struct {
	mock.Mock
}

type MockBlockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockService) EXPECT() *MockBlockService_Expecter {
	return &MockBlockService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockBlockService
func (_mock *MockBlockService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockBlockService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockBlockService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockBlockService_Expecter) Config() *MockBlockService_Config_Call {
	return &MockBlockService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockBlockService_Config_Call) Run(run func()) *MockBlockService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockService_Config_Call) Return(manager config.Manager) *MockBlockService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockBlockService_Config_Call) RunAndReturn(run func() config.Manager) *MockBlockService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockBlockService
func (_mock *MockBlockService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockBlockService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockBlockService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockBlockService_Expecter) Context() *MockBlockService_Context_Call {
	return &MockBlockService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockBlockService_Context_Call) Run(run func()) *MockBlockService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockService_Context_Call) Return(context core.Context) *MockBlockService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockBlockService_Context_Call) RunAndReturn(run func() core.Context) *MockBlockService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockBlockService
func (_mock *MockBlockService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockBlockService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockBlockService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockBlockService_Expecter) DB() *MockBlockService_DB_Call {
	return &MockBlockService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockBlockService_DB_Call) Run(run func()) *MockBlockService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockService_DB_Call) Return(dB *gorm.DB) *MockBlockService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockBlockService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockBlockService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockMeta provides a mock function for the type MockBlockService
func (_mock *MockBlockService) GetBlockMeta(ctx context.Context, c cid.Cid) (*db.UnixFSNode, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockMeta")
	}

	var r0 *db.UnixFSNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (*db.UnixFSNode, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) *db.UnixFSNode); ok {
		r0 = returnFunc(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.UnixFSNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockService_GetBlockMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockMeta'
type MockBlockService_GetBlockMeta_Call struct {
	*mock.Call
}

// GetBlockMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockBlockService_Expecter) GetBlockMeta(ctx any, c any) *MockBlockService_GetBlockMeta_Call {
	return &MockBlockService_GetBlockMeta_Call{Call: _e.mock.On("GetBlockMeta", ctx, c)}
}

func (_c *MockBlockService_GetBlockMeta_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockBlockService_GetBlockMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockService_GetBlockMeta_Call) Return(unixFSNode *db.UnixFSNode, err error) *MockBlockService_GetBlockMeta_Call {
	_c.Call.Return(unixFSNode, err)
	return _c
}

func (_c *MockBlockService_GetBlockMeta_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (*db.UnixFSNode, error)) *MockBlockService_GetBlockMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockMetaBatch provides a mock function for the type MockBlockService
func (_mock *MockBlockService) GetBlockMetaBatch(ctx context.Context, cids []cid.Cid) (map[string]*db.UnixFSNode, error) {
	ret := _mock.Called(ctx, cids)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockMetaBatch")
	}

	var r0 map[string]*db.UnixFSNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid) (map[string]*db.UnixFSNode, error)); ok {
		return returnFunc(ctx, cids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid) map[string]*db.UnixFSNode); ok {
		r0 = returnFunc(ctx, cids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*db.UnixFSNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []cid.Cid) error); ok {
		r1 = returnFunc(ctx, cids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockService_GetBlockMetaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockMetaBatch'
type MockBlockService_GetBlockMetaBatch_Call struct {
	*mock.Call
}

// GetBlockMetaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []cid.Cid
func (_e *MockBlockService_Expecter) GetBlockMetaBatch(ctx any, cids any) *MockBlockService_GetBlockMetaBatch_Call {
	return &MockBlockService_GetBlockMetaBatch_Call{Call: _e.mock.On("GetBlockMetaBatch", ctx, cids)}
}

func (_c *MockBlockService_GetBlockMetaBatch_Call) Run(run func(ctx context.Context, cids []cid.Cid)) *MockBlockService_GetBlockMetaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cid.Cid
		if args[1] != nil {
			arg1 = args[1].([]cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockService_GetBlockMetaBatch_Call) Return(stringToUnixFSNode map[string]*db.UnixFSNode, err error) *MockBlockService_GetBlockMetaBatch_Call {
	_c.Call.Return(stringToUnixFSNode, err)
	return _c
}

func (_c *MockBlockService_GetBlockMetaBatch_Call) RunAndReturn(run func(ctx context.Context, cids []cid.Cid) (map[string]*db.UnixFSNode, error)) *MockBlockService_GetBlockMetaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBlockService
func (_mock *MockBlockService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBlockService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBlockService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBlockService_Expecter) ID() *MockBlockService_ID_Call {
	return &MockBlockService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBlockService_ID_Call) Run(run func()) *MockBlockService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockService_ID_Call) Return(s string) *MockBlockService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBlockService_ID_Call) RunAndReturn(run func() string) *MockBlockService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockBlockService
func (_mock *MockBlockService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockBlockService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockBlockService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockBlockService_Expecter) Logger() *MockBlockService_Logger_Call {
	return &MockBlockService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockBlockService_Logger_Call) Run(run func()) *MockBlockService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockService_Logger_Call) Return(logger *core.Logger) *MockBlockService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockBlockService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockBlockService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockBlockService
func (_mock *MockBlockService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockBlockService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockBlockService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockBlockService_Expecter) SetConfig(cfg any) *MockBlockService_SetConfig_Call {
	return &MockBlockService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockBlockService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockBlockService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockService_SetConfig_Call) Return() *MockBlockService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockBlockService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockBlockService
func (_mock *MockBlockService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockBlockService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockBlockService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockBlockService_Expecter) SetContext(ctx any) *MockBlockService_SetContext_Call {
	return &MockBlockService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockBlockService_SetContext_Call) Run(run func(ctx core.Context)) *MockBlockService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockService_SetContext_Call) Return() *MockBlockService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockBlockService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockBlockService
func (_mock *MockBlockService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockBlockService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockBlockService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockBlockService_Expecter) SetDB(db1 any) *MockBlockService_SetDB_Call {
	return &MockBlockService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockBlockService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockBlockService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockService_SetDB_Call) Return() *MockBlockService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockBlockService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockBlockService
func (_mock *MockBlockService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockBlockService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockBlockService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockBlockService_Expecter) SetLogger(logger any) *MockBlockService_SetLogger_Call {
	return &MockBlockService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockBlockService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockBlockService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockService_SetLogger_Call) Return() *MockBlockService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockBlockService_SetLogger_Call {
	_c.Run(run)
	return _c
}
