// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/dnslink-std/go"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDNSResolver creates a new instance of MockDNSResolver. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSResolver(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSResolver {
	mock := &MockDNSResolver{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDNSResolver is an autogenerated mock type for the DNSResolver type
type MockDNSResolver struct {
	mock.Mock
}

type MockDNSResolver_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSResolver) EXPECT() *MockDNSResolver_Expecter {
	return &MockDNSResolver_Expecter{mock: &_m.Mock}
}

// LookupTXT provides a mock function for the type MockDNSResolver
func (_mock *MockDNSResolver) LookupTXT(domain string) ([]string, error) {
	ret := _mock.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for LookupTXT")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(domain)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSResolver_LookupTXT_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupTXT'
type MockDNSResolver_LookupTXT_Call struct {
	*mock.Call
}

// LookupTXT is a helper method to define mock.On call
//   - domain string
func (_e *MockDNSResolver_Expecter) LookupTXT(domain interface{}) *MockDNSResolver_LookupTXT_Call {
	return &MockDNSResolver_LookupTXT_Call{Call: _e.mock.On("LookupTXT", domain)}
}

func (_c *MockDNSResolver_LookupTXT_Call) Run(run func(domain string)) *MockDNSResolver_LookupTXT_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDNSResolver_LookupTXT_Call) Return(strings []string, err error) *MockDNSResolver_LookupTXT_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDNSResolver_LookupTXT_Call) RunAndReturn(run func(domain string) ([]string, error)) *MockDNSResolver_LookupTXT_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveDNSLink provides a mock function for the type MockDNSResolver
func (_mock *MockDNSResolver) ResolveDNSLink(domain string) (dnslink.Result, error) {
	ret := _mock.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for ResolveDNSLink")
	}

	var r0 dnslink.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (dnslink.Result, error)); ok {
		return returnFunc(domain)
	}
	if returnFunc, ok := ret.Get(0).(func(string) dnslink.Result); ok {
		r0 = returnFunc(domain)
	} else {
		r0 = ret.Get(0).(dnslink.Result)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSResolver_ResolveDNSLink_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDNSLink'
type MockDNSResolver_ResolveDNSLink_Call struct {
	*mock.Call
}

// ResolveDNSLink is a helper method to define mock.On call
//   - domain string
func (_e *MockDNSResolver_Expecter) ResolveDNSLink(domain interface{}) *MockDNSResolver_ResolveDNSLink_Call {
	return &MockDNSResolver_ResolveDNSLink_Call{Call: _e.mock.On("ResolveDNSLink", domain)}
}

func (_c *MockDNSResolver_ResolveDNSLink_Call) Run(run func(domain string)) *MockDNSResolver_ResolveDNSLink_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDNSResolver_ResolveDNSLink_Call) Return(result dnslink.Result, err error) *MockDNSResolver_ResolveDNSLink_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockDNSResolver_ResolveDNSLink_Call) RunAndReturn(run func(domain string) (dnslink.Result, error)) *MockDNSResolver_ResolveDNSLink_Call {
	_c.Call.Return(run)
	return _c
}
