// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the UploadService type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// CreateRootPin provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CreateRootPin(ctx context.Context, cid1 cid.Cid, userId uint) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, cid1, userId)

	if len(ret) == 0 {
		panic("no return value specified for CreateRootPin")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, uint) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, cid1, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, uint) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, cid1, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, uint) error); ok {
		r1 = returnFunc(ctx, cid1, userId)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_CreateRootPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRootPin'
type MockUploadService_CreateRootPin_Call struct {
	*mock.Call
}

// CreateRootPin is a helper method to define mock.On call
//   - ctx context.Context
//   - cid1 cid.Cid
//   - userId uint
func (_e *MockUploadService_Expecter) CreateRootPin(ctx interface{}, cid1 interface{}, userId interface{}) *MockUploadService_CreateRootPin_Call {
	return &MockUploadService_CreateRootPin_Call{Call: _e.mock.On("CreateRootPin", ctx, cid1, userId)}
}

func (_c *MockUploadService_CreateRootPin_Call) Run(run func(ctx context.Context, cid1 cid.Cid, userId uint)) *MockUploadService_CreateRootPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_CreateRootPin_Call) Return(iPFSPin *db.IPFSPin, err error) *MockUploadService_CreateRootPin_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockUploadService_CreateRootPin_Call) RunAndReturn(run func(ctx context.Context, cid1 cid.Cid, userId uint) (*db.IPFSPin, error)) *MockUploadService_CreateRootPin_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) HandleUpload(ctx context.Context, reader io.ReadSeekCloser, userId uint) (cid.Cid, string, error) {
	ret := _mock.Called(ctx, reader, userId)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpload")
	}

	var r0 cid.Cid
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, uint) (cid.Cid, string, error)); ok {
		return returnFunc(ctx, reader, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, uint) cid.Cid); ok {
		r0 = returnFunc(ctx, reader, userId)
	} else {
		r0 = ret.Get(0).(cid.Cid)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.ReadSeekCloser, uint) string); ok {
		r1 = returnFunc(ctx, reader, userId)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.ReadSeekCloser, uint) error); ok {
		r2 = returnFunc(ctx, reader, userId)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_HandleUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpload'
type MockUploadService_HandleUpload_Call struct {
	*mock.Call
}

// HandleUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.ReadSeekCloser
//   - userId uint
func (_e *MockUploadService_Expecter) HandleUpload(ctx interface{}, reader interface{}, userId interface{}) *MockUploadService_HandleUpload_Call {
	return &MockUploadService_HandleUpload_Call{Call: _e.mock.On("HandleUpload", ctx, reader, userId)}
}

func (_c *MockUploadService_HandleUpload_Call) Run(run func(ctx context.Context, reader io.ReadSeekCloser, userId uint)) *MockUploadService_HandleUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadSeekCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadSeekCloser)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) Return(cid1 cid.Cid, s string, err error) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(cid1, s, err)
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) RunAndReturn(run func(ctx context.Context, reader io.ReadSeekCloser, userId uint) (cid.Cid, string, error)) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUploadService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUploadService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) ID() *MockUploadService_ID_Call {
	return &MockUploadService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUploadService_ID_Call) Run(run func()) *MockUploadService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_ID_Call) Return(s string) *MockUploadService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUploadService_ID_Call) RunAndReturn(run func() string) *MockUploadService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ProcessUpload(ctx context.Context, cids []cid.Cid, userId uint) error {
	ret := _mock.Called(ctx, cids, userId)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid, uint) error); ok {
		r0 = returnFunc(ctx, cids, userId)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_ProcessUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessUpload'
type MockUploadService_ProcessUpload_Call struct {
	*mock.Call
}

// ProcessUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []cid.Cid
//   - userId uint
func (_e *MockUploadService_Expecter) ProcessUpload(ctx interface{}, cids interface{}, userId interface{}) *MockUploadService_ProcessUpload_Call {
	return &MockUploadService_ProcessUpload_Call{Call: _e.mock.On("ProcessUpload", ctx, cids, userId)}
}

func (_c *MockUploadService_ProcessUpload_Call) Run(run func(ctx context.Context, cids []cid.Cid, userId uint)) *MockUploadService_ProcessUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cid.Cid
		if args[1] != nil {
			arg1 = args[1].([]cid.Cid)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) Return(err error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) RunAndReturn(run func(ctx context.Context, cids []cid.Cid, userId uint) error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(run)
	return _c
}
