// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ipfs/boxo/ipns"
	"github.com/libp2p/go-libp2p/core/crypto"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockIPNSPublisherService creates a new instance of MockIPNSPublisherService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPNSPublisherService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPNSPublisherService {
	mock := &MockIPNSPublisherService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPNSPublisherService is an autogenerated mock type for the IPNSPublisherService type
type MockIPNSPublisherService struct {
	mock.Mock
}

type MockIPNSPublisherService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPNSPublisherService) EXPECT() *MockIPNSPublisherService_Expecter {
	return &MockIPNSPublisherService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockIPNSPublisherService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockIPNSPublisherService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockIPNSPublisherService_Expecter) Config() *MockIPNSPublisherService_Config_Call {
	return &MockIPNSPublisherService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockIPNSPublisherService_Config_Call) Run(run func()) *MockIPNSPublisherService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSPublisherService_Config_Call) Return(manager config.Manager) *MockIPNSPublisherService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockIPNSPublisherService_Config_Call) RunAndReturn(run func() config.Manager) *MockIPNSPublisherService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockIPNSPublisherService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockIPNSPublisherService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockIPNSPublisherService_Expecter) Context() *MockIPNSPublisherService_Context_Call {
	return &MockIPNSPublisherService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockIPNSPublisherService_Context_Call) Run(run func()) *MockIPNSPublisherService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSPublisherService_Context_Call) Return(context core.Context) *MockIPNSPublisherService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockIPNSPublisherService_Context_Call) RunAndReturn(run func() core.Context) *MockIPNSPublisherService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIPNSPublisherService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockIPNSPublisherService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockIPNSPublisherService_Expecter) DB() *MockIPNSPublisherService_DB_Call {
	return &MockIPNSPublisherService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockIPNSPublisherService_DB_Call) Run(run func()) *MockIPNSPublisherService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSPublisherService_DB_Call) Return(dB *gorm.DB) *MockIPNSPublisherService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIPNSPublisherService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockIPNSPublisherService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublished provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) GetPublished(ctx context.Context, keyID string, checkRouting bool) (*ipns.Record, error) {
	ret := _mock.Called(ctx, keyID, checkRouting)

	if len(ret) == 0 {
		panic("no return value specified for GetPublished")
	}

	var r0 *ipns.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) (*ipns.Record, error)); ok {
		return returnFunc(ctx, keyID, checkRouting)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, bool) *ipns.Record); ok {
		r0 = returnFunc(ctx, keyID, checkRouting)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipns.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, bool) error); ok {
		r1 = returnFunc(ctx, keyID, checkRouting)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSPublisherService_GetPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublished'
type MockIPNSPublisherService_GetPublished_Call struct {
	*mock.Call
}

// GetPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - checkRouting bool
func (_e *MockIPNSPublisherService_Expecter) GetPublished(ctx interface{}, keyID interface{}, checkRouting interface{}) *MockIPNSPublisherService_GetPublished_Call {
	return &MockIPNSPublisherService_GetPublished_Call{Call: _e.mock.On("GetPublished", ctx, keyID, checkRouting)}
}

func (_c *MockIPNSPublisherService_GetPublished_Call) Run(run func(ctx context.Context, keyID string, checkRouting bool)) *MockIPNSPublisherService_GetPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_GetPublished_Call) Return(record *ipns.Record, err error) *MockIPNSPublisherService_GetPublished_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockIPNSPublisherService_GetPublished_Call) RunAndReturn(run func(ctx context.Context, keyID string, checkRouting bool) (*ipns.Record, error)) *MockIPNSPublisherService_GetPublished_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIPNSPublisherService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIPNSPublisherService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIPNSPublisherService_Expecter) ID() *MockIPNSPublisherService_ID_Call {
	return &MockIPNSPublisherService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIPNSPublisherService_ID_Call) Run(run func()) *MockIPNSPublisherService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSPublisherService_ID_Call) Return(s string) *MockIPNSPublisherService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIPNSPublisherService_ID_Call) RunAndReturn(run func() string) *MockIPNSPublisherService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublished provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) ListPublished(ctx context.Context) (map[ipns.Name]*ipns.Record, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPublished")
	}

	var r0 map[ipns.Name]*ipns.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[ipns.Name]*ipns.Record, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[ipns.Name]*ipns.Record); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[ipns.Name]*ipns.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSPublisherService_ListPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublished'
type MockIPNSPublisherService_ListPublished_Call struct {
	*mock.Call
}

// ListPublished is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPNSPublisherService_Expecter) ListPublished(ctx interface{}) *MockIPNSPublisherService_ListPublished_Call {
	return &MockIPNSPublisherService_ListPublished_Call{Call: _e.mock.On("ListPublished", ctx)}
}

func (_c *MockIPNSPublisherService_ListPublished_Call) Run(run func(ctx context.Context)) *MockIPNSPublisherService_ListPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_ListPublished_Call) Return(nameToRecord map[ipns.Name]*ipns.Record, err error) *MockIPNSPublisherService_ListPublished_Call {
	_c.Call.Return(nameToRecord, err)
	return _c
}

func (_c *MockIPNSPublisherService_ListPublished_Call) RunAndReturn(run func(ctx context.Context) (map[ipns.Name]*ipns.Record, error)) *MockIPNSPublisherService_ListPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockIPNSPublisherService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockIPNSPublisherService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockIPNSPublisherService_Expecter) Logger() *MockIPNSPublisherService_Logger_Call {
	return &MockIPNSPublisherService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockIPNSPublisherService_Logger_Call) Run(run func()) *MockIPNSPublisherService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSPublisherService_Logger_Call) Return(logger *core.Logger) *MockIPNSPublisherService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockIPNSPublisherService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockIPNSPublisherService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// PublishCID provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) PublishCID(ctx context.Context, keyID string, cidStr string, ttl time.Duration) error {
	ret := _mock.Called(ctx, keyID, cidStr, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PublishCID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, keyID, cidStr, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSPublisherService_PublishCID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishCID'
type MockIPNSPublisherService_PublishCID_Call struct {
	*mock.Call
}

// PublishCID is a helper method to define mock.On call
//   - ctx context.Context
//   - keyID string
//   - cidStr string
//   - ttl time.Duration
func (_e *MockIPNSPublisherService_Expecter) PublishCID(ctx interface{}, keyID interface{}, cidStr interface{}, ttl interface{}) *MockIPNSPublisherService_PublishCID_Call {
	return &MockIPNSPublisherService_PublishCID_Call{Call: _e.mock.On("PublishCID", ctx, keyID, cidStr, ttl)}
}

func (_c *MockIPNSPublisherService_PublishCID_Call) Run(run func(ctx context.Context, keyID string, cidStr string, ttl time.Duration)) *MockIPNSPublisherService_PublishCID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_PublishCID_Call) Return(err error) *MockIPNSPublisherService_PublishCID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSPublisherService_PublishCID_Call) RunAndReturn(run func(ctx context.Context, keyID string, cidStr string, ttl time.Duration) error) *MockIPNSPublisherService_PublishCID_Call {
	_c.Call.Return(run)
	return _c
}

// PublishWithKey provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) PublishWithKey(ctx context.Context, privKey crypto.PrivKey, cidStr string, ttl time.Duration) error {
	ret := _mock.Called(ctx, privKey, cidStr, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PublishWithKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.PrivKey, string, time.Duration) error); ok {
		r0 = returnFunc(ctx, privKey, cidStr, ttl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSPublisherService_PublishWithKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishWithKey'
type MockIPNSPublisherService_PublishWithKey_Call struct {
	*mock.Call
}

// PublishWithKey is a helper method to define mock.On call
//   - ctx context.Context
//   - privKey crypto.PrivKey
//   - cidStr string
//   - ttl time.Duration
func (_e *MockIPNSPublisherService_Expecter) PublishWithKey(ctx interface{}, privKey interface{}, cidStr interface{}, ttl interface{}) *MockIPNSPublisherService_PublishWithKey_Call {
	return &MockIPNSPublisherService_PublishWithKey_Call{Call: _e.mock.On("PublishWithKey", ctx, privKey, cidStr, ttl)}
}

func (_c *MockIPNSPublisherService_PublishWithKey_Call) Run(run func(ctx context.Context, privKey crypto.PrivKey, cidStr string, ttl time.Duration)) *MockIPNSPublisherService_PublishWithKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.PrivKey
		if args[1] != nil {
			arg1 = args[1].(crypto.PrivKey)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_PublishWithKey_Call) Return(err error) *MockIPNSPublisherService_PublishWithKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSPublisherService_PublishWithKey_Call) RunAndReturn(run func(ctx context.Context, privKey crypto.PrivKey, cidStr string, ttl time.Duration) error) *MockIPNSPublisherService_PublishWithKey_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockIPNSPublisherService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockIPNSPublisherService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockIPNSPublisherService_Expecter) SetConfig(cfg interface{}) *MockIPNSPublisherService_SetConfig_Call {
	return &MockIPNSPublisherService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockIPNSPublisherService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockIPNSPublisherService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_SetConfig_Call) Return() *MockIPNSPublisherService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSPublisherService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockIPNSPublisherService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockIPNSPublisherService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockIPNSPublisherService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockIPNSPublisherService_Expecter) SetContext(ctx interface{}) *MockIPNSPublisherService_SetContext_Call {
	return &MockIPNSPublisherService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockIPNSPublisherService_SetContext_Call) Run(run func(ctx core.Context)) *MockIPNSPublisherService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_SetContext_Call) Return() *MockIPNSPublisherService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSPublisherService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockIPNSPublisherService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockIPNSPublisherService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockIPNSPublisherService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockIPNSPublisherService_Expecter) SetDB(db interface{}) *MockIPNSPublisherService_SetDB_Call {
	return &MockIPNSPublisherService_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockIPNSPublisherService_SetDB_Call) Run(run func(db *gorm.DB)) *MockIPNSPublisherService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_SetDB_Call) Return() *MockIPNSPublisherService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSPublisherService_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockIPNSPublisherService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockIPNSPublisherService
func (_mock *MockIPNSPublisherService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockIPNSPublisherService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockIPNSPublisherService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockIPNSPublisherService_Expecter) SetLogger(logger interface{}) *MockIPNSPublisherService_SetLogger_Call {
	return &MockIPNSPublisherService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockIPNSPublisherService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockIPNSPublisherService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSPublisherService_SetLogger_Call) Return() *MockIPNSPublisherService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSPublisherService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockIPNSPublisherService_SetLogger_Call {
	_c.Run(run)
	return _c
}
