// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/core"
)

// NewMockMetadataStore creates a new instance of MockMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataStore {
	mock := &MockMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataStore is an autogenerated mock type for the MetadataStore type
type MockMetadataStore struct {
	mock.Mock
}

type MockMetadataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataStore) EXPECT() *MockMetadataStore_Expecter {
	return &MockMetadataStore_Expecter{mock: &_m.Mock}
}

// BlockChildren provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BlockChildren(ctx context.Context, c cid.Cid, max *int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, c, max)

	if len(ret) == 0 {
		panic("no return value specified for BlockChildren")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, *int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, c, max)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, *int) []cid.Cid); ok {
		r0 = returnFunc(ctx, c, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, *int) error); ok {
		r1 = returnFunc(ctx, c, max)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_BlockChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockChildren'
type MockMetadataStore_BlockChildren_Call struct {
	*mock.Call
}

// BlockChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
//   - max *int
func (_e *MockMetadataStore_Expecter) BlockChildren(ctx interface{}, c interface{}, max interface{}) *MockMetadataStore_BlockChildren_Call {
	return &MockMetadataStore_BlockChildren_Call{Call: _e.mock.On("BlockChildren", ctx, c, max)}
}

func (_c *MockMetadataStore_BlockChildren_Call) Run(run func(ctx context.Context, c cid.Cid, max *int)) *MockMetadataStore_BlockChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BlockChildren_Call) Return(siblings []cid.Cid, err error) *MockMetadataStore_BlockChildren_Call {
	_c.Call.Return(siblings, err)
	return _c
}

func (_c *MockMetadataStore_BlockChildren_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid, max *int) ([]cid.Cid, error)) *MockMetadataStore_BlockChildren_Call {
	_c.Call.Return(run)
	return _c
}

// BlockExists provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BlockExists(ctx context.Context, c cid.Cid) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for BlockExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_BlockExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockExists'
type MockMetadataStore_BlockExists_Call struct {
	*mock.Call
}

// BlockExists is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockMetadataStore_Expecter) BlockExists(ctx interface{}, c interface{}) *MockMetadataStore_BlockExists_Call {
	return &MockMetadataStore_BlockExists_Call{Call: _e.mock.On("BlockExists", ctx, c)}
}

func (_c *MockMetadataStore_BlockExists_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockMetadataStore_BlockExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BlockExists_Call) Return(err error) *MockMetadataStore_BlockExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_BlockExists_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) error) *MockMetadataStore_BlockExists_Call {
	_c.Call.Return(run)
	return _c
}

// BlockSiblings provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BlockSiblings(ctx context.Context, c cid.Cid, max int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, c, max)

	if len(ret) == 0 {
		panic("no return value specified for BlockSiblings")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, c, max)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, int) []cid.Cid); ok {
		r0 = returnFunc(ctx, c, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, int) error); ok {
		r1 = returnFunc(ctx, c, max)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_BlockSiblings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockSiblings'
type MockMetadataStore_BlockSiblings_Call struct {
	*mock.Call
}

// BlockSiblings is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
//   - max int
func (_e *MockMetadataStore_Expecter) BlockSiblings(ctx interface{}, c interface{}, max interface{}) *MockMetadataStore_BlockSiblings_Call {
	return &MockMetadataStore_BlockSiblings_Call{Call: _e.mock.On("BlockSiblings", ctx, c, max)}
}

func (_c *MockMetadataStore_BlockSiblings_Call) Run(run func(ctx context.Context, c cid.Cid, max int)) *MockMetadataStore_BlockSiblings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BlockSiblings_Call) Return(siblings []cid.Cid, err error) *MockMetadataStore_BlockSiblings_Call {
	_c.Call.Return(siblings, err)
	return _c
}

func (_c *MockMetadataStore_BlockSiblings_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid, max int) ([]cid.Cid, error)) *MockMetadataStore_BlockSiblings_Call {
	_c.Call.Return(run)
	return _c
}

// Pin provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Pin(ctx context.Context, pinnedBlock core.PinnedBlock) error {
	ret := _mock.Called(ctx, pinnedBlock)

	if len(ret) == 0 {
		panic("no return value specified for Pin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.PinnedBlock) error); ok {
		r0 = returnFunc(ctx, pinnedBlock)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_Pin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pin'
type MockMetadataStore_Pin_Call struct {
	*mock.Call
}

// Pin is a helper method to define mock.On call
//   - ctx context.Context
//   - pinnedBlock core.PinnedBlock
func (_e *MockMetadataStore_Expecter) Pin(ctx interface{}, pinnedBlock interface{}) *MockMetadataStore_Pin_Call {
	return &MockMetadataStore_Pin_Call{Call: _e.mock.On("Pin", ctx, pinnedBlock)}
}

func (_c *MockMetadataStore_Pin_Call) Run(run func(ctx context.Context, pinnedBlock core.PinnedBlock)) *MockMetadataStore_Pin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.PinnedBlock
		if args[1] != nil {
			arg1 = args[1].(core.PinnedBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Pin_Call) Return(err error) *MockMetadataStore_Pin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_Pin_Call) RunAndReturn(run func(ctx context.Context, pinnedBlock core.PinnedBlock) error) *MockMetadataStore_Pin_Call {
	_c.Call.Return(run)
	return _c
}

// Pinned provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Pinned(ctx context.Context, offset int, limit int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Pinned")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []cid.Cid); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_Pinned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pinned'
type MockMetadataStore_Pinned_Call struct {
	*mock.Call
}

// Pinned is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockMetadataStore_Expecter) Pinned(ctx interface{}, offset interface{}, limit interface{}) *MockMetadataStore_Pinned_Call {
	return &MockMetadataStore_Pinned_Call{Call: _e.mock.On("Pinned", ctx, offset, limit)}
}

func (_c *MockMetadataStore_Pinned_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockMetadataStore_Pinned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Pinned_Call) Return(roots []cid.Cid, err error) *MockMetadataStore_Pinned_Call {
	_c.Call.Return(roots, err)
	return _c
}

func (_c *MockMetadataStore_Pinned_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]cid.Cid, error)) *MockMetadataStore_Pinned_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Size(ctx context.Context, c cid.Cid) (uint64, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (uint64, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) uint64); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockMetadataStore_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockMetadataStore_Expecter) Size(ctx interface{}, c interface{}) *MockMetadataStore_Size_Call {
	return &MockMetadataStore_Size_Call{Call: _e.mock.On("Size", ctx, c)}
}

func (_c *MockMetadataStore_Size_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockMetadataStore_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Size_Call) Return(v uint64, err error) *MockMetadataStore_Size_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockMetadataStore_Size_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (uint64, error)) *MockMetadataStore_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Unpin provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Unpin(ctx context.Context, c cid.Cid) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Unpin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_Unpin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpin'
type MockMetadataStore_Unpin_Call struct {
	*mock.Call
}

// Unpin is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockMetadataStore_Expecter) Unpin(ctx interface{}, c interface{}) *MockMetadataStore_Unpin_Call {
	return &MockMetadataStore_Unpin_Call{Call: _e.mock.On("Unpin", ctx, c)}
}

func (_c *MockMetadataStore_Unpin_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockMetadataStore_Unpin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Unpin_Call) Return(err error) *MockMetadataStore_Unpin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_Unpin_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) error) *MockMetadataStore_Unpin_Call {
	_c.Call.Return(run)
	return _c
}
