// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"io"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal-plugin-ipfs/internal/quota"
	"go.lumeweb.com/portal-plugin-ipfs/internal/upload"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockUploadService creates a new instance of MockUploadService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUploadService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUploadService {
	mock := &MockUploadService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUploadService is an autogenerated mock type for the UploadService type
type MockUploadService struct {
	mock.Mock
}

type MockUploadService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUploadService) EXPECT() *MockUploadService_Expecter {
	return &MockUploadService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockUploadService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockUploadService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) Config() *MockUploadService_Config_Call {
	return &MockUploadService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockUploadService_Config_Call) Run(run func()) *MockUploadService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_Config_Call) Return(manager config.Manager) *MockUploadService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockUploadService_Config_Call) RunAndReturn(run func() config.Manager) *MockUploadService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockUploadService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockUploadService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) Context() *MockUploadService_Context_Call {
	return &MockUploadService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockUploadService_Context_Call) Run(run func()) *MockUploadService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_Context_Call) Return(context core.Context) *MockUploadService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockUploadService_Context_Call) RunAndReturn(run func() core.Context) *MockUploadService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateRootPin provides a mock function for the type MockUploadService
func (_mock *MockUploadService) CreateRootPin(ctx context.Context, cid1 cid.Cid, userId uint, name string) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, cid1, userId, name)

	if len(ret) == 0 {
		panic("no return value specified for CreateRootPin")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, uint, string) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, cid1, userId, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, uint, string) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, cid1, userId, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, uint, string) error); ok {
		r1 = returnFunc(ctx, cid1, userId, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUploadService_CreateRootPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateRootPin'
type MockUploadService_CreateRootPin_Call struct {
	*mock.Call
}

// CreateRootPin is a helper method to define mock.On call
//   - ctx context.Context
//   - cid1 cid.Cid
//   - userId uint
//   - name string
func (_e *MockUploadService_Expecter) CreateRootPin(ctx any, cid1 any, userId any, name any) *MockUploadService_CreateRootPin_Call {
	return &MockUploadService_CreateRootPin_Call{Call: _e.mock.On("CreateRootPin", ctx, cid1, userId, name)}
}

func (_c *MockUploadService_CreateRootPin_Call) Run(run func(ctx context.Context, cid1 cid.Cid, userId uint, name string)) *MockUploadService_CreateRootPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUploadService_CreateRootPin_Call) Return(iPFSPin *db.IPFSPin, err error) *MockUploadService_CreateRootPin_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockUploadService_CreateRootPin_Call) RunAndReturn(run func(ctx context.Context, cid1 cid.Cid, userId uint, name string) (*db.IPFSPin, error)) *MockUploadService_CreateRootPin_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockUploadService
func (_mock *MockUploadService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockUploadService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockUploadService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) DB() *MockUploadService_DB_Call {
	return &MockUploadService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockUploadService_DB_Call) Run(run func()) *MockUploadService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_DB_Call) Return(dB *gorm.DB) *MockUploadService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockUploadService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockUploadService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) HandleUpload(ctx context.Context, reader io.ReadSeekCloser, userId uint) (cid.Cid, string, error) {
	ret := _mock.Called(ctx, reader, userId)

	if len(ret) == 0 {
		panic("no return value specified for HandleUpload")
	}

	var r0 cid.Cid
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, uint) (cid.Cid, string, error)); ok {
		return returnFunc(ctx, reader, userId)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, uint) cid.Cid); ok {
		r0 = returnFunc(ctx, reader, userId)
	} else {
		r0 = ret.Get(0).(cid.Cid)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.ReadSeekCloser, uint) string); ok {
		r1 = returnFunc(ctx, reader, userId)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.ReadSeekCloser, uint) error); ok {
		r2 = returnFunc(ctx, reader, userId)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_HandleUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUpload'
type MockUploadService_HandleUpload_Call struct {
	*mock.Call
}

// HandleUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.ReadSeekCloser
//   - userId uint
func (_e *MockUploadService_Expecter) HandleUpload(ctx any, reader any, userId any) *MockUploadService_HandleUpload_Call {
	return &MockUploadService_HandleUpload_Call{Call: _e.mock.On("HandleUpload", ctx, reader, userId)}
}

func (_c *MockUploadService_HandleUpload_Call) Run(run func(ctx context.Context, reader io.ReadSeekCloser, userId uint)) *MockUploadService_HandleUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadSeekCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadSeekCloser)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) Return(cid1 cid.Cid, s string, err error) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(cid1, s, err)
	return _c
}

func (_c *MockUploadService_HandleUpload_Call) RunAndReturn(run func(ctx context.Context, reader io.ReadSeekCloser, userId uint) (cid.Cid, string, error)) *MockUploadService_HandleUpload_Call {
	_c.Call.Return(run)
	return _c
}

// HandleUploadWithMode provides a mock function for the type MockUploadService
func (_mock *MockUploadService) HandleUploadWithMode(ctx context.Context, reader io.ReadSeekCloser, userId uint, mode upload.ArchiveMode) (cid.Cid, string, error) {
	ret := _mock.Called(ctx, reader, userId, mode)

	if len(ret) == 0 {
		panic("no return value specified for HandleUploadWithMode")
	}

	var r0 cid.Cid
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, uint, upload.ArchiveMode) (cid.Cid, string, error)); ok {
		return returnFunc(ctx, reader, userId, mode)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, io.ReadSeekCloser, uint, upload.ArchiveMode) cid.Cid); ok {
		r0 = returnFunc(ctx, reader, userId, mode)
	} else {
		r0 = ret.Get(0).(cid.Cid)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, io.ReadSeekCloser, uint, upload.ArchiveMode) string); ok {
		r1 = returnFunc(ctx, reader, userId, mode)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, io.ReadSeekCloser, uint, upload.ArchiveMode) error); ok {
		r2 = returnFunc(ctx, reader, userId, mode)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockUploadService_HandleUploadWithMode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleUploadWithMode'
type MockUploadService_HandleUploadWithMode_Call struct {
	*mock.Call
}

// HandleUploadWithMode is a helper method to define mock.On call
//   - ctx context.Context
//   - reader io.ReadSeekCloser
//   - userId uint
//   - mode upload.ArchiveMode
func (_e *MockUploadService_Expecter) HandleUploadWithMode(ctx any, reader any, userId any, mode any) *MockUploadService_HandleUploadWithMode_Call {
	return &MockUploadService_HandleUploadWithMode_Call{Call: _e.mock.On("HandleUploadWithMode", ctx, reader, userId, mode)}
}

func (_c *MockUploadService_HandleUploadWithMode_Call) Run(run func(ctx context.Context, reader io.ReadSeekCloser, userId uint, mode upload.ArchiveMode)) *MockUploadService_HandleUploadWithMode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 io.ReadSeekCloser
		if args[1] != nil {
			arg1 = args[1].(io.ReadSeekCloser)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 upload.ArchiveMode
		if args[3] != nil {
			arg3 = args[3].(upload.ArchiveMode)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUploadService_HandleUploadWithMode_Call) Return(cid1 cid.Cid, s string, err error) *MockUploadService_HandleUploadWithMode_Call {
	_c.Call.Return(cid1, s, err)
	return _c
}

func (_c *MockUploadService_HandleUploadWithMode_Call) RunAndReturn(run func(ctx context.Context, reader io.ReadSeekCloser, userId uint, mode upload.ArchiveMode) (cid.Cid, string, error)) *MockUploadService_HandleUploadWithMode_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockUploadService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockUploadService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) ID() *MockUploadService_ID_Call {
	return &MockUploadService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockUploadService_ID_Call) Run(run func()) *MockUploadService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_ID_Call) Return(s string) *MockUploadService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockUploadService_ID_Call) RunAndReturn(run func() string) *MockUploadService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockUploadService
func (_mock *MockUploadService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockUploadService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockUploadService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockUploadService_Expecter) Logger() *MockUploadService_Logger_Call {
	return &MockUploadService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockUploadService_Logger_Call) Run(run func()) *MockUploadService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUploadService_Logger_Call) Return(logger *core.Logger) *MockUploadService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockUploadService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockUploadService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessUpload provides a mock function for the type MockUploadService
func (_mock *MockUploadService) ProcessUpload(ctx context.Context, cids []cid.Cid, userId uint, reservations map[cid.Cid]*quota.BlockReservations) error {
	ret := _mock.Called(ctx, cids, userId, reservations)

	if len(ret) == 0 {
		panic("no return value specified for ProcessUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid, uint, map[cid.Cid]*quota.BlockReservations) error); ok {
		r0 = returnFunc(ctx, cids, userId, reservations)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUploadService_ProcessUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessUpload'
type MockUploadService_ProcessUpload_Call struct {
	*mock.Call
}

// ProcessUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []cid.Cid
//   - userId uint
//   - reservations map[cid.Cid]*quota.BlockReservations
func (_e *MockUploadService_Expecter) ProcessUpload(ctx any, cids any, userId any, reservations any) *MockUploadService_ProcessUpload_Call {
	return &MockUploadService_ProcessUpload_Call{Call: _e.mock.On("ProcessUpload", ctx, cids, userId, reservations)}
}

func (_c *MockUploadService_ProcessUpload_Call) Run(run func(ctx context.Context, cids []cid.Cid, userId uint, reservations map[cid.Cid]*quota.BlockReservations)) *MockUploadService_ProcessUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cid.Cid
		if args[1] != nil {
			arg1 = args[1].([]cid.Cid)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 map[cid.Cid]*quota.BlockReservations
		if args[3] != nil {
			arg3 = args[3].(map[cid.Cid]*quota.BlockReservations)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) Return(err error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUploadService_ProcessUpload_Call) RunAndReturn(run func(ctx context.Context, cids []cid.Cid, userId uint, reservations map[cid.Cid]*quota.BlockReservations) error) *MockUploadService_ProcessUpload_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockUploadService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockUploadService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockUploadService_Expecter) SetConfig(cfg any) *MockUploadService_SetConfig_Call {
	return &MockUploadService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockUploadService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockUploadService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetConfig_Call) Return() *MockUploadService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockUploadService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockUploadService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockUploadService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockUploadService_Expecter) SetContext(ctx any) *MockUploadService_SetContext_Call {
	return &MockUploadService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockUploadService_SetContext_Call) Run(run func(ctx core.Context)) *MockUploadService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetContext_Call) Return() *MockUploadService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockUploadService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockUploadService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockUploadService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockUploadService_Expecter) SetDB(db1 any) *MockUploadService_SetDB_Call {
	return &MockUploadService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockUploadService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockUploadService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetDB_Call) Return() *MockUploadService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockUploadService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockUploadService
func (_mock *MockUploadService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockUploadService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockUploadService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockUploadService_Expecter) SetLogger(logger any) *MockUploadService_SetLogger_Call {
	return &MockUploadService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockUploadService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockUploadService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUploadService_SetLogger_Call) Return() *MockUploadService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockUploadService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockUploadService_SetLogger_Call {
	_c.Run(run)
	return _c
}
