// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/libp2p/go-libp2p/core/crypto"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockIPNSKeyService creates a new instance of MockIPNSKeyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPNSKeyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPNSKeyService {
	mock := &MockIPNSKeyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPNSKeyService is an autogenerated mock type for the IPNSKeyService type
type MockIPNSKeyService struct {
	mock.Mock
}

type MockIPNSKeyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPNSKeyService) EXPECT() *MockIPNSKeyService_Expecter {
	return &MockIPNSKeyService_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockIPNSKeyService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockIPNSKeyService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockIPNSKeyService_Expecter) Config() *MockIPNSKeyService_Config_Call {
	return &MockIPNSKeyService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockIPNSKeyService_Config_Call) Run(run func()) *MockIPNSKeyService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSKeyService_Config_Call) Return(manager config.Manager) *MockIPNSKeyService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockIPNSKeyService_Config_Call) RunAndReturn(run func() config.Manager) *MockIPNSKeyService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockIPNSKeyService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockIPNSKeyService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockIPNSKeyService_Expecter) Context() *MockIPNSKeyService_Context_Call {
	return &MockIPNSKeyService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockIPNSKeyService_Context_Call) Run(run func()) *MockIPNSKeyService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSKeyService_Context_Call) Return(context core.Context) *MockIPNSKeyService_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockIPNSKeyService_Context_Call) RunAndReturn(run func() core.Context) *MockIPNSKeyService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateKey provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) CreateKey(ctx context.Context, userID uint, name string, keyType int) (*db.IPFSIPNSKey, error) {
	ret := _mock.Called(ctx, userID, name, keyType)

	if len(ret) == 0 {
		panic("no return value specified for CreateKey")
	}

	var r0 *db.IPFSIPNSKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, int) (*db.IPFSIPNSKey, error)); ok {
		return returnFunc(ctx, userID, name, keyType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, int) *db.IPFSIPNSKey); ok {
		r0 = returnFunc(ctx, userID, name, keyType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSIPNSKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, int) error); ok {
		r1 = returnFunc(ctx, userID, name, keyType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSKeyService_CreateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateKey'
type MockIPNSKeyService_CreateKey_Call struct {
	*mock.Call
}

// CreateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
//   - keyType int
func (_e *MockIPNSKeyService_Expecter) CreateKey(ctx interface{}, userID interface{}, name interface{}, keyType interface{}) *MockIPNSKeyService_CreateKey_Call {
	return &MockIPNSKeyService_CreateKey_Call{Call: _e.mock.On("CreateKey", ctx, userID, name, keyType)}
}

func (_c *MockIPNSKeyService_CreateKey_Call) Run(run func(ctx context.Context, userID uint, name string, keyType int)) *MockIPNSKeyService_CreateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_CreateKey_Call) Return(iPFSIPNSKey *db.IPFSIPNSKey, err error) *MockIPNSKeyService_CreateKey_Call {
	_c.Call.Return(iPFSIPNSKey, err)
	return _c
}

func (_c *MockIPNSKeyService_CreateKey_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string, keyType int) (*db.IPFSIPNSKey, error)) *MockIPNSKeyService_CreateKey_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIPNSKeyService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockIPNSKeyService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockIPNSKeyService_Expecter) DB() *MockIPNSKeyService_DB_Call {
	return &MockIPNSKeyService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockIPNSKeyService_DB_Call) Run(run func()) *MockIPNSKeyService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSKeyService_DB_Call) Return(dB *gorm.DB) *MockIPNSKeyService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIPNSKeyService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockIPNSKeyService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteKey provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) DeleteKey(ctx context.Context, userID uint, keyID uint) error {
	ret := _mock.Called(ctx, userID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteKey")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, keyID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSKeyService_DeleteKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteKey'
type MockIPNSKeyService_DeleteKey_Call struct {
	*mock.Call
}

// DeleteKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - keyID uint
func (_e *MockIPNSKeyService_Expecter) DeleteKey(ctx interface{}, userID interface{}, keyID interface{}) *MockIPNSKeyService_DeleteKey_Call {
	return &MockIPNSKeyService_DeleteKey_Call{Call: _e.mock.On("DeleteKey", ctx, userID, keyID)}
}

func (_c *MockIPNSKeyService_DeleteKey_Call) Run(run func(ctx context.Context, userID uint, keyID uint)) *MockIPNSKeyService_DeleteKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_DeleteKey_Call) Return(err error) *MockIPNSKeyService_DeleteKey_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSKeyService_DeleteKey_Call) RunAndReturn(run func(ctx context.Context, userID uint, keyID uint) error) *MockIPNSKeyService_DeleteKey_Call {
	_c.Call.Return(run)
	return _c
}

// ExportKey provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) ExportKey(ctx context.Context, userID uint, keyID uint) (string, error) {
	ret := _mock.Called(ctx, userID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for ExportKey")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (string, error)); ok {
		return returnFunc(ctx, userID, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) string); ok {
		r0 = returnFunc(ctx, userID, keyID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSKeyService_ExportKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExportKey'
type MockIPNSKeyService_ExportKey_Call struct {
	*mock.Call
}

// ExportKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - keyID uint
func (_e *MockIPNSKeyService_Expecter) ExportKey(ctx interface{}, userID interface{}, keyID interface{}) *MockIPNSKeyService_ExportKey_Call {
	return &MockIPNSKeyService_ExportKey_Call{Call: _e.mock.On("ExportKey", ctx, userID, keyID)}
}

func (_c *MockIPNSKeyService_ExportKey_Call) Run(run func(ctx context.Context, userID uint, keyID uint)) *MockIPNSKeyService_ExportKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_ExportKey_Call) Return(s string, err error) *MockIPNSKeyService_ExportKey_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockIPNSKeyService_ExportKey_Call) RunAndReturn(run func(ctx context.Context, userID uint, keyID uint) (string, error)) *MockIPNSKeyService_ExportKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeyByID provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) GetKeyByID(ctx context.Context, userID uint, keyID uint) (*db.IPFSIPNSKey, error) {
	ret := _mock.Called(ctx, userID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetKeyByID")
	}

	var r0 *db.IPFSIPNSKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*db.IPFSIPNSKey, error)); ok {
		return returnFunc(ctx, userID, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *db.IPFSIPNSKey); ok {
		r0 = returnFunc(ctx, userID, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSIPNSKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSKeyService_GetKeyByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeyByID'
type MockIPNSKeyService_GetKeyByID_Call struct {
	*mock.Call
}

// GetKeyByID is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - keyID uint
func (_e *MockIPNSKeyService_Expecter) GetKeyByID(ctx interface{}, userID interface{}, keyID interface{}) *MockIPNSKeyService_GetKeyByID_Call {
	return &MockIPNSKeyService_GetKeyByID_Call{Call: _e.mock.On("GetKeyByID", ctx, userID, keyID)}
}

func (_c *MockIPNSKeyService_GetKeyByID_Call) Run(run func(ctx context.Context, userID uint, keyID uint)) *MockIPNSKeyService_GetKeyByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_GetKeyByID_Call) Return(iPFSIPNSKey *db.IPFSIPNSKey, err error) *MockIPNSKeyService_GetKeyByID_Call {
	_c.Call.Return(iPFSIPNSKey, err)
	return _c
}

func (_c *MockIPNSKeyService_GetKeyByID_Call) RunAndReturn(run func(ctx context.Context, userID uint, keyID uint) (*db.IPFSIPNSKey, error)) *MockIPNSKeyService_GetKeyByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateKey provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) GetPrivateKey(ctx context.Context, userID uint, keyID uint) (crypto.PrivKey, error) {
	ret := _mock.Called(ctx, userID, keyID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 crypto.PrivKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (crypto.PrivKey, error)); ok {
		return returnFunc(ctx, userID, keyID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) crypto.PrivKey); ok {
		r0 = returnFunc(ctx, userID, keyID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, keyID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSKeyService_GetPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKey'
type MockIPNSKeyService_GetPrivateKey_Call struct {
	*mock.Call
}

// GetPrivateKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - keyID uint
func (_e *MockIPNSKeyService_Expecter) GetPrivateKey(ctx interface{}, userID interface{}, keyID interface{}) *MockIPNSKeyService_GetPrivateKey_Call {
	return &MockIPNSKeyService_GetPrivateKey_Call{Call: _e.mock.On("GetPrivateKey", ctx, userID, keyID)}
}

func (_c *MockIPNSKeyService_GetPrivateKey_Call) Run(run func(ctx context.Context, userID uint, keyID uint)) *MockIPNSKeyService_GetPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_GetPrivateKey_Call) Return(privKey crypto.PrivKey, err error) *MockIPNSKeyService_GetPrivateKey_Call {
	_c.Call.Return(privKey, err)
	return _c
}

func (_c *MockIPNSKeyService_GetPrivateKey_Call) RunAndReturn(run func(ctx context.Context, userID uint, keyID uint) (crypto.PrivKey, error)) *MockIPNSKeyService_GetPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateKeyByPeerID provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) GetPrivateKeyByPeerID(ctx context.Context, peerID string) (crypto.PrivKey, uint, error) {
	ret := _mock.Called(ctx, peerID)

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKeyByPeerID")
	}

	var r0 crypto.PrivKey
	var r1 uint
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (crypto.PrivKey, uint, error)); ok {
		return returnFunc(ctx, peerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) crypto.PrivKey); ok {
		r0 = returnFunc(ctx, peerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) uint); ok {
		r1 = returnFunc(ctx, peerID)
	} else {
		r1 = ret.Get(1).(uint)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, peerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPNSKeyService_GetPrivateKeyByPeerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKeyByPeerID'
type MockIPNSKeyService_GetPrivateKeyByPeerID_Call struct {
	*mock.Call
}

// GetPrivateKeyByPeerID is a helper method to define mock.On call
//   - ctx context.Context
//   - peerID string
func (_e *MockIPNSKeyService_Expecter) GetPrivateKeyByPeerID(ctx interface{}, peerID interface{}) *MockIPNSKeyService_GetPrivateKeyByPeerID_Call {
	return &MockIPNSKeyService_GetPrivateKeyByPeerID_Call{Call: _e.mock.On("GetPrivateKeyByPeerID", ctx, peerID)}
}

func (_c *MockIPNSKeyService_GetPrivateKeyByPeerID_Call) Run(run func(ctx context.Context, peerID string)) *MockIPNSKeyService_GetPrivateKeyByPeerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_GetPrivateKeyByPeerID_Call) Return(privKey crypto.PrivKey, v uint, err error) *MockIPNSKeyService_GetPrivateKeyByPeerID_Call {
	_c.Call.Return(privKey, v, err)
	return _c
}

func (_c *MockIPNSKeyService_GetPrivateKeyByPeerID_Call) RunAndReturn(run func(ctx context.Context, peerID string) (crypto.PrivKey, uint, error)) *MockIPNSKeyService_GetPrivateKeyByPeerID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIPNSKeyService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIPNSKeyService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIPNSKeyService_Expecter) ID() *MockIPNSKeyService_ID_Call {
	return &MockIPNSKeyService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIPNSKeyService_ID_Call) Run(run func()) *MockIPNSKeyService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSKeyService_ID_Call) Return(s string) *MockIPNSKeyService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIPNSKeyService_ID_Call) RunAndReturn(run func() string) *MockIPNSKeyService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ImportKey provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) ImportKey(ctx context.Context, userID uint, name string, privateKeyBase64 string) (*db.IPFSIPNSKey, error) {
	ret := _mock.Called(ctx, userID, name, privateKeyBase64)

	if len(ret) == 0 {
		panic("no return value specified for ImportKey")
	}

	var r0 *db.IPFSIPNSKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) (*db.IPFSIPNSKey, error)); ok {
		return returnFunc(ctx, userID, name, privateKeyBase64)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, string) *db.IPFSIPNSKey); ok {
		r0 = returnFunc(ctx, userID, name, privateKeyBase64)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSIPNSKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, string) error); ok {
		r1 = returnFunc(ctx, userID, name, privateKeyBase64)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSKeyService_ImportKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportKey'
type MockIPNSKeyService_ImportKey_Call struct {
	*mock.Call
}

// ImportKey is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - name string
//   - privateKeyBase64 string
func (_e *MockIPNSKeyService_Expecter) ImportKey(ctx interface{}, userID interface{}, name interface{}, privateKeyBase64 interface{}) *MockIPNSKeyService_ImportKey_Call {
	return &MockIPNSKeyService_ImportKey_Call{Call: _e.mock.On("ImportKey", ctx, userID, name, privateKeyBase64)}
}

func (_c *MockIPNSKeyService_ImportKey_Call) Run(run func(ctx context.Context, userID uint, name string, privateKeyBase64 string)) *MockIPNSKeyService_ImportKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_ImportKey_Call) Return(iPFSIPNSKey *db.IPFSIPNSKey, err error) *MockIPNSKeyService_ImportKey_Call {
	_c.Call.Return(iPFSIPNSKey, err)
	return _c
}

func (_c *MockIPNSKeyService_ImportKey_Call) RunAndReturn(run func(ctx context.Context, userID uint, name string, privateKeyBase64 string) (*db.IPFSIPNSKey, error)) *MockIPNSKeyService_ImportKey_Call {
	_c.Call.Return(run)
	return _c
}

// ListKeys provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) ListKeys(ctx context.Context, userID uint) ([]db.IPFSIPNSKey, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListKeys")
	}

	var r0 []db.IPFSIPNSKey
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) ([]db.IPFSIPNSKey, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) []db.IPFSIPNSKey); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]db.IPFSIPNSKey)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSKeyService_ListKeys_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListKeys'
type MockIPNSKeyService_ListKeys_Call struct {
	*mock.Call
}

// ListKeys is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
func (_e *MockIPNSKeyService_Expecter) ListKeys(ctx interface{}, userID interface{}) *MockIPNSKeyService_ListKeys_Call {
	return &MockIPNSKeyService_ListKeys_Call{Call: _e.mock.On("ListKeys", ctx, userID)}
}

func (_c *MockIPNSKeyService_ListKeys_Call) Run(run func(ctx context.Context, userID uint)) *MockIPNSKeyService_ListKeys_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_ListKeys_Call) Return(iPFSIPNSKeys []db.IPFSIPNSKey, err error) *MockIPNSKeyService_ListKeys_Call {
	_c.Call.Return(iPFSIPNSKeys, err)
	return _c
}

func (_c *MockIPNSKeyService_ListKeys_Call) RunAndReturn(run func(ctx context.Context, userID uint) ([]db.IPFSIPNSKey, error)) *MockIPNSKeyService_ListKeys_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockIPNSKeyService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockIPNSKeyService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockIPNSKeyService_Expecter) Logger() *MockIPNSKeyService_Logger_Call {
	return &MockIPNSKeyService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockIPNSKeyService_Logger_Call) Run(run func()) *MockIPNSKeyService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPNSKeyService_Logger_Call) Return(logger *core.Logger) *MockIPNSKeyService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockIPNSKeyService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockIPNSKeyService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockIPNSKeyService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockIPNSKeyService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockIPNSKeyService_Expecter) SetConfig(cfg interface{}) *MockIPNSKeyService_SetConfig_Call {
	return &MockIPNSKeyService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockIPNSKeyService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockIPNSKeyService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_SetConfig_Call) Return() *MockIPNSKeyService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSKeyService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockIPNSKeyService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockIPNSKeyService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockIPNSKeyService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockIPNSKeyService_Expecter) SetContext(ctx interface{}) *MockIPNSKeyService_SetContext_Call {
	return &MockIPNSKeyService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockIPNSKeyService_SetContext_Call) Run(run func(ctx core.Context)) *MockIPNSKeyService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_SetContext_Call) Return() *MockIPNSKeyService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSKeyService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockIPNSKeyService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockIPNSKeyService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockIPNSKeyService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockIPNSKeyService_Expecter) SetDB(db1 interface{}) *MockIPNSKeyService_SetDB_Call {
	return &MockIPNSKeyService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockIPNSKeyService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockIPNSKeyService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_SetDB_Call) Return() *MockIPNSKeyService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSKeyService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockIPNSKeyService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockIPNSKeyService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockIPNSKeyService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockIPNSKeyService_Expecter) SetLogger(logger interface{}) *MockIPNSKeyService_SetLogger_Call {
	return &MockIPNSKeyService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockIPNSKeyService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockIPNSKeyService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_SetLogger_Call) Return() *MockIPNSKeyService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPNSKeyService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockIPNSKeyService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SyncToBoxoKeystore provides a mock function for the type MockIPNSKeyService
func (_mock *MockIPNSKeyService) SyncToBoxoKeystore(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SyncToBoxoKeystore")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSKeyService_SyncToBoxoKeystore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SyncToBoxoKeystore'
type MockIPNSKeyService_SyncToBoxoKeystore_Call struct {
	*mock.Call
}

// SyncToBoxoKeystore is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPNSKeyService_Expecter) SyncToBoxoKeystore(ctx interface{}) *MockIPNSKeyService_SyncToBoxoKeystore_Call {
	return &MockIPNSKeyService_SyncToBoxoKeystore_Call{Call: _e.mock.On("SyncToBoxoKeystore", ctx)}
}

func (_c *MockIPNSKeyService_SyncToBoxoKeystore_Call) Run(run func(ctx context.Context)) *MockIPNSKeyService_SyncToBoxoKeystore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSKeyService_SyncToBoxoKeystore_Call) Return(err error) *MockIPNSKeyService_SyncToBoxoKeystore_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSKeyService_SyncToBoxoKeystore_Call) RunAndReturn(run func(ctx context.Context) error) *MockIPNSKeyService_SyncToBoxoKeystore_Call {
	_c.Call.Return(run)
	return _c
}
