// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/core"
)

// NewMockReprovideStore creates a new instance of MockReprovideStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReprovideStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReprovideStore {
	mock := &MockReprovideStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReprovideStore is an autogenerated mock type for the ReprovideStore type
type MockReprovideStore struct {
	mock.Mock
}

type MockReprovideStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReprovideStore) EXPECT() *MockReprovideStore_Expecter {
	return &MockReprovideStore_Expecter{mock: &_m.Mock}
}

// ProvideCIDs provides a mock function for the type MockReprovideStore
func (_mock *MockReprovideStore) ProvideCIDs(ctx context.Context, limit int) ([]core.PinnedCID, error) {
	ret := _mock.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for ProvideCIDs")
	}

	var r0 []core.PinnedCID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) ([]core.PinnedCID, error)); ok {
		return returnFunc(ctx, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int) []core.PinnedCID); ok {
		r0 = returnFunc(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.PinnedCID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = returnFunc(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockReprovideStore_ProvideCIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvideCIDs'
type MockReprovideStore_ProvideCIDs_Call struct {
	*mock.Call
}

// ProvideCIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
func (_e *MockReprovideStore_Expecter) ProvideCIDs(ctx interface{}, limit interface{}) *MockReprovideStore_ProvideCIDs_Call {
	return &MockReprovideStore_ProvideCIDs_Call{Call: _e.mock.On("ProvideCIDs", ctx, limit)}
}

func (_c *MockReprovideStore_ProvideCIDs_Call) Run(run func(ctx context.Context, limit int)) *MockReprovideStore_ProvideCIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReprovideStore_ProvideCIDs_Call) Return(pinnedCIDs []core.PinnedCID, err error) *MockReprovideStore_ProvideCIDs_Call {
	_c.Call.Return(pinnedCIDs, err)
	return _c
}

func (_c *MockReprovideStore_ProvideCIDs_Call) RunAndReturn(run func(ctx context.Context, limit int) ([]core.PinnedCID, error)) *MockReprovideStore_ProvideCIDs_Call {
	_c.Call.Return(run)
	return _c
}

// SetLastAnnouncement provides a mock function for the type MockReprovideStore
func (_mock *MockReprovideStore) SetLastAnnouncement(ctx context.Context, cids []cid.Cid, t time.Time) error {
	ret := _mock.Called(ctx, cids, t)

	if len(ret) == 0 {
		panic("no return value specified for SetLastAnnouncement")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid, time.Time) error); ok {
		r0 = returnFunc(ctx, cids, t)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockReprovideStore_SetLastAnnouncement_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLastAnnouncement'
type MockReprovideStore_SetLastAnnouncement_Call struct {
	*mock.Call
}

// SetLastAnnouncement is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []cid.Cid
//   - t time.Time
func (_e *MockReprovideStore_Expecter) SetLastAnnouncement(ctx interface{}, cids interface{}, t interface{}) *MockReprovideStore_SetLastAnnouncement_Call {
	return &MockReprovideStore_SetLastAnnouncement_Call{Call: _e.mock.On("SetLastAnnouncement", ctx, cids, t)}
}

func (_c *MockReprovideStore_SetLastAnnouncement_Call) Run(run func(ctx context.Context, cids []cid.Cid, t time.Time)) *MockReprovideStore_SetLastAnnouncement_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cid.Cid
		if args[1] != nil {
			arg1 = args[1].([]cid.Cid)
		}
		var arg2 time.Time
		if args[2] != nil {
			arg2 = args[2].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReprovideStore_SetLastAnnouncement_Call) Return(err error) *MockReprovideStore_SetLastAnnouncement_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockReprovideStore_SetLastAnnouncement_Call) RunAndReturn(run func(ctx context.Context, cids []cid.Cid, t time.Time) error) *MockReprovideStore_SetLastAnnouncement_Call {
	_c.Call.Return(run)
	return _c
}
