// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-datastore"
	"github.com/ipfs/go-datastore/query"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDatastore creates a new instance of MockDatastore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDatastore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDatastore {
	mock := &MockDatastore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDatastore is an autogenerated mock type for the Datastore type
type MockDatastore struct {
	mock.Mock
}

type MockDatastore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDatastore) EXPECT() *MockDatastore_Expecter {
	return &MockDatastore_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockDatastore_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockDatastore_Expecter) Close() *MockDatastore_Close_Call {
	return &MockDatastore_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockDatastore_Close_Call) Run(run func()) *MockDatastore_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDatastore_Close_Call) Return(err error) *MockDatastore_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_Close_Call) RunAndReturn(run func() error) *MockDatastore_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Delete(ctx context.Context, key datastore.Key) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDatastore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
func (_e *MockDatastore_Expecter) Delete(ctx interface{}, key interface{}) *MockDatastore_Delete_Call {
	return &MockDatastore_Delete_Call{Call: _e.mock.On("Delete", ctx, key)}
}

func (_c *MockDatastore_Delete_Call) Run(run func(ctx context.Context, key datastore.Key)) *MockDatastore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_Delete_Call) Return(err error) *MockDatastore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_Delete_Call) RunAndReturn(run func(ctx context.Context, key datastore.Key) error) *MockDatastore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Get(ctx context.Context, key datastore.Key) ([]byte, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) ([]byte, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) []byte); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, datastore.Key) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockDatastore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
func (_e *MockDatastore_Expecter) Get(ctx interface{}, key interface{}) *MockDatastore_Get_Call {
	return &MockDatastore_Get_Call{Call: _e.mock.On("Get", ctx, key)}
}

func (_c *MockDatastore_Get_Call) Run(run func(ctx context.Context, key datastore.Key)) *MockDatastore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_Get_Call) Return(value []byte, err error) *MockDatastore_Get_Call {
	_c.Call.Return(value, err)
	return _c
}

func (_c *MockDatastore_Get_Call) RunAndReturn(run func(ctx context.Context, key datastore.Key) ([]byte, error)) *MockDatastore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetSize provides a mock function for the type MockDatastore
func (_mock *MockDatastore) GetSize(ctx context.Context, key datastore.Key) (int, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for GetSize")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) (int, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) int); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, datastore.Key) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_GetSize_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSize'
type MockDatastore_GetSize_Call struct {
	*mock.Call
}

// GetSize is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
func (_e *MockDatastore_Expecter) GetSize(ctx interface{}, key interface{}) *MockDatastore_GetSize_Call {
	return &MockDatastore_GetSize_Call{Call: _e.mock.On("GetSize", ctx, key)}
}

func (_c *MockDatastore_GetSize_Call) Run(run func(ctx context.Context, key datastore.Key)) *MockDatastore_GetSize_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_GetSize_Call) Return(size int, err error) *MockDatastore_GetSize_Call {
	_c.Call.Return(size, err)
	return _c
}

func (_c *MockDatastore_GetSize_Call) RunAndReturn(run func(ctx context.Context, key datastore.Key) (int, error)) *MockDatastore_GetSize_Call {
	_c.Call.Return(run)
	return _c
}

// Has provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Has(ctx context.Context, key datastore.Key) (bool, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for Has")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) (bool, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) bool); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, datastore.Key) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_Has_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Has'
type MockDatastore_Has_Call struct {
	*mock.Call
}

// Has is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
func (_e *MockDatastore_Expecter) Has(ctx interface{}, key interface{}) *MockDatastore_Has_Call {
	return &MockDatastore_Has_Call{Call: _e.mock.On("Has", ctx, key)}
}

func (_c *MockDatastore_Has_Call) Run(run func(ctx context.Context, key datastore.Key)) *MockDatastore_Has_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_Has_Call) Return(exists bool, err error) *MockDatastore_Has_Call {
	_c.Call.Return(exists, err)
	return _c
}

func (_c *MockDatastore_Has_Call) RunAndReturn(run func(ctx context.Context, key datastore.Key) (bool, error)) *MockDatastore_Has_Call {
	_c.Call.Return(run)
	return _c
}

// Put provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Put(ctx context.Context, key datastore.Key, value []byte) error {
	ret := _mock.Called(ctx, key, value)

	if len(ret) == 0 {
		panic("no return value specified for Put")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key, []byte) error); ok {
		r0 = returnFunc(ctx, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_Put_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Put'
type MockDatastore_Put_Call struct {
	*mock.Call
}

// Put is a helper method to define mock.On call
//   - ctx context.Context
//   - key datastore.Key
//   - value []byte
func (_e *MockDatastore_Expecter) Put(ctx interface{}, key interface{}, value interface{}) *MockDatastore_Put_Call {
	return &MockDatastore_Put_Call{Call: _e.mock.On("Put", ctx, key, value)}
}

func (_c *MockDatastore_Put_Call) Run(run func(ctx context.Context, key datastore.Key, value []byte)) *MockDatastore_Put_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		var arg2 []byte
		if args[2] != nil {
			arg2 = args[2].([]byte)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDatastore_Put_Call) Return(err error) *MockDatastore_Put_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_Put_Call) RunAndReturn(run func(ctx context.Context, key datastore.Key, value []byte) error) *MockDatastore_Put_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Query(ctx context.Context, q query.Query) (query.Results, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 query.Results
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.Query) (query.Results, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, query.Query) query.Results); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(query.Results)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, query.Query) error); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDatastore_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockDatastore_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - q query.Query
func (_e *MockDatastore_Expecter) Query(ctx interface{}, q interface{}) *MockDatastore_Query_Call {
	return &MockDatastore_Query_Call{Call: _e.mock.On("Query", ctx, q)}
}

func (_c *MockDatastore_Query_Call) Run(run func(ctx context.Context, q query.Query)) *MockDatastore_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 query.Query
		if args[1] != nil {
			arg1 = args[1].(query.Query)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_Query_Call) Return(results query.Results, err error) *MockDatastore_Query_Call {
	_c.Call.Return(results, err)
	return _c
}

func (_c *MockDatastore_Query_Call) RunAndReturn(run func(ctx context.Context, q query.Query) (query.Results, error)) *MockDatastore_Query_Call {
	_c.Call.Return(run)
	return _c
}

// Sync provides a mock function for the type MockDatastore
func (_mock *MockDatastore) Sync(ctx context.Context, prefix datastore.Key) error {
	ret := _mock.Called(ctx, prefix)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, datastore.Key) error); ok {
		r0 = returnFunc(ctx, prefix)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDatastore_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type MockDatastore_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - prefix datastore.Key
func (_e *MockDatastore_Expecter) Sync(ctx interface{}, prefix interface{}) *MockDatastore_Sync_Call {
	return &MockDatastore_Sync_Call{Call: _e.mock.On("Sync", ctx, prefix)}
}

func (_c *MockDatastore_Sync_Call) Run(run func(ctx context.Context, prefix datastore.Key)) *MockDatastore_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 datastore.Key
		if args[1] != nil {
			arg1 = args[1].(datastore.Key)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDatastore_Sync_Call) Return(err error) *MockDatastore_Sync_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDatastore_Sync_Call) RunAndReturn(run func(ctx context.Context, prefix datastore.Key) error) *MockDatastore_Sync_Call {
	_c.Call.Return(run)
	return _c
}
