// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/boxo/ipns"
	"github.com/ipfs/boxo/namesys"
	"github.com/ipfs/boxo/path"
	"github.com/libp2p/go-libp2p/core/crypto"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIPNSPublisher creates a new instance of MockIPNSPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPNSPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPNSPublisher {
	mock := &MockIPNSPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPNSPublisher is an autogenerated mock type for the IPNSPublisher type
type MockIPNSPublisher struct {
	mock.Mock
}

type MockIPNSPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPNSPublisher) EXPECT() *MockIPNSPublisher_Expecter {
	return &MockIPNSPublisher_Expecter{mock: &_m.Mock}
}

// GetPublished provides a mock function for the type MockIPNSPublisher
func (_mock *MockIPNSPublisher) GetPublished(ctx context.Context, name ipns.Name, checkRouting bool) (*ipns.Record, error) {
	ret := _mock.Called(ctx, name, checkRouting)

	if len(ret) == 0 {
		panic("no return value specified for GetPublished")
	}

	var r0 *ipns.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipns.Name, bool) (*ipns.Record, error)); ok {
		return returnFunc(ctx, name, checkRouting)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ipns.Name, bool) *ipns.Record); ok {
		r0 = returnFunc(ctx, name, checkRouting)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipns.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ipns.Name, bool) error); ok {
		r1 = returnFunc(ctx, name, checkRouting)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSPublisher_GetPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublished'
type MockIPNSPublisher_GetPublished_Call struct {
	*mock.Call
}

// GetPublished is a helper method to define mock.On call
//   - ctx context.Context
//   - name ipns.Name
//   - checkRouting bool
func (_e *MockIPNSPublisher_Expecter) GetPublished(ctx interface{}, name interface{}, checkRouting interface{}) *MockIPNSPublisher_GetPublished_Call {
	return &MockIPNSPublisher_GetPublished_Call{Call: _e.mock.On("GetPublished", ctx, name, checkRouting)}
}

func (_c *MockIPNSPublisher_GetPublished_Call) Run(run func(ctx context.Context, name ipns.Name, checkRouting bool)) *MockIPNSPublisher_GetPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 ipns.Name
		if args[1] != nil {
			arg1 = args[1].(ipns.Name)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPNSPublisher_GetPublished_Call) Return(record *ipns.Record, err error) *MockIPNSPublisher_GetPublished_Call {
	_c.Call.Return(record, err)
	return _c
}

func (_c *MockIPNSPublisher_GetPublished_Call) RunAndReturn(run func(ctx context.Context, name ipns.Name, checkRouting bool) (*ipns.Record, error)) *MockIPNSPublisher_GetPublished_Call {
	_c.Call.Return(run)
	return _c
}

// ListPublished provides a mock function for the type MockIPNSPublisher
func (_mock *MockIPNSPublisher) ListPublished(ctx context.Context) (map[ipns.Name]*ipns.Record, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ListPublished")
	}

	var r0 map[ipns.Name]*ipns.Record
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (map[ipns.Name]*ipns.Record, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) map[ipns.Name]*ipns.Record); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[ipns.Name]*ipns.Record)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPNSPublisher_ListPublished_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPublished'
type MockIPNSPublisher_ListPublished_Call struct {
	*mock.Call
}

// ListPublished is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockIPNSPublisher_Expecter) ListPublished(ctx interface{}) *MockIPNSPublisher_ListPublished_Call {
	return &MockIPNSPublisher_ListPublished_Call{Call: _e.mock.On("ListPublished", ctx)}
}

func (_c *MockIPNSPublisher_ListPublished_Call) Run(run func(ctx context.Context)) *MockIPNSPublisher_ListPublished_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPNSPublisher_ListPublished_Call) Return(nameToRecord map[ipns.Name]*ipns.Record, err error) *MockIPNSPublisher_ListPublished_Call {
	_c.Call.Return(nameToRecord, err)
	return _c
}

func (_c *MockIPNSPublisher_ListPublished_Call) RunAndReturn(run func(ctx context.Context) (map[ipns.Name]*ipns.Record, error)) *MockIPNSPublisher_ListPublished_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function for the type MockIPNSPublisher
func (_mock *MockIPNSPublisher) Publish(ctx context.Context, privKey crypto.PrivKey, ipnsPath path.Path, options ...namesys.PublishOption) error {
	// namesys.PublishOption
	_va := make([]interface{}, len(options))
	for _i := range options {
		_va[_i] = options[_i]
	}
	var _ca []interface{}
	_ca = append(_ca, ctx, privKey, ipnsPath)
	_ca = append(_ca, _va...)
	ret := _mock.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, crypto.PrivKey, path.Path, ...namesys.PublishOption) error); ok {
		r0 = returnFunc(ctx, privKey, ipnsPath, options...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPNSPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockIPNSPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - privKey crypto.PrivKey
//   - ipnsPath path.Path
//   - options ...namesys.PublishOption
func (_e *MockIPNSPublisher_Expecter) Publish(ctx interface{}, privKey interface{}, ipnsPath interface{}, options ...interface{}) *MockIPNSPublisher_Publish_Call {
	return &MockIPNSPublisher_Publish_Call{Call: _e.mock.On("Publish",
		append([]interface{}{ctx, privKey, ipnsPath}, options...)...)}
}

func (_c *MockIPNSPublisher_Publish_Call) Run(run func(ctx context.Context, privKey crypto.PrivKey, ipnsPath path.Path, options ...namesys.PublishOption)) *MockIPNSPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 crypto.PrivKey
		if args[1] != nil {
			arg1 = args[1].(crypto.PrivKey)
		}
		var arg2 path.Path
		if args[2] != nil {
			arg2 = args[2].(path.Path)
		}
		var arg3 []namesys.PublishOption
		variadicArgs := make([]namesys.PublishOption, len(args)-3)
		for i, a := range args[3:] {
			if a != nil {
				variadicArgs[i] = a.(namesys.PublishOption)
			}
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockIPNSPublisher_Publish_Call) Return(err error) *MockIPNSPublisher_Publish_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPNSPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, privKey crypto.PrivKey, ipnsPath path.Path, options ...namesys.PublishOption) error) *MockIPNSPublisher_Publish_Call {
	_c.Call.Return(run)
	return _c
}
