// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"encoding/json"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/core"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
)

// NewMockDomainProvider creates a new instance of MockDomainProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDomainProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDomainProvider {
	mock := &MockDomainProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDomainProvider is an autogenerated mock type for the DomainProvider type
type MockDomainProvider struct {
	mock.Mock
}

type MockDomainProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDomainProvider) EXPECT() *MockDomainProvider_Expecter {
	return &MockDomainProvider_Expecter{mock: &_m.Mock}
}

// ApexRecordType provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) ApexRecordType() core.RecordType {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ApexRecordType")
	}

	var r0 core.RecordType
	if returnFunc, ok := ret.Get(0).(func() core.RecordType); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(core.RecordType)
	}
	return r0
}

// MockDomainProvider_ApexRecordType_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApexRecordType'
type MockDomainProvider_ApexRecordType_Call struct {
	*mock.Call
}

// ApexRecordType is a helper method to define mock.On call
func (_e *MockDomainProvider_Expecter) ApexRecordType() *MockDomainProvider_ApexRecordType_Call {
	return &MockDomainProvider_ApexRecordType_Call{Call: _e.mock.On("ApexRecordType")}
}

func (_c *MockDomainProvider_ApexRecordType_Call) Run(run func()) *MockDomainProvider_ApexRecordType_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDomainProvider_ApexRecordType_Call) Return(recordType core.RecordType) *MockDomainProvider_ApexRecordType_Call {
	_c.Call.Return(recordType)
	return _c
}

func (_c *MockDomainProvider_ApexRecordType_Call) RunAndReturn(run func() core.RecordType) *MockDomainProvider_ApexRecordType_Call {
	_c.Call.Return(run)
	return _c
}

// BuildDelegation provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) BuildDelegation(ctx context.Context, zoneID uint, domain string, website *db.Website, config json.RawMessage) (json.RawMessage, error) {
	ret := _mock.Called(ctx, zoneID, domain, website, config)

	if len(ret) == 0 {
		panic("no return value specified for BuildDelegation")
	}

	var r0 json.RawMessage
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, *db.Website, json.RawMessage) (json.RawMessage, error)); ok {
		return returnFunc(ctx, zoneID, domain, website, config)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, *db.Website, json.RawMessage) json.RawMessage); ok {
		r0 = returnFunc(ctx, zoneID, domain, website, config)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(json.RawMessage)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, *db.Website, json.RawMessage) error); ok {
		r1 = returnFunc(ctx, zoneID, domain, website, config)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainProvider_BuildDelegation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildDelegation'
type MockDomainProvider_BuildDelegation_Call struct {
	*mock.Call
}

// BuildDelegation is a helper method to define mock.On call
//   - ctx context.Context
//   - zoneID uint
//   - domain string
//   - website *db.Website
//   - config json.RawMessage
func (_e *MockDomainProvider_Expecter) BuildDelegation(ctx any, zoneID any, domain any, website any, config any) *MockDomainProvider_BuildDelegation_Call {
	return &MockDomainProvider_BuildDelegation_Call{Call: _e.mock.On("BuildDelegation", ctx, zoneID, domain, website, config)}
}

func (_c *MockDomainProvider_BuildDelegation_Call) Run(run func(ctx context.Context, zoneID uint, domain string, website *db.Website, config json.RawMessage)) *MockDomainProvider_BuildDelegation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 *db.Website
		if args[3] != nil {
			arg3 = args[3].(*db.Website)
		}
		var arg4 json.RawMessage
		if args[4] != nil {
			arg4 = args[4].(json.RawMessage)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockDomainProvider_BuildDelegation_Call) Return(delegation json.RawMessage, err error) *MockDomainProvider_BuildDelegation_Call {
	_c.Call.Return(delegation, err)
	return _c
}

func (_c *MockDomainProvider_BuildDelegation_Call) RunAndReturn(run func(ctx context.Context, zoneID uint, domain string, website *db.Website, config json.RawMessage) (json.RawMessage, error)) *MockDomainProvider_BuildDelegation_Call {
	_c.Call.Return(run)
	return _c
}

// Inspect provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) Inspect(ctx context.Context, domain string) (bool, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for Inspect")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainProvider_Inspect_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Inspect'
type MockDomainProvider_Inspect_Call struct {
	*mock.Call
}

// Inspect is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockDomainProvider_Expecter) Inspect(ctx any, domain any) *MockDomainProvider_Inspect_Call {
	return &MockDomainProvider_Inspect_Call{Call: _e.mock.On("Inspect", ctx, domain)}
}

func (_c *MockDomainProvider_Inspect_Call) Run(run func(ctx context.Context, domain string)) *MockDomainProvider_Inspect_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDomainProvider_Inspect_Call) Return(onchainManaged bool, err error) *MockDomainProvider_Inspect_Call {
	_c.Call.Return(onchainManaged, err)
	return _c
}

func (_c *MockDomainProvider_Inspect_Call) RunAndReturn(run func(ctx context.Context, domain string) (bool, error)) *MockDomainProvider_Inspect_Call {
	_c.Call.Return(run)
	return _c
}

// LiveNameservers provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) LiveNameservers(ctx context.Context, domain string) ([]string, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for LiveNameservers")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]string, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []string); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainProvider_LiveNameservers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LiveNameservers'
type MockDomainProvider_LiveNameservers_Call struct {
	*mock.Call
}

// LiveNameservers is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockDomainProvider_Expecter) LiveNameservers(ctx any, domain any) *MockDomainProvider_LiveNameservers_Call {
	return &MockDomainProvider_LiveNameservers_Call{Call: _e.mock.On("LiveNameservers", ctx, domain)}
}

func (_c *MockDomainProvider_LiveNameservers_Call) Run(run func(ctx context.Context, domain string)) *MockDomainProvider_LiveNameservers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDomainProvider_LiveNameservers_Call) Return(strings []string, err error) *MockDomainProvider_LiveNameservers_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockDomainProvider_LiveNameservers_Call) RunAndReturn(run func(ctx context.Context, domain string) ([]string, error)) *MockDomainProvider_LiveNameservers_Call {
	_c.Call.Return(run)
	return _c
}

// Nameservers provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) Nameservers() []string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Nameservers")
	}

	var r0 []string
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	return r0
}

// MockDomainProvider_Nameservers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Nameservers'
type MockDomainProvider_Nameservers_Call struct {
	*mock.Call
}

// Nameservers is a helper method to define mock.On call
func (_e *MockDomainProvider_Expecter) Nameservers() *MockDomainProvider_Nameservers_Call {
	return &MockDomainProvider_Nameservers_Call{Call: _e.mock.On("Nameservers")}
}

func (_c *MockDomainProvider_Nameservers_Call) Run(run func()) *MockDomainProvider_Nameservers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDomainProvider_Nameservers_Call) Return(strings []string) *MockDomainProvider_Nameservers_Call {
	_c.Call.Return(strings)
	return _c
}

func (_c *MockDomainProvider_Nameservers_Call) RunAndReturn(run func() []string) *MockDomainProvider_Nameservers_Call {
	_c.Call.Return(run)
	return _c
}

// Policy provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) Policy() core.ProviderPolicy {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Policy")
	}

	var r0 core.ProviderPolicy
	if returnFunc, ok := ret.Get(0).(func() core.ProviderPolicy); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(core.ProviderPolicy)
	}
	return r0
}

// MockDomainProvider_Policy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Policy'
type MockDomainProvider_Policy_Call struct {
	*mock.Call
}

// Policy is a helper method to define mock.On call
func (_e *MockDomainProvider_Expecter) Policy() *MockDomainProvider_Policy_Call {
	return &MockDomainProvider_Policy_Call{Call: _e.mock.On("Policy")}
}

func (_c *MockDomainProvider_Policy_Call) Run(run func()) *MockDomainProvider_Policy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDomainProvider_Policy_Call) Return(policy core.ProviderPolicy) *MockDomainProvider_Policy_Call {
	_c.Call.Return(policy)
	return _c
}

func (_c *MockDomainProvider_Policy_Call) RunAndReturn(run func() core.ProviderPolicy) *MockDomainProvider_Policy_Call {
	_c.Call.Return(run)
	return _c
}

// Protocol provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) Protocol() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Protocol")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockDomainProvider_Protocol_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Protocol'
type MockDomainProvider_Protocol_Call struct {
	*mock.Call
}

// Protocol is a helper method to define mock.On call
func (_e *MockDomainProvider_Expecter) Protocol() *MockDomainProvider_Protocol_Call {
	return &MockDomainProvider_Protocol_Call{Call: _e.mock.On("Protocol")}
}

func (_c *MockDomainProvider_Protocol_Call) Run(run func()) *MockDomainProvider_Protocol_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDomainProvider_Protocol_Call) Return(s string) *MockDomainProvider_Protocol_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockDomainProvider_Protocol_Call) RunAndReturn(run func() string) *MockDomainProvider_Protocol_Call {
	_c.Call.Return(run)
	return _c
}

// RequiresDNSSEC provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) RequiresDNSSEC() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RequiresDNSSEC")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDomainProvider_RequiresDNSSEC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RequiresDNSSEC'
type MockDomainProvider_RequiresDNSSEC_Call struct {
	*mock.Call
}

// RequiresDNSSEC is a helper method to define mock.On call
func (_e *MockDomainProvider_Expecter) RequiresDNSSEC() *MockDomainProvider_RequiresDNSSEC_Call {
	return &MockDomainProvider_RequiresDNSSEC_Call{Call: _e.mock.On("RequiresDNSSEC")}
}

func (_c *MockDomainProvider_RequiresDNSSEC_Call) Run(run func()) *MockDomainProvider_RequiresDNSSEC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDomainProvider_RequiresDNSSEC_Call) Return(b bool) *MockDomainProvider_RequiresDNSSEC_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDomainProvider_RequiresDNSSEC_Call) RunAndReturn(run func() bool) *MockDomainProvider_RequiresDNSSEC_Call {
	_c.Call.Return(run)
	return _c
}

// UsesManagedZoneTLSA provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) UsesManagedZoneTLSA() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UsesManagedZoneTLSA")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockDomainProvider_UsesManagedZoneTLSA_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UsesManagedZoneTLSA'
type MockDomainProvider_UsesManagedZoneTLSA_Call struct {
	*mock.Call
}

// UsesManagedZoneTLSA is a helper method to define mock.On call
func (_e *MockDomainProvider_Expecter) UsesManagedZoneTLSA() *MockDomainProvider_UsesManagedZoneTLSA_Call {
	return &MockDomainProvider_UsesManagedZoneTLSA_Call{Call: _e.mock.On("UsesManagedZoneTLSA")}
}

func (_c *MockDomainProvider_UsesManagedZoneTLSA_Call) Run(run func()) *MockDomainProvider_UsesManagedZoneTLSA_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDomainProvider_UsesManagedZoneTLSA_Call) Return(b bool) *MockDomainProvider_UsesManagedZoneTLSA_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockDomainProvider_UsesManagedZoneTLSA_Call) RunAndReturn(run func() bool) *MockDomainProvider_UsesManagedZoneTLSA_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) Validate(domain string) error {
	ret := _mock.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(domain)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDomainProvider_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockDomainProvider_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - domain string
func (_e *MockDomainProvider_Expecter) Validate(domain any) *MockDomainProvider_Validate_Call {
	return &MockDomainProvider_Validate_Call{Call: _e.mock.On("Validate", domain)}
}

func (_c *MockDomainProvider_Validate_Call) Run(run func(domain string)) *MockDomainProvider_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDomainProvider_Validate_Call) Return(err error) *MockDomainProvider_Validate_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDomainProvider_Validate_Call) RunAndReturn(run func(domain string) error) *MockDomainProvider_Validate_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyDelegation provides a mock function for the type MockDomainProvider
func (_mock *MockDomainProvider) VerifyDelegation(ctx context.Context, domain string, expectedDS string) (bool, error) {
	ret := _mock.Called(ctx, domain, expectedDS)

	if len(ret) == 0 {
		panic("no return value specified for VerifyDelegation")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (bool, error)); ok {
		return returnFunc(ctx, domain, expectedDS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) bool); ok {
		r0 = returnFunc(ctx, domain, expectedDS)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, domain, expectedDS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDomainProvider_VerifyDelegation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyDelegation'
type MockDomainProvider_VerifyDelegation_Call struct {
	*mock.Call
}

// VerifyDelegation is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - expectedDS string
func (_e *MockDomainProvider_Expecter) VerifyDelegation(ctx any, domain any, expectedDS any) *MockDomainProvider_VerifyDelegation_Call {
	return &MockDomainProvider_VerifyDelegation_Call{Call: _e.mock.On("VerifyDelegation", ctx, domain, expectedDS)}
}

func (_c *MockDomainProvider_VerifyDelegation_Call) Run(run func(ctx context.Context, domain string, expectedDS string)) *MockDomainProvider_VerifyDelegation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDomainProvider_VerifyDelegation_Call) Return(b bool, err error) *MockDomainProvider_VerifyDelegation_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockDomainProvider_VerifyDelegation_Call) RunAndReturn(run func(ctx context.Context, domain string, expectedDS string) (bool, error)) *MockDomainProvider_VerifyDelegation_Call {
	_c.Call.Return(run)
	return _c
}
