// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
	core0 "go.lumeweb.com/portal-plugin-ipfs/core"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/queryutil"
	"go.lumeweb.com/queryutil/filter"
	"gorm.io/gorm"
)

// NewMockWebsiteService creates a new instance of MockWebsiteService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockWebsiteService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockWebsiteService {
	mock := &MockWebsiteService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockWebsiteService is an autogenerated mock type for the WebsiteService type
type MockWebsiteService struct {
	mock.Mock
}

type MockWebsiteService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockWebsiteService) EXPECT() *MockWebsiteService_Expecter {
	return &MockWebsiteService_Expecter{mock: &_m.Mock}
}

// ActivatePlatformSubdomainWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) ActivatePlatformSubdomainWebsite(ctx context.Context, websiteID uint) error {
	ret := _mock.Called(ctx, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for ActivatePlatformSubdomainWebsite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, websiteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsiteService_ActivatePlatformSubdomainWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActivatePlatformSubdomainWebsite'
type MockWebsiteService_ActivatePlatformSubdomainWebsite_Call struct {
	*mock.Call
}

// ActivatePlatformSubdomainWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) ActivatePlatformSubdomainWebsite(ctx any, websiteID any) *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call {
	return &MockWebsiteService_ActivatePlatformSubdomainWebsite_Call{Call: _e.mock.On("ActivatePlatformSubdomainWebsite", ctx, websiteID)}
}

func (_c *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call) Run(run func(ctx context.Context, websiteID uint)) *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call) Return(err error) *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call) RunAndReturn(run func(ctx context.Context, websiteID uint) error) *MockWebsiteService_ActivatePlatformSubdomainWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// BlockWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) BlockWebsite(ctx context.Context, websiteID uint) error {
	ret := _mock.Called(ctx, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for BlockWebsite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, websiteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsiteService_BlockWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockWebsite'
type MockWebsiteService_BlockWebsite_Call struct {
	*mock.Call
}

// BlockWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) BlockWebsite(ctx any, websiteID any) *MockWebsiteService_BlockWebsite_Call {
	return &MockWebsiteService_BlockWebsite_Call{Call: _e.mock.On("BlockWebsite", ctx, websiteID)}
}

func (_c *MockWebsiteService_BlockWebsite_Call) Run(run func(ctx context.Context, websiteID uint)) *MockWebsiteService_BlockWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_BlockWebsite_Call) Return(err error) *MockWebsiteService_BlockWebsite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsiteService_BlockWebsite_Call) RunAndReturn(run func(ctx context.Context, websiteID uint) error) *MockWebsiteService_BlockWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// CheckStatus provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) CheckStatus(ctx context.Context, website *db.Website) (db.WebsiteStatus, error) {
	ret := _mock.Called(ctx, website)

	if len(ret) == 0 {
		panic("no return value specified for CheckStatus")
	}

	var r0 db.WebsiteStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Website) (db.WebsiteStatus, error)); ok {
		return returnFunc(ctx, website)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Website) db.WebsiteStatus); ok {
		r0 = returnFunc(ctx, website)
	} else {
		r0 = ret.Get(0).(db.WebsiteStatus)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *db.Website) error); ok {
		r1 = returnFunc(ctx, website)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_CheckStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CheckStatus'
type MockWebsiteService_CheckStatus_Call struct {
	*mock.Call
}

// CheckStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - website *db.Website
func (_e *MockWebsiteService_Expecter) CheckStatus(ctx any, website any) *MockWebsiteService_CheckStatus_Call {
	return &MockWebsiteService_CheckStatus_Call{Call: _e.mock.On("CheckStatus", ctx, website)}
}

func (_c *MockWebsiteService_CheckStatus_Call) Run(run func(ctx context.Context, website *db.Website)) *MockWebsiteService_CheckStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.Website
		if args[1] != nil {
			arg1 = args[1].(*db.Website)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_CheckStatus_Call) Return(websiteStatus db.WebsiteStatus, err error) *MockWebsiteService_CheckStatus_Call {
	_c.Call.Return(websiteStatus, err)
	return _c
}

func (_c *MockWebsiteService_CheckStatus_Call) RunAndReturn(run func(ctx context.Context, website *db.Website) (db.WebsiteStatus, error)) *MockWebsiteService_CheckStatus_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockWebsiteService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockWebsiteService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) Config() *MockWebsiteService_Config_Call {
	return &MockWebsiteService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockWebsiteService_Config_Call) Run(run func()) *MockWebsiteService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_Config_Call) Return(manager config.Manager) *MockWebsiteService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockWebsiteService_Config_Call) RunAndReturn(run func() config.Manager) *MockWebsiteService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockWebsiteService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockWebsiteService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) Context() *MockWebsiteService_Context_Call {
	return &MockWebsiteService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockWebsiteService_Context_Call) Run(run func()) *MockWebsiteService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_Context_Call) Return(context1 core.Context) *MockWebsiteService_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockWebsiteService_Context_Call) RunAndReturn(run func() core.Context) *MockWebsiteService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) CreateWebsite(ctx context.Context, website *db.Website) (*db.Website, error) {
	ret := _mock.Called(ctx, website)

	if len(ret) == 0 {
		panic("no return value specified for CreateWebsite")
	}

	var r0 *db.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Website) (*db.Website, error)); ok {
		return returnFunc(ctx, website)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.Website) *db.Website); ok {
		r0 = returnFunc(ctx, website)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *db.Website) error); ok {
		r1 = returnFunc(ctx, website)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_CreateWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWebsite'
type MockWebsiteService_CreateWebsite_Call struct {
	*mock.Call
}

// CreateWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - website *db.Website
func (_e *MockWebsiteService_Expecter) CreateWebsite(ctx any, website any) *MockWebsiteService_CreateWebsite_Call {
	return &MockWebsiteService_CreateWebsite_Call{Call: _e.mock.On("CreateWebsite", ctx, website)}
}

func (_c *MockWebsiteService_CreateWebsite_Call) Run(run func(ctx context.Context, website *db.Website)) *MockWebsiteService_CreateWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.Website
		if args[1] != nil {
			arg1 = args[1].(*db.Website)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_CreateWebsite_Call) Return(website1 *db.Website, err error) *MockWebsiteService_CreateWebsite_Call {
	_c.Call.Return(website1, err)
	return _c
}

func (_c *MockWebsiteService_CreateWebsite_Call) RunAndReturn(run func(ctx context.Context, website *db.Website) (*db.Website, error)) *MockWebsiteService_CreateWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockWebsiteService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockWebsiteService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) DB() *MockWebsiteService_DB_Call {
	return &MockWebsiteService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockWebsiteService_DB_Call) Run(run func()) *MockWebsiteService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_DB_Call) Return(dB *gorm.DB) *MockWebsiteService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockWebsiteService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockWebsiteService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) DeleteWebsite(ctx context.Context, userID uint, websiteID uint) error {
	ret := _mock.Called(ctx, userID, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteWebsite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) error); ok {
		r0 = returnFunc(ctx, userID, websiteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsiteService_DeleteWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteWebsite'
type MockWebsiteService_DeleteWebsite_Call struct {
	*mock.Call
}

// DeleteWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) DeleteWebsite(ctx any, userID any, websiteID any) *MockWebsiteService_DeleteWebsite_Call {
	return &MockWebsiteService_DeleteWebsite_Call{Call: _e.mock.On("DeleteWebsite", ctx, userID, websiteID)}
}

func (_c *MockWebsiteService_DeleteWebsite_Call) Run(run func(ctx context.Context, userID uint, websiteID uint)) *MockWebsiteService_DeleteWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsiteService_DeleteWebsite_Call) Return(err error) *MockWebsiteService_DeleteWebsite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsiteService_DeleteWebsite_Call) RunAndReturn(run func(ctx context.Context, userID uint, websiteID uint) error) *MockWebsiteService_DeleteWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// GetApexDomainBinding provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) GetApexDomainBinding(ctx context.Context, websiteID uint) (*db.WebsiteDomain, error) {
	ret := _mock.Called(ctx, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for GetApexDomainBinding")
	}

	var r0 *db.WebsiteDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) (*db.WebsiteDomain, error)); ok {
		return returnFunc(ctx, websiteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) *db.WebsiteDomain); ok {
		r0 = returnFunc(ctx, websiteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.WebsiteDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = returnFunc(ctx, websiteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_GetApexDomainBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetApexDomainBinding'
type MockWebsiteService_GetApexDomainBinding_Call struct {
	*mock.Call
}

// GetApexDomainBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) GetApexDomainBinding(ctx any, websiteID any) *MockWebsiteService_GetApexDomainBinding_Call {
	return &MockWebsiteService_GetApexDomainBinding_Call{Call: _e.mock.On("GetApexDomainBinding", ctx, websiteID)}
}

func (_c *MockWebsiteService_GetApexDomainBinding_Call) Run(run func(ctx context.Context, websiteID uint)) *MockWebsiteService_GetApexDomainBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_GetApexDomainBinding_Call) Return(websiteDomain *db.WebsiteDomain, err error) *MockWebsiteService_GetApexDomainBinding_Call {
	_c.Call.Return(websiteDomain, err)
	return _c
}

func (_c *MockWebsiteService_GetApexDomainBinding_Call) RunAndReturn(run func(ctx context.Context, websiteID uint) (*db.WebsiteDomain, error)) *MockWebsiteService_GetApexDomainBinding_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) GetConfig() (any, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (any, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() any); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockWebsiteService_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) GetConfig() *MockWebsiteService_GetConfig_Call {
	return &MockWebsiteService_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockWebsiteService_GetConfig_Call) Run(run func()) *MockWebsiteService_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_GetConfig_Call) Return(v any, err error) *MockWebsiteService_GetConfig_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockWebsiteService_GetConfig_Call) RunAndReturn(run func() (any, error)) *MockWebsiteService_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) GetWebsite(ctx context.Context, userID uint, websiteID uint) (*db.Website, error) {
	ret := _mock.Called(ctx, userID, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for GetWebsite")
	}

	var r0 *db.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (*db.Website, error)); ok {
		return returnFunc(ctx, userID, websiteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) *db.Website); ok {
		r0 = returnFunc(ctx, userID, websiteID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, websiteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_GetWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebsite'
type MockWebsiteService_GetWebsite_Call struct {
	*mock.Call
}

// GetWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) GetWebsite(ctx any, userID any, websiteID any) *MockWebsiteService_GetWebsite_Call {
	return &MockWebsiteService_GetWebsite_Call{Call: _e.mock.On("GetWebsite", ctx, userID, websiteID)}
}

func (_c *MockWebsiteService_GetWebsite_Call) Run(run func(ctx context.Context, userID uint, websiteID uint)) *MockWebsiteService_GetWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsiteService_GetWebsite_Call) Return(website *db.Website, err error) *MockWebsiteService_GetWebsite_Call {
	_c.Call.Return(website, err)
	return _c
}

func (_c *MockWebsiteService_GetWebsite_Call) RunAndReturn(run func(ctx context.Context, userID uint, websiteID uint) (*db.Website, error)) *MockWebsiteService_GetWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// GetWebsiteByDomain provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) GetWebsiteByDomain(ctx context.Context, domain string) (*db.Website, db.DomainNamespace, error) {
	ret := _mock.Called(ctx, domain)

	if len(ret) == 0 {
		panic("no return value specified for GetWebsiteByDomain")
	}

	var r0 *db.Website
	var r1 db.DomainNamespace
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*db.Website, db.DomainNamespace, error)); ok {
		return returnFunc(ctx, domain)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *db.Website); ok {
		r0 = returnFunc(ctx, domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) db.DomainNamespace); ok {
		r1 = returnFunc(ctx, domain)
	} else {
		r1 = ret.Get(1).(db.DomainNamespace)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, domain)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWebsiteService_GetWebsiteByDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetWebsiteByDomain'
type MockWebsiteService_GetWebsiteByDomain_Call struct {
	*mock.Call
}

// GetWebsiteByDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
func (_e *MockWebsiteService_Expecter) GetWebsiteByDomain(ctx any, domain any) *MockWebsiteService_GetWebsiteByDomain_Call {
	return &MockWebsiteService_GetWebsiteByDomain_Call{Call: _e.mock.On("GetWebsiteByDomain", ctx, domain)}
}

func (_c *MockWebsiteService_GetWebsiteByDomain_Call) Run(run func(ctx context.Context, domain string)) *MockWebsiteService_GetWebsiteByDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_GetWebsiteByDomain_Call) Return(website *db.Website, domainNamespace db.DomainNamespace, err error) *MockWebsiteService_GetWebsiteByDomain_Call {
	_c.Call.Return(website, domainNamespace, err)
	return _c
}

func (_c *MockWebsiteService_GetWebsiteByDomain_Call) RunAndReturn(run func(ctx context.Context, domain string) (*db.Website, db.DomainNamespace, error)) *MockWebsiteService_GetWebsiteByDomain_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockWebsiteService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockWebsiteService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) ID() *MockWebsiteService_ID_Call {
	return &MockWebsiteService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockWebsiteService_ID_Call) Run(run func()) *MockWebsiteService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_ID_Call) Return(s string) *MockWebsiteService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockWebsiteService_ID_Call) RunAndReturn(run func() string) *MockWebsiteService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListWebsites provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) ListWebsites(ctx context.Context, userID uint, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.Website, int64, error) {
	ret := _mock.Called(ctx, userID, filter1, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListWebsites")
	}

	var r0 []*db.Website
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) ([]*db.Website, int64, error)); ok {
		return returnFunc(ctx, userID, filter1, sort, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) []*db.Website); ok {
		r0 = returnFunc(ctx, userID, filter1, sort, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filter1, sort, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filter1, sort, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockWebsiteService_ListWebsites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListWebsites'
type MockWebsiteService_ListWebsites_Call struct {
	*mock.Call
}

// ListWebsites is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filter1 []queryutil.CrudFilter
//   - sort []filter.Sort
//   - pagination queryutil.Pagination
func (_e *MockWebsiteService_Expecter) ListWebsites(ctx any, userID any, filter1 any, sort any, pagination any) *MockWebsiteService_ListWebsites_Call {
	return &MockWebsiteService_ListWebsites_Call{Call: _e.mock.On("ListWebsites", ctx, userID, filter1, sort, pagination)}
}

func (_c *MockWebsiteService_ListWebsites_Call) Run(run func(ctx context.Context, userID uint, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination)) *MockWebsiteService_ListWebsites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []filter.Sort
		if args[3] != nil {
			arg3 = args[3].([]filter.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWebsiteService_ListWebsites_Call) Return(websites []*db.Website, n int64, err error) *MockWebsiteService_ListWebsites_Call {
	_c.Call.Return(websites, n, err)
	return _c
}

func (_c *MockWebsiteService_ListWebsites_Call) RunAndReturn(run func(ctx context.Context, userID uint, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.Website, int64, error)) *MockWebsiteService_ListWebsites_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockWebsiteService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockWebsiteService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) Logger() *MockWebsiteService_Logger_Call {
	return &MockWebsiteService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockWebsiteService_Logger_Call) Run(run func()) *MockWebsiteService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_Logger_Call) Return(logger *core.Logger) *MockWebsiteService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockWebsiteService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockWebsiteService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// NotifyAdminWebsiteCreated provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) NotifyAdminWebsiteCreated(ctx context.Context, websiteID uint) error {
	ret := _mock.Called(ctx, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for NotifyAdminWebsiteCreated")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, websiteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsiteService_NotifyAdminWebsiteCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NotifyAdminWebsiteCreated'
type MockWebsiteService_NotifyAdminWebsiteCreated_Call struct {
	*mock.Call
}

// NotifyAdminWebsiteCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) NotifyAdminWebsiteCreated(ctx any, websiteID any) *MockWebsiteService_NotifyAdminWebsiteCreated_Call {
	return &MockWebsiteService_NotifyAdminWebsiteCreated_Call{Call: _e.mock.On("NotifyAdminWebsiteCreated", ctx, websiteID)}
}

func (_c *MockWebsiteService_NotifyAdminWebsiteCreated_Call) Run(run func(ctx context.Context, websiteID uint)) *MockWebsiteService_NotifyAdminWebsiteCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_NotifyAdminWebsiteCreated_Call) Return(err error) *MockWebsiteService_NotifyAdminWebsiteCreated_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsiteService_NotifyAdminWebsiteCreated_Call) RunAndReturn(run func(ctx context.Context, websiteID uint) error) *MockWebsiteService_NotifyAdminWebsiteCreated_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockWebsiteService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockWebsiteService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockWebsiteService_Expecter) SetConfig(cfg any) *MockWebsiteService_SetConfig_Call {
	return &MockWebsiteService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockWebsiteService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockWebsiteService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsiteService_SetConfig_Call) Return() *MockWebsiteService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsiteService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockWebsiteService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockWebsiteService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockWebsiteService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockWebsiteService_Expecter) SetContext(ctx any) *MockWebsiteService_SetContext_Call {
	return &MockWebsiteService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockWebsiteService_SetContext_Call) Run(run func(ctx core.Context)) *MockWebsiteService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsiteService_SetContext_Call) Return() *MockWebsiteService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsiteService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockWebsiteService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockWebsiteService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockWebsiteService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockWebsiteService_Expecter) SetDB(db1 any) *MockWebsiteService_SetDB_Call {
	return &MockWebsiteService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockWebsiteService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockWebsiteService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsiteService_SetDB_Call) Return() *MockWebsiteService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsiteService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockWebsiteService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetDomainDNSEnabled provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) SetDomainDNSEnabled(ctx context.Context, userID uint, websiteID uint, domainID uint, enabled bool) (*db.WebsiteDomain, error) {
	ret := _mock.Called(ctx, userID, websiteID, domainID, enabled)

	if len(ret) == 0 {
		panic("no return value specified for SetDomainDNSEnabled")
	}

	var r0 *db.WebsiteDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint, bool) (*db.WebsiteDomain, error)); ok {
		return returnFunc(ctx, userID, websiteID, domainID, enabled)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint, bool) *db.WebsiteDomain); ok {
		r0 = returnFunc(ctx, userID, websiteID, domainID, enabled)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.WebsiteDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, uint, bool) error); ok {
		r1 = returnFunc(ctx, userID, websiteID, domainID, enabled)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_SetDomainDNSEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDomainDNSEnabled'
type MockWebsiteService_SetDomainDNSEnabled_Call struct {
	*mock.Call
}

// SetDomainDNSEnabled is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - websiteID uint
//   - domainID uint
//   - enabled bool
func (_e *MockWebsiteService_Expecter) SetDomainDNSEnabled(ctx any, userID any, websiteID any, domainID any, enabled any) *MockWebsiteService_SetDomainDNSEnabled_Call {
	return &MockWebsiteService_SetDomainDNSEnabled_Call{Call: _e.mock.On("SetDomainDNSEnabled", ctx, userID, websiteID, domainID, enabled)}
}

func (_c *MockWebsiteService_SetDomainDNSEnabled_Call) Run(run func(ctx context.Context, userID uint, websiteID uint, domainID uint, enabled bool)) *MockWebsiteService_SetDomainDNSEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		var arg4 bool
		if args[4] != nil {
			arg4 = args[4].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWebsiteService_SetDomainDNSEnabled_Call) Return(websiteDomain *db.WebsiteDomain, err error) *MockWebsiteService_SetDomainDNSEnabled_Call {
	_c.Call.Return(websiteDomain, err)
	return _c
}

func (_c *MockWebsiteService_SetDomainDNSEnabled_Call) RunAndReturn(run func(ctx context.Context, userID uint, websiteID uint, domainID uint, enabled bool) (*db.WebsiteDomain, error)) *MockWebsiteService_SetDomainDNSEnabled_Call {
	_c.Call.Return(run)
	return _c
}

// SetLogger provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockWebsiteService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockWebsiteService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockWebsiteService_Expecter) SetLogger(logger any) *MockWebsiteService_SetLogger_Call {
	return &MockWebsiteService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockWebsiteService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockWebsiteService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockWebsiteService_SetLogger_Call) Return() *MockWebsiteService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsiteService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockWebsiteService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// SetPrimaryDomain provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) SetPrimaryDomain(ctx context.Context, userID uint, websiteID uint, domainID uint) (*db.WebsiteDomain, error) {
	ret := _mock.Called(ctx, userID, websiteID, domainID)

	if len(ret) == 0 {
		panic("no return value specified for SetPrimaryDomain")
	}

	var r0 *db.WebsiteDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) (*db.WebsiteDomain, error)); ok {
		return returnFunc(ctx, userID, websiteID, domainID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, uint) *db.WebsiteDomain); ok {
		r0 = returnFunc(ctx, userID, websiteID, domainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.WebsiteDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, websiteID, domainID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_SetPrimaryDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetPrimaryDomain'
type MockWebsiteService_SetPrimaryDomain_Call struct {
	*mock.Call
}

// SetPrimaryDomain is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - websiteID uint
//   - domainID uint
func (_e *MockWebsiteService_Expecter) SetPrimaryDomain(ctx any, userID any, websiteID any, domainID any) *MockWebsiteService_SetPrimaryDomain_Call {
	return &MockWebsiteService_SetPrimaryDomain_Call{Call: _e.mock.On("SetPrimaryDomain", ctx, userID, websiteID, domainID)}
}

func (_c *MockWebsiteService_SetPrimaryDomain_Call) Run(run func(ctx context.Context, userID uint, websiteID uint, domainID uint)) *MockWebsiteService_SetPrimaryDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 uint
		if args[3] != nil {
			arg3 = args[3].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebsiteService_SetPrimaryDomain_Call) Return(websiteDomain *db.WebsiteDomain, err error) *MockWebsiteService_SetPrimaryDomain_Call {
	_c.Call.Return(websiteDomain, err)
	return _c
}

func (_c *MockWebsiteService_SetPrimaryDomain_Call) RunAndReturn(run func(ctx context.Context, userID uint, websiteID uint, domainID uint) (*db.WebsiteDomain, error)) *MockWebsiteService_SetPrimaryDomain_Call {
	_c.Call.Return(run)
	return _c
}

// UnblockWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) UnblockWebsite(ctx context.Context, websiteID uint) error {
	ret := _mock.Called(ctx, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for UnblockWebsite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = returnFunc(ctx, websiteID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockWebsiteService_UnblockWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnblockWebsite'
type MockWebsiteService_UnblockWebsite_Call struct {
	*mock.Call
}

// UnblockWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) UnblockWebsite(ctx any, websiteID any) *MockWebsiteService_UnblockWebsite_Call {
	return &MockWebsiteService_UnblockWebsite_Call{Call: _e.mock.On("UnblockWebsite", ctx, websiteID)}
}

func (_c *MockWebsiteService_UnblockWebsite_Call) Run(run func(ctx context.Context, websiteID uint)) *MockWebsiteService_UnblockWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockWebsiteService_UnblockWebsite_Call) Return(err error) *MockWebsiteService_UnblockWebsite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockWebsiteService_UnblockWebsite_Call) RunAndReturn(run func(ctx context.Context, websiteID uint) error) *MockWebsiteService_UnblockWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSSLStatus provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) UpdateSSLStatus(ctx context.Context, domain string, status db.SSLStatus, sslError string, timestamp *time.Time) (*db.WebsiteDomain, error) {
	ret := _mock.Called(ctx, domain, status, sslError, timestamp)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSSLStatus")
	}

	var r0 *db.WebsiteDomain
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.SSLStatus, string, *time.Time) (*db.WebsiteDomain, error)); ok {
		return returnFunc(ctx, domain, status, sslError, timestamp)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, db.SSLStatus, string, *time.Time) *db.WebsiteDomain); ok {
		r0 = returnFunc(ctx, domain, status, sslError, timestamp)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.WebsiteDomain)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, db.SSLStatus, string, *time.Time) error); ok {
		r1 = returnFunc(ctx, domain, status, sslError, timestamp)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_UpdateSSLStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSSLStatus'
type MockWebsiteService_UpdateSSLStatus_Call struct {
	*mock.Call
}

// UpdateSSLStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - domain string
//   - status db.SSLStatus
//   - sslError string
//   - timestamp *time.Time
func (_e *MockWebsiteService_Expecter) UpdateSSLStatus(ctx any, domain any, status any, sslError any, timestamp any) *MockWebsiteService_UpdateSSLStatus_Call {
	return &MockWebsiteService_UpdateSSLStatus_Call{Call: _e.mock.On("UpdateSSLStatus", ctx, domain, status, sslError, timestamp)}
}

func (_c *MockWebsiteService_UpdateSSLStatus_Call) Run(run func(ctx context.Context, domain string, status db.SSLStatus, sslError string, timestamp *time.Time)) *MockWebsiteService_UpdateSSLStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 db.SSLStatus
		if args[2] != nil {
			arg2 = args[2].(db.SSLStatus)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *time.Time
		if args[4] != nil {
			arg4 = args[4].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockWebsiteService_UpdateSSLStatus_Call) Return(websiteDomain *db.WebsiteDomain, err error) *MockWebsiteService_UpdateSSLStatus_Call {
	_c.Call.Return(websiteDomain, err)
	return _c
}

func (_c *MockWebsiteService_UpdateSSLStatus_Call) RunAndReturn(run func(ctx context.Context, domain string, status db.SSLStatus, sslError string, timestamp *time.Time) (*db.WebsiteDomain, error)) *MockWebsiteService_UpdateSSLStatus_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWebsite provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) UpdateWebsite(ctx context.Context, userID uint, websiteID uint, updates map[string]interface{}) (*db.Website, error) {
	ret := _mock.Called(ctx, userID, websiteID, updates)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWebsite")
	}

	var r0 *db.Website
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, map[string]interface{}) (*db.Website, error)); ok {
		return returnFunc(ctx, userID, websiteID, updates)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint, map[string]interface{}) *db.Website); ok {
		r0 = returnFunc(ctx, userID, websiteID, updates)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.Website)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint, map[string]interface{}) error); ok {
		r1 = returnFunc(ctx, userID, websiteID, updates)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_UpdateWebsite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWebsite'
type MockWebsiteService_UpdateWebsite_Call struct {
	*mock.Call
}

// UpdateWebsite is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - websiteID uint
//   - updates map[string]interface{}
func (_e *MockWebsiteService_Expecter) UpdateWebsite(ctx any, userID any, websiteID any, updates any) *MockWebsiteService_UpdateWebsite_Call {
	return &MockWebsiteService_UpdateWebsite_Call{Call: _e.mock.On("UpdateWebsite", ctx, userID, websiteID, updates)}
}

func (_c *MockWebsiteService_UpdateWebsite_Call) Run(run func(ctx context.Context, userID uint, websiteID uint, updates map[string]interface{})) *MockWebsiteService_UpdateWebsite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		var arg3 map[string]interface{}
		if args[3] != nil {
			arg3 = args[3].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockWebsiteService_UpdateWebsite_Call) Return(website *db.Website, err error) *MockWebsiteService_UpdateWebsite_Call {
	_c.Call.Return(website, err)
	return _c
}

func (_c *MockWebsiteService_UpdateWebsite_Call) RunAndReturn(run func(ctx context.Context, userID uint, websiteID uint, updates map[string]interface{}) (*db.Website, error)) *MockWebsiteService_UpdateWebsite_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateDNS provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) ValidateDNS(ctx context.Context, userID uint, websiteID uint) (core0.ValidateDNSResult, error) {
	ret := _mock.Called(ctx, userID, websiteID)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDNS")
	}

	var r0 core0.ValidateDNSResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) (core0.ValidateDNSResult, error)); ok {
		return returnFunc(ctx, userID, websiteID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, uint) core0.ValidateDNSResult); ok {
		r0 = returnFunc(ctx, userID, websiteID)
	} else {
		r0 = ret.Get(0).(core0.ValidateDNSResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, uint) error); ok {
		r1 = returnFunc(ctx, userID, websiteID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockWebsiteService_ValidateDNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDNS'
type MockWebsiteService_ValidateDNS_Call struct {
	*mock.Call
}

// ValidateDNS is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - websiteID uint
func (_e *MockWebsiteService_Expecter) ValidateDNS(ctx any, userID any, websiteID any) *MockWebsiteService_ValidateDNS_Call {
	return &MockWebsiteService_ValidateDNS_Call{Call: _e.mock.On("ValidateDNS", ctx, userID, websiteID)}
}

func (_c *MockWebsiteService_ValidateDNS_Call) Run(run func(ctx context.Context, userID uint, websiteID uint)) *MockWebsiteService_ValidateDNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockWebsiteService_ValidateDNS_Call) Return(validateDNSResult core0.ValidateDNSResult, err error) *MockWebsiteService_ValidateDNS_Call {
	_c.Call.Return(validateDNSResult, err)
	return _c
}

func (_c *MockWebsiteService_ValidateDNS_Call) RunAndReturn(run func(ctx context.Context, userID uint, websiteID uint) (core0.ValidateDNSResult, error)) *MockWebsiteService_ValidateDNS_Call {
	_c.Call.Return(run)
	return _c
}

// WaitForPublishes provides a mock function for the type MockWebsiteService
func (_mock *MockWebsiteService) WaitForPublishes() {
	_mock.Called()
	return
}

// MockWebsiteService_WaitForPublishes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WaitForPublishes'
type MockWebsiteService_WaitForPublishes_Call struct {
	*mock.Call
}

// WaitForPublishes is a helper method to define mock.On call
func (_e *MockWebsiteService_Expecter) WaitForPublishes() *MockWebsiteService_WaitForPublishes_Call {
	return &MockWebsiteService_WaitForPublishes_Call{Call: _e.mock.On("WaitForPublishes")}
}

func (_c *MockWebsiteService_WaitForPublishes_Call) Run(run func()) *MockWebsiteService_WaitForPublishes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockWebsiteService_WaitForPublishes_Call) Return() *MockWebsiteService_WaitForPublishes_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockWebsiteService_WaitForPublishes_Call) RunAndReturn(run func()) *MockWebsiteService_WaitForPublishes_Call {
	_c.Run(run)
	return _c
}
