// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/core"
	portalcore "go.lumeweb.com/portal/core"
)

// NewMockMetadataStore creates a new instance of MockMetadataStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataStore {
	mock := &MockMetadataStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataStore is an autogenerated mock type for the MetadataStore type
type MockMetadataStore struct {
	mock.Mock
}

type MockMetadataStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataStore) EXPECT() *MockMetadataStore_Expecter {
	return &MockMetadataStore_Expecter{mock: &_m.Mock}
}

// BatchPin provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BatchPin(ctx context.Context, pinnedBlocks []core.PinnedBlock) error {
	ret := _mock.Called(ctx, pinnedBlocks)

	if len(ret) == 0 {
		panic("no return value specified for BatchPin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []core.PinnedBlock) error); ok {
		r0 = returnFunc(ctx, pinnedBlocks)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_BatchPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchPin'
type MockMetadataStore_BatchPin_Call struct {
	*mock.Call
}

// BatchPin is a helper method to define mock.On call
//   - ctx context.Context
//   - pinnedBlocks []core.PinnedBlock
func (_e *MockMetadataStore_Expecter) BatchPin(ctx any, pinnedBlocks any) *MockMetadataStore_BatchPin_Call {
	return &MockMetadataStore_BatchPin_Call{Call: _e.mock.On("BatchPin", ctx, pinnedBlocks)}
}

func (_c *MockMetadataStore_BatchPin_Call) Run(run func(ctx context.Context, pinnedBlocks []core.PinnedBlock)) *MockMetadataStore_BatchPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []core.PinnedBlock
		if args[1] != nil {
			arg1 = args[1].([]core.PinnedBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BatchPin_Call) Return(err error) *MockMetadataStore_BatchPin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_BatchPin_Call) RunAndReturn(run func(ctx context.Context, pinnedBlocks []core.PinnedBlock) error) *MockMetadataStore_BatchPin_Call {
	_c.Call.Return(run)
	return _c
}

// BlockChildren provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BlockChildren(ctx context.Context, c cid.Cid, max *int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, c, max)

	if len(ret) == 0 {
		panic("no return value specified for BlockChildren")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, *int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, c, max)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, *int) []cid.Cid); ok {
		r0 = returnFunc(ctx, c, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, *int) error); ok {
		r1 = returnFunc(ctx, c, max)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_BlockChildren_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockChildren'
type MockMetadataStore_BlockChildren_Call struct {
	*mock.Call
}

// BlockChildren is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
//   - max *int
func (_e *MockMetadataStore_Expecter) BlockChildren(ctx any, c any, max any) *MockMetadataStore_BlockChildren_Call {
	return &MockMetadataStore_BlockChildren_Call{Call: _e.mock.On("BlockChildren", ctx, c, max)}
}

func (_c *MockMetadataStore_BlockChildren_Call) Run(run func(ctx context.Context, c cid.Cid, max *int)) *MockMetadataStore_BlockChildren_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BlockChildren_Call) Return(siblings []cid.Cid, err error) *MockMetadataStore_BlockChildren_Call {
	_c.Call.Return(siblings, err)
	return _c
}

func (_c *MockMetadataStore_BlockChildren_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid, max *int) ([]cid.Cid, error)) *MockMetadataStore_BlockChildren_Call {
	_c.Call.Return(run)
	return _c
}

// BlockExists provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BlockExists(ctx context.Context, c cid.Cid) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for BlockExists")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_BlockExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockExists'
type MockMetadataStore_BlockExists_Call struct {
	*mock.Call
}

// BlockExists is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockMetadataStore_Expecter) BlockExists(ctx any, c any) *MockMetadataStore_BlockExists_Call {
	return &MockMetadataStore_BlockExists_Call{Call: _e.mock.On("BlockExists", ctx, c)}
}

func (_c *MockMetadataStore_BlockExists_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockMetadataStore_BlockExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BlockExists_Call) Return(err error) *MockMetadataStore_BlockExists_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_BlockExists_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) error) *MockMetadataStore_BlockExists_Call {
	_c.Call.Return(run)
	return _c
}

// BlockSiblings provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) BlockSiblings(ctx context.Context, c cid.Cid, max int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, c, max)

	if len(ret) == 0 {
		panic("no return value specified for BlockSiblings")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, c, max)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, int) []cid.Cid); ok {
		r0 = returnFunc(ctx, c, max)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, int) error); ok {
		r1 = returnFunc(ctx, c, max)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_BlockSiblings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BlockSiblings'
type MockMetadataStore_BlockSiblings_Call struct {
	*mock.Call
}

// BlockSiblings is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
//   - max int
func (_e *MockMetadataStore_Expecter) BlockSiblings(ctx any, c any, max any) *MockMetadataStore_BlockSiblings_Call {
	return &MockMetadataStore_BlockSiblings_Call{Call: _e.mock.On("BlockSiblings", ctx, c, max)}
}

func (_c *MockMetadataStore_BlockSiblings_Call) Run(run func(ctx context.Context, c cid.Cid, max int)) *MockMetadataStore_BlockSiblings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_BlockSiblings_Call) Return(siblings []cid.Cid, err error) *MockMetadataStore_BlockSiblings_Call {
	_c.Call.Return(siblings, err)
	return _c
}

func (_c *MockMetadataStore_BlockSiblings_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid, max int) ([]cid.Cid, error)) *MockMetadataStore_BlockSiblings_Call {
	_c.Call.Return(run)
	return _c
}

// MarkBlockReady provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) MarkBlockReady(c cid.Cid, ready bool) error {
	ret := _mock.Called(c, ready)

	if len(ret) == 0 {
		panic("no return value specified for MarkBlockReady")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cid.Cid, bool) error); ok {
		r0 = returnFunc(c, ready)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_MarkBlockReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkBlockReady'
type MockMetadataStore_MarkBlockReady_Call struct {
	*mock.Call
}

// MarkBlockReady is a helper method to define mock.On call
//   - c cid.Cid
//   - ready bool
func (_e *MockMetadataStore_Expecter) MarkBlockReady(c any, ready any) *MockMetadataStore_MarkBlockReady_Call {
	return &MockMetadataStore_MarkBlockReady_Call{Call: _e.mock.On("MarkBlockReady", c, ready)}
}

func (_c *MockMetadataStore_MarkBlockReady_Call) Run(run func(c cid.Cid, ready bool)) *MockMetadataStore_MarkBlockReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cid.Cid
		if args[0] != nil {
			arg0 = args[0].(cid.Cid)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_MarkBlockReady_Call) Return(err error) *MockMetadataStore_MarkBlockReady_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_MarkBlockReady_Call) RunAndReturn(run func(c cid.Cid, ready bool) error) *MockMetadataStore_MarkBlockReady_Call {
	_c.Call.Return(run)
	return _c
}

// Pin provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Pin(ctx context.Context, pinnedBlock core.PinnedBlock) error {
	ret := _mock.Called(ctx, pinnedBlock)

	if len(ret) == 0 {
		panic("no return value specified for Pin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, core.PinnedBlock) error); ok {
		r0 = returnFunc(ctx, pinnedBlock)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_Pin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pin'
type MockMetadataStore_Pin_Call struct {
	*mock.Call
}

// Pin is a helper method to define mock.On call
//   - ctx context.Context
//   - pinnedBlock core.PinnedBlock
func (_e *MockMetadataStore_Expecter) Pin(ctx any, pinnedBlock any) *MockMetadataStore_Pin_Call {
	return &MockMetadataStore_Pin_Call{Call: _e.mock.On("Pin", ctx, pinnedBlock)}
}

func (_c *MockMetadataStore_Pin_Call) Run(run func(ctx context.Context, pinnedBlock core.PinnedBlock)) *MockMetadataStore_Pin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 core.PinnedBlock
		if args[1] != nil {
			arg1 = args[1].(core.PinnedBlock)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Pin_Call) Return(err error) *MockMetadataStore_Pin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_Pin_Call) RunAndReturn(run func(ctx context.Context, pinnedBlock core.PinnedBlock) error) *MockMetadataStore_Pin_Call {
	_c.Call.Return(run)
	return _c
}

// Pinned provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Pinned(ctx context.Context, offset int, limit int) ([]cid.Cid, error) {
	ret := _mock.Called(ctx, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for Pinned")
	}

	var r0 []cid.Cid
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) ([]cid.Cid, error)); ok {
		return returnFunc(ctx, offset, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int) []cid.Cid); ok {
		r0 = returnFunc(ctx, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int) error); ok {
		r1 = returnFunc(ctx, offset, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_Pinned_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pinned'
type MockMetadataStore_Pinned_Call struct {
	*mock.Call
}

// Pinned is a helper method to define mock.On call
//   - ctx context.Context
//   - offset int
//   - limit int
func (_e *MockMetadataStore_Expecter) Pinned(ctx any, offset any, limit any) *MockMetadataStore_Pinned_Call {
	return &MockMetadataStore_Pinned_Call{Call: _e.mock.On("Pinned", ctx, offset, limit)}
}

func (_c *MockMetadataStore_Pinned_Call) Run(run func(ctx context.Context, offset int, limit int)) *MockMetadataStore_Pinned_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Pinned_Call) Return(roots []cid.Cid, err error) *MockMetadataStore_Pinned_Call {
	_c.Call.Return(roots, err)
	return _c
}

func (_c *MockMetadataStore_Pinned_Call) RunAndReturn(run func(ctx context.Context, offset int, limit int) ([]cid.Cid, error)) *MockMetadataStore_Pinned_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessMissingUnixFSNames provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) ProcessMissingUnixFSNames(ctx context.Context, cids []cid.Cid) error {
	ret := _mock.Called(ctx, cids)

	if len(ret) == 0 {
		panic("no return value specified for ProcessMissingUnixFSNames")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid) error); ok {
		r0 = returnFunc(ctx, cids)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_ProcessMissingUnixFSNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessMissingUnixFSNames'
type MockMetadataStore_ProcessMissingUnixFSNames_Call struct {
	*mock.Call
}

// ProcessMissingUnixFSNames is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []cid.Cid
func (_e *MockMetadataStore_Expecter) ProcessMissingUnixFSNames(ctx any, cids any) *MockMetadataStore_ProcessMissingUnixFSNames_Call {
	return &MockMetadataStore_ProcessMissingUnixFSNames_Call{Call: _e.mock.On("ProcessMissingUnixFSNames", ctx, cids)}
}

func (_c *MockMetadataStore_ProcessMissingUnixFSNames_Call) Run(run func(ctx context.Context, cids []cid.Cid)) *MockMetadataStore_ProcessMissingUnixFSNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cid.Cid
		if args[1] != nil {
			arg1 = args[1].([]cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_ProcessMissingUnixFSNames_Call) Return(err error) *MockMetadataStore_ProcessMissingUnixFSNames_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_ProcessMissingUnixFSNames_Call) RunAndReturn(run func(ctx context.Context, cids []cid.Cid) error) *MockMetadataStore_ProcessMissingUnixFSNames_Call {
	_c.Call.Return(run)
	return _c
}

// ResolveDAG provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) ResolveDAG(ctx context.Context, rootCID cid.Cid) ([]portalcore.DAGBlockNode, error) {
	ret := _mock.Called(ctx, rootCID)

	if len(ret) == 0 {
		panic("ResolveDAG requires at least 1 return value")
	}

	var r0 []portalcore.DAGBlockNode
	if ret[0] != nil {
		r0 = ret[0].([]portalcore.DAGBlockNode)
	}

	var r1 error
	if len(ret) > 1 && ret[1] != nil {
		r1 = ret[1].(error)
	}

	return r0, r1
}

// MockMetadataStore_ResolveDAG_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResolveDAG'
type MockMetadataStore_ResolveDAG_Call struct {
	*mock.Call
}

// ResolveDAG is a helper method to define mock.On call
//   - ctx context.Context
//   - rootCID cid.Cid
func (_e *MockMetadataStore_Expecter) ResolveDAG(ctx interface{}, rootCID interface{}) *MockMetadataStore_ResolveDAG_Call {
	return &MockMetadataStore_ResolveDAG_Call{Call: _e.mock.On("ResolveDAG", ctx, rootCID)}
}

func (_c *MockMetadataStore_ResolveDAG_Call) Run(run func(ctx context.Context, rootCID cid.Cid)) *MockMetadataStore_ResolveDAG_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(cid.Cid))
	})
	return _c
}

func (_c *MockMetadataStore_ResolveDAG_Call) Return(nodes []portalcore.DAGBlockNode, err error) *MockMetadataStore_ResolveDAG_Call {
	_c.Call.Return(nodes, err)
	return _c
}

func (_c *MockMetadataStore_ResolveDAG_Call) RunAndReturn(run func(ctx context.Context, rootCID cid.Cid) ([]portalcore.DAGBlockNode, error)) *MockMetadataStore_ResolveDAG_Call {
	_c.Call.Return(run)
	return _c
}

// Size provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Size(ctx context.Context, c cid.Cid) (uint64, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Size")
	}

	var r0 uint64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (uint64, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) uint64); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(uint64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataStore_Size_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Size'
type MockMetadataStore_Size_Call struct {
	*mock.Call
}

// Size is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockMetadataStore_Expecter) Size(ctx any, c any) *MockMetadataStore_Size_Call {
	return &MockMetadataStore_Size_Call{Call: _e.mock.On("Size", ctx, c)}
}

func (_c *MockMetadataStore_Size_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockMetadataStore_Size_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Size_Call) Return(v uint64, err error) *MockMetadataStore_Size_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockMetadataStore_Size_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (uint64, error)) *MockMetadataStore_Size_Call {
	_c.Call.Return(run)
	return _c
}

// Unpin provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) Unpin(ctx context.Context, c cid.Cid) error {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for Unpin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) error); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_Unpin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Unpin'
type MockMetadataStore_Unpin_Call struct {
	*mock.Call
}

// Unpin is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockMetadataStore_Expecter) Unpin(ctx any, c any) *MockMetadataStore_Unpin_Call {
	return &MockMetadataStore_Unpin_Call{Call: _e.mock.On("Unpin", ctx, c)}
}

func (_c *MockMetadataStore_Unpin_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockMetadataStore_Unpin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_Unpin_Call) Return(err error) *MockMetadataStore_Unpin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_Unpin_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) error) *MockMetadataStore_Unpin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUnixFSMetadata provides a mock function for the type MockMetadataStore
func (_mock *MockMetadataStore) UpdateUnixFSMetadata(c cid.Cid, metadata any) error {
	ret := _mock.Called(c, metadata)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUnixFSMetadata")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(cid.Cid, any) error); ok {
		r0 = returnFunc(c, metadata)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataStore_UpdateUnixFSMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUnixFSMetadata'
type MockMetadataStore_UpdateUnixFSMetadata_Call struct {
	*mock.Call
}

// UpdateUnixFSMetadata is a helper method to define mock.On call
//   - c cid.Cid
//   - metadata any
func (_e *MockMetadataStore_Expecter) UpdateUnixFSMetadata(c any, metadata any) *MockMetadataStore_UpdateUnixFSMetadata_Call {
	return &MockMetadataStore_UpdateUnixFSMetadata_Call{Call: _e.mock.On("UpdateUnixFSMetadata", c, metadata)}
}

func (_c *MockMetadataStore_UpdateUnixFSMetadata_Call) Run(run func(c cid.Cid, metadata any)) *MockMetadataStore_UpdateUnixFSMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cid.Cid
		if args[0] != nil {
			arg0 = args[0].(cid.Cid)
		}
		var arg1 any
		if args[1] != nil {
			arg1 = args[1].(any)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataStore_UpdateUnixFSMetadata_Call) Return(err error) *MockMetadataStore_UpdateUnixFSMetadata_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataStore_UpdateUnixFSMetadata_Call) RunAndReturn(run func(c cid.Cid, metadata any) error) *MockMetadataStore_UpdateUnixFSMetadata_Call {
	_c.Call.Return(run)
	return _c
}
