// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"go.lumeweb.com/portal/db/types"
	"go.lumeweb.com/queryutil"
	"go.lumeweb.com/queryutil/filter"
	"gorm.io/datatypes"
	"gorm.io/gorm"
)

// NewMockIPFSPinService creates a new instance of MockIPFSPinService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPFSPinService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPFSPinService {
	mock := &MockIPFSPinService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPFSPinService is an autogenerated mock type for the IPFSPinService type
type MockIPFSPinService struct {
	mock.Mock
}

type MockIPFSPinService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPFSPinService) EXPECT() *MockIPFSPinService_Expecter {
	return &MockIPFSPinService_Expecter{mock: &_m.Mock}
}

// AddPin provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) AddPin(ctx context.Context, pin *db.IPFSPin) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, pin)

	if len(ret) == 0 {
		panic("no return value specified for AddPin")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.IPFSPin) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, pin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.IPFSPin) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, pin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *db.IPFSPin) error); ok {
		r1 = returnFunc(ctx, pin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_AddPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPin'
type MockIPFSPinService_AddPin_Call struct {
	*mock.Call
}

// AddPin is a helper method to define mock.On call
//   - ctx context.Context
//   - pin *db.IPFSPin
func (_e *MockIPFSPinService_Expecter) AddPin(ctx any, pin any) *MockIPFSPinService_AddPin_Call {
	return &MockIPFSPinService_AddPin_Call{Call: _e.mock.On("AddPin", ctx, pin)}
}

func (_c *MockIPFSPinService_AddPin_Call) Run(run func(ctx context.Context, pin *db.IPFSPin)) *MockIPFSPinService_AddPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.IPFSPin
		if args[1] != nil {
			arg1 = args[1].(*db.IPFSPin)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_AddPin_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_AddPin_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_AddPin_Call) RunAndReturn(run func(ctx context.Context, pin *db.IPFSPin) (*db.IPFSPin, error)) *MockIPFSPinService_AddPin_Call {
	_c.Call.Return(run)
	return _c
}

// Config provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockIPFSPinService_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockIPFSPinService_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockIPFSPinService_Expecter) Config() *MockIPFSPinService_Config_Call {
	return &MockIPFSPinService_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockIPFSPinService_Config_Call) Run(run func()) *MockIPFSPinService_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSPinService_Config_Call) Return(manager config.Manager) *MockIPFSPinService_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockIPFSPinService_Config_Call) RunAndReturn(run func() config.Manager) *MockIPFSPinService_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockIPFSPinService_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockIPFSPinService_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockIPFSPinService_Expecter) Context() *MockIPFSPinService_Context_Call {
	return &MockIPFSPinService_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockIPFSPinService_Context_Call) Run(run func()) *MockIPFSPinService_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSPinService_Context_Call) Return(context1 core.Context) *MockIPFSPinService_Context_Call {
	_c.Call.Return(context1)
	return _c
}

func (_c *MockIPFSPinService_Context_Call) RunAndReturn(run func() core.Context) *MockIPFSPinService_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockIPFSPinService_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockIPFSPinService_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockIPFSPinService_Expecter) DB() *MockIPFSPinService_DB_Call {
	return &MockIPFSPinService_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockIPFSPinService_DB_Call) Run(run func()) *MockIPFSPinService_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSPinService_DB_Call) Return(dB *gorm.DB) *MockIPFSPinService_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockIPFSPinService_DB_Call) RunAndReturn(run func() *gorm.DB) *MockIPFSPinService_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePin provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) DeletePin(ctx context.Context, requestID types.BinaryUUID) error {
	ret := _mock.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID) error); ok {
		r0 = returnFunc(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSPinService_DeletePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePin'
type MockIPFSPinService_DeletePin_Call struct {
	*mock.Call
}

// DeletePin is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID types.BinaryUUID
func (_e *MockIPFSPinService_Expecter) DeletePin(ctx any, requestID any) *MockIPFSPinService_DeletePin_Call {
	return &MockIPFSPinService_DeletePin_Call{Call: _e.mock.On("DeletePin", ctx, requestID)}
}

func (_c *MockIPFSPinService_DeletePin_Call) Run(run func(ctx context.Context, requestID types.BinaryUUID)) *MockIPFSPinService_DeletePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(types.BinaryUUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_DeletePin_Call) Return(err error) *MockIPFSPinService_DeletePin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSPinService_DeletePin_Call) RunAndReturn(run func(ctx context.Context, requestID types.BinaryUUID) error) *MockIPFSPinService_DeletePin_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePinForUser provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) DeletePinForUser(ctx context.Context, userID uint, requestID types.BinaryUUID) error {
	ret := _mock.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePinForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, types.BinaryUUID) error); ok {
		r0 = returnFunc(ctx, userID, requestID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSPinService_DeletePinForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePinForUser'
type MockIPFSPinService_DeletePinForUser_Call struct {
	*mock.Call
}

// DeletePinForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - requestID types.BinaryUUID
func (_e *MockIPFSPinService_Expecter) DeletePinForUser(ctx any, userID any, requestID any) *MockIPFSPinService_DeletePinForUser_Call {
	return &MockIPFSPinService_DeletePinForUser_Call{Call: _e.mock.On("DeletePinForUser", ctx, userID, requestID)}
}

func (_c *MockIPFSPinService_DeletePinForUser_Call) Run(run func(ctx context.Context, userID uint, requestID types.BinaryUUID)) *MockIPFSPinService_DeletePinForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 types.BinaryUUID
		if args[2] != nil {
			arg2 = args[2].(types.BinaryUUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_DeletePinForUser_Call) Return(err error) *MockIPFSPinService_DeletePinForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSPinService_DeletePinForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, requestID types.BinaryUUID) error) *MockIPFSPinService_DeletePinForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPinByCIDAndUser provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) GetPinByCIDAndUser(ctx context.Context, c cid.Cid, userID uint) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, c, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetPinByCIDAndUser")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, uint) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, c, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, uint) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, c, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid, uint) error); ok {
		r1 = returnFunc(ctx, c, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_GetPinByCIDAndUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPinByCIDAndUser'
type MockIPFSPinService_GetPinByCIDAndUser_Call struct {
	*mock.Call
}

// GetPinByCIDAndUser is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
//   - userID uint
func (_e *MockIPFSPinService_Expecter) GetPinByCIDAndUser(ctx any, c any, userID any) *MockIPFSPinService_GetPinByCIDAndUser_Call {
	return &MockIPFSPinService_GetPinByCIDAndUser_Call{Call: _e.mock.On("GetPinByCIDAndUser", ctx, c, userID)}
}

func (_c *MockIPFSPinService_GetPinByCIDAndUser_Call) Run(run func(ctx context.Context, c cid.Cid, userID uint)) *MockIPFSPinService_GetPinByCIDAndUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 uint
		if args[2] != nil {
			arg2 = args[2].(uint)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_GetPinByCIDAndUser_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_GetPinByCIDAndUser_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_GetPinByCIDAndUser_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid, userID uint) (*db.IPFSPin, error)) *MockIPFSPinService_GetPinByCIDAndUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetPinByRequestID provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) GetPinByRequestID(ctx context.Context, requestID types.BinaryUUID) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetPinByRequestID")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, requestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.BinaryUUID) error); ok {
		r1 = returnFunc(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_GetPinByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPinByRequestID'
type MockIPFSPinService_GetPinByRequestID_Call struct {
	*mock.Call
}

// GetPinByRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID types.BinaryUUID
func (_e *MockIPFSPinService_Expecter) GetPinByRequestID(ctx any, requestID any) *MockIPFSPinService_GetPinByRequestID_Call {
	return &MockIPFSPinService_GetPinByRequestID_Call{Call: _e.mock.On("GetPinByRequestID", ctx, requestID)}
}

func (_c *MockIPFSPinService_GetPinByRequestID_Call) Run(run func(ctx context.Context, requestID types.BinaryUUID)) *MockIPFSPinService_GetPinByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(types.BinaryUUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_GetPinByRequestID_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_GetPinByRequestID_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_GetPinByRequestID_Call) RunAndReturn(run func(ctx context.Context, requestID types.BinaryUUID) (*db.IPFSPin, error)) *MockIPFSPinService_GetPinByRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// GetPinByRequestIDForUser provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) GetPinByRequestIDForUser(ctx context.Context, userID uint, requestID types.BinaryUUID) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, userID, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetPinByRequestIDForUser")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, types.BinaryUUID) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, userID, requestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, types.BinaryUUID) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, userID, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, types.BinaryUUID) error); ok {
		r1 = returnFunc(ctx, userID, requestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_GetPinByRequestIDForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPinByRequestIDForUser'
type MockIPFSPinService_GetPinByRequestIDForUser_Call struct {
	*mock.Call
}

// GetPinByRequestIDForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - requestID types.BinaryUUID
func (_e *MockIPFSPinService_Expecter) GetPinByRequestIDForUser(ctx any, userID any, requestID any) *MockIPFSPinService_GetPinByRequestIDForUser_Call {
	return &MockIPFSPinService_GetPinByRequestIDForUser_Call{Call: _e.mock.On("GetPinByRequestIDForUser", ctx, userID, requestID)}
}

func (_c *MockIPFSPinService_GetPinByRequestIDForUser_Call) Run(run func(ctx context.Context, userID uint, requestID types.BinaryUUID)) *MockIPFSPinService_GetPinByRequestIDForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 types.BinaryUUID
		if args[2] != nil {
			arg2 = args[2].(types.BinaryUUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_GetPinByRequestIDForUser_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_GetPinByRequestIDForUser_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_GetPinByRequestIDForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, requestID types.BinaryUUID) (*db.IPFSPin, error)) *MockIPFSPinService_GetPinByRequestIDForUser_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIPFSPinService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIPFSPinService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIPFSPinService_Expecter) ID() *MockIPFSPinService_ID_Call {
	return &MockIPFSPinService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIPFSPinService_ID_Call) Run(run func()) *MockIPFSPinService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSPinService_ID_Call) Return(s string) *MockIPFSPinService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIPFSPinService_ID_Call) RunAndReturn(run func() string) *MockIPFSPinService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPins provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ListPins(ctx context.Context, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.IPFSPin, int64, error) {
	ret := _mock.Called(ctx, filter1, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPins")
	}

	var r0 []*db.IPFSPin
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) ([]*db.IPFSPin, int64, error)); ok {
		return returnFunc(ctx, filter1, sort, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) []*db.IPFSPin); ok {
		r0 = returnFunc(ctx, filter1, sort, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, filter1, sort, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, filter1, sort, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPFSPinService_ListPins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPins'
type MockIPFSPinService_ListPins_Call struct {
	*mock.Call
}

// ListPins is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 []queryutil.CrudFilter
//   - sort []filter.Sort
//   - pagination queryutil.Pagination
func (_e *MockIPFSPinService_Expecter) ListPins(ctx any, filter1 any, sort any, pagination any) *MockIPFSPinService_ListPins_Call {
	return &MockIPFSPinService_ListPins_Call{Call: _e.mock.On("ListPins", ctx, filter1, sort, pagination)}
}

func (_c *MockIPFSPinService_ListPins_Call) Run(run func(ctx context.Context, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination)) *MockIPFSPinService_ListPins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []filter.Sort
		if args[2] != nil {
			arg2 = args[2].([]filter.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ListPins_Call) Return(iPFSPins []*db.IPFSPin, n int64, err error) *MockIPFSPinService_ListPins_Call {
	_c.Call.Return(iPFSPins, n, err)
	return _c
}

func (_c *MockIPFSPinService_ListPins_Call) RunAndReturn(run func(ctx context.Context, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.IPFSPin, int64, error)) *MockIPFSPinService_ListPins_Call {
	_c.Call.Return(run)
	return _c
}

// ListPinsForUser provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ListPinsForUser(ctx context.Context, userID uint, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.IPFSPin, int64, error) {
	ret := _mock.Called(ctx, userID, filter1, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPinsForUser")
	}

	var r0 []*db.IPFSPin
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) ([]*db.IPFSPin, int64, error)); ok {
		return returnFunc(ctx, userID, filter1, sort, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) []*db.IPFSPin); ok {
		r0 = returnFunc(ctx, userID, filter1, sort, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, userID, filter1, sort, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uint, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, userID, filter1, sort, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPFSPinService_ListPinsForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPinsForUser'
type MockIPFSPinService_ListPinsForUser_Call struct {
	*mock.Call
}

// ListPinsForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - filter1 []queryutil.CrudFilter
//   - sort []filter.Sort
//   - pagination queryutil.Pagination
func (_e *MockIPFSPinService_Expecter) ListPinsForUser(ctx any, userID any, filter1 any, sort any, pagination any) *MockIPFSPinService_ListPinsForUser_Call {
	return &MockIPFSPinService_ListPinsForUser_Call{Call: _e.mock.On("ListPinsForUser", ctx, userID, filter1, sort, pagination)}
}

func (_c *MockIPFSPinService_ListPinsForUser_Call) Run(run func(ctx context.Context, userID uint, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination)) *MockIPFSPinService_ListPinsForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 []queryutil.CrudFilter
		if args[2] != nil {
			arg2 = args[2].([]queryutil.CrudFilter)
		}
		var arg3 []filter.Sort
		if args[3] != nil {
			arg3 = args[3].([]filter.Sort)
		}
		var arg4 queryutil.Pagination
		if args[4] != nil {
			arg4 = args[4].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ListPinsForUser_Call) Return(iPFSPins []*db.IPFSPin, n int64, err error) *MockIPFSPinService_ListPinsForUser_Call {
	_c.Call.Return(iPFSPins, n, err)
	return _c
}

func (_c *MockIPFSPinService_ListPinsForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.IPFSPin, int64, error)) *MockIPFSPinService_ListPinsForUser_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockIPFSPinService_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockIPFSPinService_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockIPFSPinService_Expecter) Logger() *MockIPFSPinService_Logger_Call {
	return &MockIPFSPinService_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockIPFSPinService_Logger_Call) Run(run func()) *MockIPFSPinService_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSPinService_Logger_Call) Return(logger *core.Logger) *MockIPFSPinService_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockIPFSPinService_Logger_Call) RunAndReturn(run func() *core.Logger) *MockIPFSPinService_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePin provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ReplacePin(ctx context.Context, userId uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, userId, userIp, oldRequestID, newPin)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePin")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, userId, userIp, oldRequestID, newPin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, userId, userIp, oldRequestID, newPin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) error); ok {
		r1 = returnFunc(ctx, userId, userIp, oldRequestID, newPin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_ReplacePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePin'
type MockIPFSPinService_ReplacePin_Call struct {
	*mock.Call
}

// ReplacePin is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - userIp string
//   - oldRequestID types.BinaryUUID
//   - newPin *db.IPFSPin
func (_e *MockIPFSPinService_Expecter) ReplacePin(ctx any, userId any, userIp any, oldRequestID any, newPin any) *MockIPFSPinService_ReplacePin_Call {
	return &MockIPFSPinService_ReplacePin_Call{Call: _e.mock.On("ReplacePin", ctx, userId, userIp, oldRequestID, newPin)}
}

func (_c *MockIPFSPinService_ReplacePin_Call) Run(run func(ctx context.Context, userId uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin)) *MockIPFSPinService_ReplacePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 types.BinaryUUID
		if args[3] != nil {
			arg3 = args[3].(types.BinaryUUID)
		}
		var arg4 *db.IPFSPin
		if args[4] != nil {
			arg4 = args[4].(*db.IPFSPin)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ReplacePin_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_ReplacePin_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_ReplacePin_Call) RunAndReturn(run func(ctx context.Context, userId uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin) (*db.IPFSPin, error)) *MockIPFSPinService_ReplacePin_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePinForUser provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ReplacePinForUser(ctx context.Context, userID uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, userID, userIp, oldRequestID, newPin)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePinForUser")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, userID, userIp, oldRequestID, newPin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, userID, userIp, oldRequestID, newPin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) error); ok {
		r1 = returnFunc(ctx, userID, userIp, oldRequestID, newPin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_ReplacePinForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePinForUser'
type MockIPFSPinService_ReplacePinForUser_Call struct {
	*mock.Call
}

// ReplacePinForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uint
//   - userIp string
//   - oldRequestID types.BinaryUUID
//   - newPin *db.IPFSPin
func (_e *MockIPFSPinService_Expecter) ReplacePinForUser(ctx any, userID any, userIp any, oldRequestID any, newPin any) *MockIPFSPinService_ReplacePinForUser_Call {
	return &MockIPFSPinService_ReplacePinForUser_Call{Call: _e.mock.On("ReplacePinForUser", ctx, userID, userIp, oldRequestID, newPin)}
}

func (_c *MockIPFSPinService_ReplacePinForUser_Call) Run(run func(ctx context.Context, userID uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin)) *MockIPFSPinService_ReplacePinForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 types.BinaryUUID
		if args[3] != nil {
			arg3 = args[3].(types.BinaryUUID)
		}
		var arg4 *db.IPFSPin
		if args[4] != nil {
			arg4 = args[4].(*db.IPFSPin)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ReplacePinForUser_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_ReplacePinForUser_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_ReplacePinForUser_Call) RunAndReturn(run func(ctx context.Context, userID uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin) (*db.IPFSPin, error)) *MockIPFSPinService_ReplacePinForUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockIPFSPinService_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockIPFSPinService_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockIPFSPinService_Expecter) SetConfig(cfg any) *MockIPFSPinService_SetConfig_Call {
	return &MockIPFSPinService_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockIPFSPinService_SetConfig_Call) Run(run func(cfg config.Manager)) *MockIPFSPinService_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_SetConfig_Call) Return() *MockIPFSPinService_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPFSPinService_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockIPFSPinService_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockIPFSPinService_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockIPFSPinService_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockIPFSPinService_Expecter) SetContext(ctx any) *MockIPFSPinService_SetContext_Call {
	return &MockIPFSPinService_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockIPFSPinService_SetContext_Call) Run(run func(ctx core.Context)) *MockIPFSPinService_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_SetContext_Call) Return() *MockIPFSPinService_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPFSPinService_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockIPFSPinService_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) SetDB(db1 *gorm.DB) {
	_mock.Called(db1)
	return
}

// MockIPFSPinService_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockIPFSPinService_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db1 *gorm.DB
func (_e *MockIPFSPinService_Expecter) SetDB(db1 any) *MockIPFSPinService_SetDB_Call {
	return &MockIPFSPinService_SetDB_Call{Call: _e.mock.On("SetDB", db1)}
}

func (_c *MockIPFSPinService_SetDB_Call) Run(run func(db1 *gorm.DB)) *MockIPFSPinService_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_SetDB_Call) Return() *MockIPFSPinService_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPFSPinService_SetDB_Call) RunAndReturn(run func(db1 *gorm.DB)) *MockIPFSPinService_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockIPFSPinService_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockIPFSPinService_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockIPFSPinService_Expecter) SetLogger(logger any) *MockIPFSPinService_SetLogger_Call {
	return &MockIPFSPinService_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockIPFSPinService_SetLogger_Call) Run(run func(logger *core.Logger)) *MockIPFSPinService_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_SetLogger_Call) Return() *MockIPFSPinService_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPFSPinService_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockIPFSPinService_SetLogger_Call {
	_c.Run(run)
	return _c
}

// UpdatePinStatus provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) UpdatePinStatus(ctx context.Context, requestID types.BinaryUUID, status db.PinningStatus, info datatypes.JSON) error {
	ret := _mock.Called(ctx, requestID, status, info)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePinStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID, db.PinningStatus, datatypes.JSON) error); ok {
		r0 = returnFunc(ctx, requestID, status, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSPinService_UpdatePinStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePinStatus'
type MockIPFSPinService_UpdatePinStatus_Call struct {
	*mock.Call
}

// UpdatePinStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID types.BinaryUUID
//   - status db.PinningStatus
//   - info datatypes.JSON
func (_e *MockIPFSPinService_Expecter) UpdatePinStatus(ctx any, requestID any, status any, info any) *MockIPFSPinService_UpdatePinStatus_Call {
	return &MockIPFSPinService_UpdatePinStatus_Call{Call: _e.mock.On("UpdatePinStatus", ctx, requestID, status, info)}
}

func (_c *MockIPFSPinService_UpdatePinStatus_Call) Run(run func(ctx context.Context, requestID types.BinaryUUID, status db.PinningStatus, info datatypes.JSON)) *MockIPFSPinService_UpdatePinStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(types.BinaryUUID)
		}
		var arg2 db.PinningStatus
		if args[2] != nil {
			arg2 = args[2].(db.PinningStatus)
		}
		var arg3 datatypes.JSON
		if args[3] != nil {
			arg3 = args[3].(datatypes.JSON)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_UpdatePinStatus_Call) Return(err error) *MockIPFSPinService_UpdatePinStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSPinService_UpdatePinStatus_Call) RunAndReturn(run func(ctx context.Context, requestID types.BinaryUUID, status db.PinningStatus, info datatypes.JSON) error) *MockIPFSPinService_UpdatePinStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateDAGCompletion provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ValidateDAGCompletion(ctx context.Context, pin *db.IPFSPin) ([][]byte, error) {
	ret := _mock.Called(ctx, pin)

	if len(ret) == 0 {
		panic("no return value specified for ValidateDAGCompletion")
	}

	var r0 [][]byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.IPFSPin) ([][]byte, error)); ok {
		return returnFunc(ctx, pin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.IPFSPin) [][]byte); ok {
		r0 = returnFunc(ctx, pin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *db.IPFSPin) error); ok {
		r1 = returnFunc(ctx, pin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_ValidateDAGCompletion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateDAGCompletion'
type MockIPFSPinService_ValidateDAGCompletion_Call struct {
	*mock.Call
}

// ValidateDAGCompletion is a helper method to define mock.On call
//   - ctx context.Context
//   - pin *db.IPFSPin
func (_e *MockIPFSPinService_Expecter) ValidateDAGCompletion(ctx any, pin any) *MockIPFSPinService_ValidateDAGCompletion_Call {
	return &MockIPFSPinService_ValidateDAGCompletion_Call{Call: _e.mock.On("ValidateDAGCompletion", ctx, pin)}
}

func (_c *MockIPFSPinService_ValidateDAGCompletion_Call) Run(run func(ctx context.Context, pin *db.IPFSPin)) *MockIPFSPinService_ValidateDAGCompletion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.IPFSPin
		if args[1] != nil {
			arg1 = args[1].(*db.IPFSPin)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ValidateDAGCompletion_Call) Return(bytess [][]byte, err error) *MockIPFSPinService_ValidateDAGCompletion_Call {
	_c.Call.Return(bytess, err)
	return _c
}

func (_c *MockIPFSPinService_ValidateDAGCompletion_Call) RunAndReturn(run func(ctx context.Context, pin *db.IPFSPin) ([][]byte, error)) *MockIPFSPinService_ValidateDAGCompletion_Call {
	_c.Call.Return(run)
	return _c
}
