// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
)

// NewMockBlockService creates a new instance of MockBlockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockService {
	mock := &MockBlockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockService is an autogenerated mock type for the BlockService type
type MockBlockService struct {
	mock.Mock
}

type MockBlockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockService) EXPECT() *MockBlockService_Expecter {
	return &MockBlockService_Expecter{mock: &_m.Mock}
}

// GetBlockMeta provides a mock function for the type MockBlockService
func (_mock *MockBlockService) GetBlockMeta(ctx context.Context, c cid.Cid) (*db.UnixFSNode, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockMeta")
	}

	var r0 *db.UnixFSNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (*db.UnixFSNode, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) *db.UnixFSNode); ok {
		r0 = returnFunc(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.UnixFSNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockService_GetBlockMeta_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockMeta'
type MockBlockService_GetBlockMeta_Call struct {
	*mock.Call
}

// GetBlockMeta is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockBlockService_Expecter) GetBlockMeta(ctx interface{}, c interface{}) *MockBlockService_GetBlockMeta_Call {
	return &MockBlockService_GetBlockMeta_Call{Call: _e.mock.On("GetBlockMeta", ctx, c)}
}

func (_c *MockBlockService_GetBlockMeta_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockBlockService_GetBlockMeta_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockService_GetBlockMeta_Call) Return(unixFSNode *db.UnixFSNode, err error) *MockBlockService_GetBlockMeta_Call {
	_c.Call.Return(unixFSNode, err)
	return _c
}

func (_c *MockBlockService_GetBlockMeta_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (*db.UnixFSNode, error)) *MockBlockService_GetBlockMeta_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockMetaBatch provides a mock function for the type MockBlockService
func (_mock *MockBlockService) GetBlockMetaBatch(ctx context.Context, cids []cid.Cid) (map[string]*db.UnixFSNode, error) {
	ret := _mock.Called(ctx, cids)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockMetaBatch")
	}

	var r0 map[string]*db.UnixFSNode
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid) (map[string]*db.UnixFSNode, error)); ok {
		return returnFunc(ctx, cids)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []cid.Cid) map[string]*db.UnixFSNode); ok {
		r0 = returnFunc(ctx, cids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*db.UnixFSNode)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []cid.Cid) error); ok {
		r1 = returnFunc(ctx, cids)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockService_GetBlockMetaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockMetaBatch'
type MockBlockService_GetBlockMetaBatch_Call struct {
	*mock.Call
}

// GetBlockMetaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - cids []cid.Cid
func (_e *MockBlockService_Expecter) GetBlockMetaBatch(ctx interface{}, cids interface{}) *MockBlockService_GetBlockMetaBatch_Call {
	return &MockBlockService_GetBlockMetaBatch_Call{Call: _e.mock.On("GetBlockMetaBatch", ctx, cids)}
}

func (_c *MockBlockService_GetBlockMetaBatch_Call) Run(run func(ctx context.Context, cids []cid.Cid)) *MockBlockService_GetBlockMetaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []cid.Cid
		if args[1] != nil {
			arg1 = args[1].([]cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBlockService_GetBlockMetaBatch_Call) Return(stringToUnixFSNode map[string]*db.UnixFSNode, err error) *MockBlockService_GetBlockMetaBatch_Call {
	_c.Call.Return(stringToUnixFSNode, err)
	return _c
}

func (_c *MockBlockService_GetBlockMetaBatch_Call) RunAndReturn(run func(ctx context.Context, cids []cid.Cid) (map[string]*db.UnixFSNode, error)) *MockBlockService_GetBlockMetaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockBlockService
func (_mock *MockBlockService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockBlockService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockBlockService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockBlockService_Expecter) ID() *MockBlockService_ID_Call {
	return &MockBlockService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockBlockService_ID_Call) Run(run func()) *MockBlockService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockService_ID_Call) Return(s string) *MockBlockService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockBlockService_ID_Call) RunAndReturn(run func() string) *MockBlockService_ID_Call {
	_c.Call.Return(run)
	return _c
}
