// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/multiformats/go-multihash"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProvider creates a new instance of MockProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProvider {
	mock := &MockProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProvider is an autogenerated mock type for the Provider type
type MockProvider struct {
	mock.Mock
}

type MockProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProvider) EXPECT() *MockProvider_Expecter {
	return &MockProvider_Expecter{mock: &_m.Mock}
}

// ProvideMany provides a mock function for the type MockProvider
func (_mock *MockProvider) ProvideMany(ctx context.Context, keys []multihash.Multihash) error {
	ret := _mock.Called(ctx, keys)

	if len(ret) == 0 {
		panic("no return value specified for ProvideMany")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []multihash.Multihash) error); ok {
		r0 = returnFunc(ctx, keys)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProvider_ProvideMany_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProvideMany'
type MockProvider_ProvideMany_Call struct {
	*mock.Call
}

// ProvideMany is a helper method to define mock.On call
//   - ctx context.Context
//   - keys []multihash.Multihash
func (_e *MockProvider_Expecter) ProvideMany(ctx interface{}, keys interface{}) *MockProvider_ProvideMany_Call {
	return &MockProvider_ProvideMany_Call{Call: _e.mock.On("ProvideMany", ctx, keys)}
}

func (_c *MockProvider_ProvideMany_Call) Run(run func(ctx context.Context, keys []multihash.Multihash)) *MockProvider_ProvideMany_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []multihash.Multihash
		if args[1] != nil {
			arg1 = args[1].([]multihash.Multihash)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProvider_ProvideMany_Call) Return(err error) *MockProvider_ProvideMany_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProvider_ProvideMany_Call) RunAndReturn(run func(ctx context.Context, keys []multihash.Multihash) error) *MockProvider_ProvideMany_Call {
	_c.Call.Return(run)
	return _c
}

// Ready provides a mock function for the type MockProvider
func (_mock *MockProvider) Ready() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Ready")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProvider_Ready_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ready'
type MockProvider_Ready_Call struct {
	*mock.Call
}

// Ready is a helper method to define mock.On call
func (_e *MockProvider_Expecter) Ready() *MockProvider_Ready_Call {
	return &MockProvider_Ready_Call{Call: _e.mock.On("Ready")}
}

func (_c *MockProvider_Ready_Call) Run(run func()) *MockProvider_Ready_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProvider_Ready_Call) Return(b bool) *MockProvider_Ready_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProvider_Ready_Call) RunAndReturn(run func() bool) *MockProvider_Ready_Call {
	_c.Call.Return(run)
	return _c
}
