// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/ipfs/boxo/blockstore"
	"github.com/ipfs/boxo/keystore"
	"github.com/ipfs/go-block-format"
	"github.com/ipfs/go-cid"
	"github.com/ipfs/go-datastore"
	"github.com/ipfs/go-ipld-format"
	"github.com/libp2p/go-libp2p/core/crypto"
	"github.com/libp2p/go-libp2p/core/peer"
	"github.com/multiformats/go-multiaddr"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/core"
)

// NewMockIPFSNode creates a new instance of MockIPFSNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPFSNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPFSNode {
	mock := &MockIPFSNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPFSNode is an autogenerated mock type for the IPFSNode type
type MockIPFSNode struct {
	mock.Mock
}

type MockIPFSNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPFSNode) EXPECT() *MockIPFSNode_Expecter {
	return &MockIPFSNode_Expecter{mock: &_m.Mock}
}

// AddBlock provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) AddBlock(ctx context.Context, block blocks.Block) error {
	ret := _mock.Called(ctx, block)

	if len(ret) == 0 {
		panic("no return value specified for AddBlock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, blocks.Block) error); ok {
		r0 = returnFunc(ctx, block)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSNode_AddBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlock'
type MockIPFSNode_AddBlock_Call struct {
	*mock.Call
}

// AddBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - block blocks.Block
func (_e *MockIPFSNode_Expecter) AddBlock(ctx interface{}, block interface{}) *MockIPFSNode_AddBlock_Call {
	return &MockIPFSNode_AddBlock_Call{Call: _e.mock.On("AddBlock", ctx, block)}
}

func (_c *MockIPFSNode_AddBlock_Call) Run(run func(ctx context.Context, block blocks.Block)) *MockIPFSNode_AddBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 blocks.Block
		if args[1] != nil {
			arg1 = args[1].(blocks.Block)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSNode_AddBlock_Call) Return(err error) *MockIPFSNode_AddBlock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSNode_AddBlock_Call) RunAndReturn(run func(ctx context.Context, block blocks.Block) error) *MockIPFSNode_AddBlock_Call {
	_c.Call.Return(run)
	return _c
}

// AddPeer provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) AddPeer(addr peer.AddrInfo) {
	_mock.Called(addr)
	return
}

// MockIPFSNode_AddPeer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPeer'
type MockIPFSNode_AddPeer_Call struct {
	*mock.Call
}

// AddPeer is a helper method to define mock.On call
//   - addr peer.AddrInfo
func (_e *MockIPFSNode_Expecter) AddPeer(addr interface{}) *MockIPFSNode_AddPeer_Call {
	return &MockIPFSNode_AddPeer_Call{Call: _e.mock.On("AddPeer", addr)}
}

func (_c *MockIPFSNode_AddPeer_Call) Run(run func(addr peer.AddrInfo)) *MockIPFSNode_AddPeer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 peer.AddrInfo
		if args[0] != nil {
			arg0 = args[0].(peer.AddrInfo)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockIPFSNode_AddPeer_Call) Return() *MockIPFSNode_AddPeer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPFSNode_AddPeer_Call) RunAndReturn(run func(addr peer.AddrInfo)) *MockIPFSNode_AddPeer_Call {
	_c.Run(run)
	return _c
}

// AnnounceDomain provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) AnnounceDomain() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AnnounceDomain")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIPFSNode_AnnounceDomain_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnounceDomain'
type MockIPFSNode_AnnounceDomain_Call struct {
	*mock.Call
}

// AnnounceDomain is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) AnnounceDomain() *MockIPFSNode_AnnounceDomain_Call {
	return &MockIPFSNode_AnnounceDomain_Call{Call: _e.mock.On("AnnounceDomain")}
}

func (_c *MockIPFSNode_AnnounceDomain_Call) Run(run func()) *MockIPFSNode_AnnounceDomain_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_AnnounceDomain_Call) Return(s string) *MockIPFSNode_AnnounceDomain_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIPFSNode_AnnounceDomain_Call) RunAndReturn(run func() string) *MockIPFSNode_AnnounceDomain_Call {
	_c.Call.Return(run)
	return _c
}

// AnnounceWeb provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) AnnounceWeb() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for AnnounceWeb")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockIPFSNode_AnnounceWeb_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AnnounceWeb'
type MockIPFSNode_AnnounceWeb_Call struct {
	*mock.Call
}

// AnnounceWeb is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) AnnounceWeb() *MockIPFSNode_AnnounceWeb_Call {
	return &MockIPFSNode_AnnounceWeb_Call{Call: _e.mock.On("AnnounceWeb")}
}

func (_c *MockIPFSNode_AnnounceWeb_Call) Run(run func()) *MockIPFSNode_AnnounceWeb_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_AnnounceWeb_Call) Return(b bool) *MockIPFSNode_AnnounceWeb_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockIPFSNode_AnnounceWeb_Call) RunAndReturn(run func() bool) *MockIPFSNode_AnnounceWeb_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSNode_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockIPFSNode_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) Close() *MockIPFSNode_Close_Call {
	return &MockIPFSNode_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockIPFSNode_Close_Call) Run(run func()) *MockIPFSNode_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_Close_Call) Return(err error) *MockIPFSNode_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSNode_Close_Call) RunAndReturn(run func() error) *MockIPFSNode_Close_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectionAddresses provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) ConnectionAddresses() ([]multiaddr.Multiaddr, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ConnectionAddresses")
	}

	var r0 []multiaddr.Multiaddr
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]multiaddr.Multiaddr, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []multiaddr.Multiaddr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]multiaddr.Multiaddr)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSNode_ConnectionAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectionAddresses'
type MockIPFSNode_ConnectionAddresses_Call struct {
	*mock.Call
}

// ConnectionAddresses is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) ConnectionAddresses() *MockIPFSNode_ConnectionAddresses_Call {
	return &MockIPFSNode_ConnectionAddresses_Call{Call: _e.mock.On("ConnectionAddresses")}
}

func (_c *MockIPFSNode_ConnectionAddresses_Call) Run(run func()) *MockIPFSNode_ConnectionAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_ConnectionAddresses_Call) Return(multiaddrs []multiaddr.Multiaddr, err error) *MockIPFSNode_ConnectionAddresses_Call {
	_c.Call.Return(multiaddrs, err)
	return _c
}

func (_c *MockIPFSNode_ConnectionAddresses_Call) RunAndReturn(run func() ([]multiaddr.Multiaddr, error)) *MockIPFSNode_ConnectionAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// DagService provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) DagService() format.DAGService {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DagService")
	}

	var r0 format.DAGService
	if returnFunc, ok := ret.Get(0).(func() format.DAGService); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(format.DAGService)
		}
	}
	return r0
}

// MockIPFSNode_DagService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DagService'
type MockIPFSNode_DagService_Call struct {
	*mock.Call
}

// DagService is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) DagService() *MockIPFSNode_DagService_Call {
	return &MockIPFSNode_DagService_Call{Call: _e.mock.On("DagService")}
}

func (_c *MockIPFSNode_DagService_Call) Run(run func()) *MockIPFSNode_DagService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_DagService_Call) Return(dAGService format.DAGService) *MockIPFSNode_DagService_Call {
	_c.Call.Return(dAGService)
	return _c
}

func (_c *MockIPFSNode_DagService_Call) RunAndReturn(run func() format.DAGService) *MockIPFSNode_DagService_Call {
	_c.Call.Return(run)
	return _c
}

// DelegateAddresses provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) DelegateAddresses() ([]multiaddr.Multiaddr, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DelegateAddresses")
	}

	var r0 []multiaddr.Multiaddr
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]multiaddr.Multiaddr, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []multiaddr.Multiaddr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]multiaddr.Multiaddr)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSNode_DelegateAddresses_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DelegateAddresses'
type MockIPFSNode_DelegateAddresses_Call struct {
	*mock.Call
}

// DelegateAddresses is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) DelegateAddresses() *MockIPFSNode_DelegateAddresses_Call {
	return &MockIPFSNode_DelegateAddresses_Call{Call: _e.mock.On("DelegateAddresses")}
}

func (_c *MockIPFSNode_DelegateAddresses_Call) Run(run func()) *MockIPFSNode_DelegateAddresses_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_DelegateAddresses_Call) Return(multiaddrs []multiaddr.Multiaddr, err error) *MockIPFSNode_DelegateAddresses_Call {
	_c.Call.Return(multiaddrs, err)
	return _c
}

func (_c *MockIPFSNode_DelegateAddresses_Call) RunAndReturn(run func() ([]multiaddr.Multiaddr, error)) *MockIPFSNode_DelegateAddresses_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlock provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) GetBlock(ctx context.Context, c cid.Cid) (format.Node, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for GetBlock")
	}

	var r0 format.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (format.Node, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) format.Node); ok {
		r0 = returnFunc(ctx, c)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(format.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSNode_GetBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlock'
type MockIPFSNode_GetBlock_Call struct {
	*mock.Call
}

// GetBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockIPFSNode_Expecter) GetBlock(ctx interface{}, c interface{}) *MockIPFSNode_GetBlock_Call {
	return &MockIPFSNode_GetBlock_Call{Call: _e.mock.On("GetBlock", ctx, c)}
}

func (_c *MockIPFSNode_GetBlock_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockIPFSNode_GetBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSNode_GetBlock_Call) Return(node format.Node, err error) *MockIPFSNode_GetBlock_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *MockIPFSNode_GetBlock_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (format.Node, error)) *MockIPFSNode_GetBlock_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockstore provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) GetBlockstore() blockstore.Blockstore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetBlockstore")
	}

	var r0 blockstore.Blockstore
	if returnFunc, ok := ret.Get(0).(func() blockstore.Blockstore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blockstore.Blockstore)
		}
	}
	return r0
}

// MockIPFSNode_GetBlockstore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockstore'
type MockIPFSNode_GetBlockstore_Call struct {
	*mock.Call
}

// GetBlockstore is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) GetBlockstore() *MockIPFSNode_GetBlockstore_Call {
	return &MockIPFSNode_GetBlockstore_Call{Call: _e.mock.On("GetBlockstore")}
}

func (_c *MockIPFSNode_GetBlockstore_Call) Run(run func()) *MockIPFSNode_GetBlockstore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_GetBlockstore_Call) Return(blockstore1 blockstore.Blockstore) *MockIPFSNode_GetBlockstore_Call {
	_c.Call.Return(blockstore1)
	return _c
}

func (_c *MockIPFSNode_GetBlockstore_Call) RunAndReturn(run func() blockstore.Blockstore) *MockIPFSNode_GetBlockstore_Call {
	_c.Call.Return(run)
	return _c
}

// GetDatastore provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) GetDatastore() datastore.Datastore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDatastore")
	}

	var r0 datastore.Datastore
	if returnFunc, ok := ret.Get(0).(func() datastore.Datastore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(datastore.Datastore)
		}
	}
	return r0
}

// MockIPFSNode_GetDatastore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDatastore'
type MockIPFSNode_GetDatastore_Call struct {
	*mock.Call
}

// GetDatastore is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) GetDatastore() *MockIPFSNode_GetDatastore_Call {
	return &MockIPFSNode_GetDatastore_Call{Call: _e.mock.On("GetDatastore")}
}

func (_c *MockIPFSNode_GetDatastore_Call) Run(run func()) *MockIPFSNode_GetDatastore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_GetDatastore_Call) Return(datastore1 datastore.Datastore) *MockIPFSNode_GetDatastore_Call {
	_c.Call.Return(datastore1)
	return _c
}

func (_c *MockIPFSNode_GetDatastore_Call) RunAndReturn(run func() datastore.Datastore) *MockIPFSNode_GetDatastore_Call {
	_c.Call.Return(run)
	return _c
}

// GetKeystore provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) GetKeystore() keystore.Keystore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetKeystore")
	}

	var r0 keystore.Keystore
	if returnFunc, ok := ret.Get(0).(func() keystore.Keystore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keystore.Keystore)
		}
	}
	return r0
}

// MockIPFSNode_GetKeystore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetKeystore'
type MockIPFSNode_GetKeystore_Call struct {
	*mock.Call
}

// GetKeystore is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) GetKeystore() *MockIPFSNode_GetKeystore_Call {
	return &MockIPFSNode_GetKeystore_Call{Call: _e.mock.On("GetKeystore")}
}

func (_c *MockIPFSNode_GetKeystore_Call) Run(run func()) *MockIPFSNode_GetKeystore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_GetKeystore_Call) Return(keystore1 keystore.Keystore) *MockIPFSNode_GetKeystore_Call {
	_c.Call.Return(keystore1)
	return _c
}

func (_c *MockIPFSNode_GetKeystore_Call) RunAndReturn(run func() keystore.Keystore) *MockIPFSNode_GetKeystore_Call {
	_c.Call.Return(run)
	return _c
}

// GetPrivateKey provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) GetPrivateKey() crypto.PrivKey {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPrivateKey")
	}

	var r0 crypto.PrivKey
	if returnFunc, ok := ret.Get(0).(func() crypto.PrivKey); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(crypto.PrivKey)
		}
	}
	return r0
}

// MockIPFSNode_GetPrivateKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPrivateKey'
type MockIPFSNode_GetPrivateKey_Call struct {
	*mock.Call
}

// GetPrivateKey is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) GetPrivateKey() *MockIPFSNode_GetPrivateKey_Call {
	return &MockIPFSNode_GetPrivateKey_Call{Call: _e.mock.On("GetPrivateKey")}
}

func (_c *MockIPFSNode_GetPrivateKey_Call) Run(run func()) *MockIPFSNode_GetPrivateKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_GetPrivateKey_Call) Return(privKey crypto.PrivKey) *MockIPFSNode_GetPrivateKey_Call {
	_c.Call.Return(privKey)
	return _c
}

func (_c *MockIPFSNode_GetPrivateKey_Call) RunAndReturn(run func() crypto.PrivKey) *MockIPFSNode_GetPrivateKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetPublisher provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) GetPublisher() core.IPNSPublisher {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPublisher")
	}

	var r0 core.IPNSPublisher
	if returnFunc, ok := ret.Get(0).(func() core.IPNSPublisher); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.IPNSPublisher)
		}
	}
	return r0
}

// MockIPFSNode_GetPublisher_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPublisher'
type MockIPFSNode_GetPublisher_Call struct {
	*mock.Call
}

// GetPublisher is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) GetPublisher() *MockIPFSNode_GetPublisher_Call {
	return &MockIPFSNode_GetPublisher_Call{Call: _e.mock.On("GetPublisher")}
}

func (_c *MockIPFSNode_GetPublisher_Call) Run(run func()) *MockIPFSNode_GetPublisher_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_GetPublisher_Call) Return(iPNSPublisher core.IPNSPublisher) *MockIPFSNode_GetPublisher_Call {
	_c.Call.Return(iPNSPublisher)
	return _c
}

func (_c *MockIPFSNode_GetPublisher_Call) RunAndReturn(run func() core.IPNSPublisher) *MockIPFSNode_GetPublisher_Call {
	_c.Call.Return(run)
	return _c
}

// HasBlock provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) HasBlock(ctx context.Context, c cid.Cid) (bool, error) {
	ret := _mock.Called(ctx, c)

	if len(ret) == 0 {
		panic("no return value specified for HasBlock")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) (bool, error)); ok {
		return returnFunc(ctx, c)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid) bool); ok {
		r0 = returnFunc(ctx, c)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, cid.Cid) error); ok {
		r1 = returnFunc(ctx, c)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSNode_HasBlock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasBlock'
type MockIPFSNode_HasBlock_Call struct {
	*mock.Call
}

// HasBlock is a helper method to define mock.On call
//   - ctx context.Context
//   - c cid.Cid
func (_e *MockIPFSNode_Expecter) HasBlock(ctx interface{}, c interface{}) *MockIPFSNode_HasBlock_Call {
	return &MockIPFSNode_HasBlock_Call{Call: _e.mock.On("HasBlock", ctx, c)}
}

func (_c *MockIPFSNode_HasBlock_Call) Run(run func(ctx context.Context, c cid.Cid)) *MockIPFSNode_HasBlock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSNode_HasBlock_Call) Return(b bool, err error) *MockIPFSNode_HasBlock_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockIPFSNode_HasBlock_Call) RunAndReturn(run func(ctx context.Context, c cid.Cid) (bool, error)) *MockIPFSNode_HasBlock_Call {
	_c.Call.Return(run)
	return _c
}

// HostAddrs provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) HostAddrs() []multiaddr.Multiaddr {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HostAddrs")
	}

	var r0 []multiaddr.Multiaddr
	if returnFunc, ok := ret.Get(0).(func() []multiaddr.Multiaddr); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]multiaddr.Multiaddr)
		}
	}
	return r0
}

// MockIPFSNode_HostAddrs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HostAddrs'
type MockIPFSNode_HostAddrs_Call struct {
	*mock.Call
}

// HostAddrs is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) HostAddrs() *MockIPFSNode_HostAddrs_Call {
	return &MockIPFSNode_HostAddrs_Call{Call: _e.mock.On("HostAddrs")}
}

func (_c *MockIPFSNode_HostAddrs_Call) Run(run func()) *MockIPFSNode_HostAddrs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_HostAddrs_Call) Return(multiaddrs []multiaddr.Multiaddr) *MockIPFSNode_HostAddrs_Call {
	_c.Call.Return(multiaddrs)
	return _c
}

func (_c *MockIPFSNode_HostAddrs_Call) RunAndReturn(run func() []multiaddr.Multiaddr) *MockIPFSNode_HostAddrs_Call {
	_c.Call.Return(run)
	return _c
}

// PeerID provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) PeerID() peer.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PeerID")
	}

	var r0 peer.ID
	if returnFunc, ok := ret.Get(0).(func() peer.ID); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(peer.ID)
	}
	return r0
}

// MockIPFSNode_PeerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PeerID'
type MockIPFSNode_PeerID_Call struct {
	*mock.Call
}

// PeerID is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) PeerID() *MockIPFSNode_PeerID_Call {
	return &MockIPFSNode_PeerID_Call{Call: _e.mock.On("PeerID")}
}

func (_c *MockIPFSNode_PeerID_Call) Run(run func()) *MockIPFSNode_PeerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_PeerID_Call) Return(iD peer.ID) *MockIPFSNode_PeerID_Call {
	_c.Call.Return(iD)
	return _c
}

func (_c *MockIPFSNode_PeerID_Call) RunAndReturn(run func() peer.ID) *MockIPFSNode_PeerID_Call {
	_c.Call.Return(run)
	return _c
}

// Peers provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) Peers() []peer.ID {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Peers")
	}

	var r0 []peer.ID
	if returnFunc, ok := ret.Get(0).(func() []peer.ID); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]peer.ID)
		}
	}
	return r0
}

// MockIPFSNode_Peers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Peers'
type MockIPFSNode_Peers_Call struct {
	*mock.Call
}

// Peers is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) Peers() *MockIPFSNode_Peers_Call {
	return &MockIPFSNode_Peers_Call{Call: _e.mock.On("Peers")}
}

func (_c *MockIPFSNode_Peers_Call) Run(run func()) *MockIPFSNode_Peers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_Peers_Call) Return(iDs []peer.ID) *MockIPFSNode_Peers_Call {
	_c.Call.Return(iDs)
	return _c
}

func (_c *MockIPFSNode_Peers_Call) RunAndReturn(run func() []peer.ID) *MockIPFSNode_Peers_Call {
	_c.Call.Return(run)
	return _c
}

// Pin provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) Pin(ctx context.Context, root cid.Cid, recursive bool) error {
	ret := _mock.Called(ctx, root, recursive)

	if len(ret) == 0 {
		panic("no return value specified for Pin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, cid.Cid, bool) error); ok {
		r0 = returnFunc(ctx, root, recursive)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSNode_Pin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Pin'
type MockIPFSNode_Pin_Call struct {
	*mock.Call
}

// Pin is a helper method to define mock.On call
//   - ctx context.Context
//   - root cid.Cid
//   - recursive bool
func (_e *MockIPFSNode_Expecter) Pin(ctx interface{}, root interface{}, recursive interface{}) *MockIPFSNode_Pin_Call {
	return &MockIPFSNode_Pin_Call{Call: _e.mock.On("Pin", ctx, root, recursive)}
}

func (_c *MockIPFSNode_Pin_Call) Run(run func(ctx context.Context, root cid.Cid, recursive bool)) *MockIPFSNode_Pin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 cid.Cid
		if args[1] != nil {
			arg1 = args[1].(cid.Cid)
		}
		var arg2 bool
		if args[2] != nil {
			arg2 = args[2].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIPFSNode_Pin_Call) Return(err error) *MockIPFSNode_Pin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSNode_Pin_Call) RunAndReturn(run func(ctx context.Context, root cid.Cid, recursive bool) error) *MockIPFSNode_Pin_Call {
	_c.Call.Return(run)
	return _c
}

// Port provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) Port() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Port")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockIPFSNode_Port_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Port'
type MockIPFSNode_Port_Call struct {
	*mock.Call
}

// Port is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) Port() *MockIPFSNode_Port_Call {
	return &MockIPFSNode_Port_Call{Call: _e.mock.On("Port")}
}

func (_c *MockIPFSNode_Port_Call) Run(run func()) *MockIPFSNode_Port_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_Port_Call) Return(n int) *MockIPFSNode_Port_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockIPFSNode_Port_Call) RunAndReturn(run func() int) *MockIPFSNode_Port_Call {
	_c.Call.Return(run)
	return _c
}

// TriggerReprovider provides a mock function for the type MockIPFSNode
func (_mock *MockIPFSNode) TriggerReprovider() {
	_mock.Called()
	return
}

// MockIPFSNode_TriggerReprovider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TriggerReprovider'
type MockIPFSNode_TriggerReprovider_Call struct {
	*mock.Call
}

// TriggerReprovider is a helper method to define mock.On call
func (_e *MockIPFSNode_Expecter) TriggerReprovider() *MockIPFSNode_TriggerReprovider_Call {
	return &MockIPFSNode_TriggerReprovider_Call{Call: _e.mock.On("TriggerReprovider")}
}

func (_c *MockIPFSNode_TriggerReprovider_Call) Run(run func()) *MockIPFSNode_TriggerReprovider_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSNode_TriggerReprovider_Call) Return() *MockIPFSNode_TriggerReprovider_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockIPFSNode_TriggerReprovider_Call) RunAndReturn(run func()) *MockIPFSNode_TriggerReprovider_Call {
	_c.Run(run)
	return _c
}
