// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"net"

	mock "github.com/stretchr/testify/mock"
)

// NewMockDNSLookup creates a new instance of MockDNSLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDNSLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDNSLookup {
	mock := &MockDNSLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDNSLookup is an autogenerated mock type for the DNSLookup type
type MockDNSLookup struct {
	mock.Mock
}

type MockDNSLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDNSLookup) EXPECT() *MockDNSLookup_Expecter {
	return &MockDNSLookup_Expecter{mock: &_m.Mock}
}

// LookupNS provides a mock function for the type MockDNSLookup
func (_mock *MockDNSLookup) LookupNS(domain string) ([]*net.NS, error) {
	ret := _mock.Called(domain)

	if len(ret) == 0 {
		panic("no return value specified for LookupNS")
	}

	var r0 []*net.NS
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]*net.NS, error)); ok {
		return returnFunc(domain)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []*net.NS); ok {
		r0 = returnFunc(domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*net.NS)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(domain)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDNSLookup_LookupNS_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookupNS'
type MockDNSLookup_LookupNS_Call struct {
	*mock.Call
}

// LookupNS is a helper method to define mock.On call
//   - domain string
func (_e *MockDNSLookup_Expecter) LookupNS(domain any) *MockDNSLookup_LookupNS_Call {
	return &MockDNSLookup_LookupNS_Call{Call: _e.mock.On("LookupNS", domain)}
}

func (_c *MockDNSLookup_LookupNS_Call) Run(run func(domain string)) *MockDNSLookup_LookupNS_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockDNSLookup_LookupNS_Call) Return(nSs []*net.NS, err error) *MockDNSLookup_LookupNS_Call {
	_c.Call.Return(nSs, err)
	return _c
}

func (_c *MockDNSLookup_LookupNS_Call) RunAndReturn(run func(domain string) ([]*net.NS, error)) *MockDNSLookup_LookupNS_Call {
	_c.Call.Return(run)
	return _c
}
