// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal/db/types"
	"go.lumeweb.com/queryutil"
	"go.lumeweb.com/queryutil/filter"
	"gorm.io/datatypes"
)

// NewMockIPFSPinService creates a new instance of MockIPFSPinService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIPFSPinService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIPFSPinService {
	mock := &MockIPFSPinService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIPFSPinService is an autogenerated mock type for the IPFSPinService type
type MockIPFSPinService struct {
	mock.Mock
}

type MockIPFSPinService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIPFSPinService) EXPECT() *MockIPFSPinService_Expecter {
	return &MockIPFSPinService_Expecter{mock: &_m.Mock}
}

// AddPin provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) AddPin(ctx context.Context, pin *db.IPFSPin) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, pin)

	if len(ret) == 0 {
		panic("no return value specified for AddPin")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.IPFSPin) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, pin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, *db.IPFSPin) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, pin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, *db.IPFSPin) error); ok {
		r1 = returnFunc(ctx, pin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_AddPin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddPin'
type MockIPFSPinService_AddPin_Call struct {
	*mock.Call
}

// AddPin is a helper method to define mock.On call
//   - ctx context.Context
//   - pin *db.IPFSPin
func (_e *MockIPFSPinService_Expecter) AddPin(ctx interface{}, pin interface{}) *MockIPFSPinService_AddPin_Call {
	return &MockIPFSPinService_AddPin_Call{Call: _e.mock.On("AddPin", ctx, pin)}
}

func (_c *MockIPFSPinService_AddPin_Call) Run(run func(ctx context.Context, pin *db.IPFSPin)) *MockIPFSPinService_AddPin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *db.IPFSPin
		if args[1] != nil {
			arg1 = args[1].(*db.IPFSPin)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_AddPin_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_AddPin_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_AddPin_Call) RunAndReturn(run func(ctx context.Context, pin *db.IPFSPin) (*db.IPFSPin, error)) *MockIPFSPinService_AddPin_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePin provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) DeletePin(ctx context.Context, requestID types.BinaryUUID) error {
	ret := _mock.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for DeletePin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID) error); ok {
		r0 = returnFunc(ctx, requestID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSPinService_DeletePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePin'
type MockIPFSPinService_DeletePin_Call struct {
	*mock.Call
}

// DeletePin is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID types.BinaryUUID
func (_e *MockIPFSPinService_Expecter) DeletePin(ctx interface{}, requestID interface{}) *MockIPFSPinService_DeletePin_Call {
	return &MockIPFSPinService_DeletePin_Call{Call: _e.mock.On("DeletePin", ctx, requestID)}
}

func (_c *MockIPFSPinService_DeletePin_Call) Run(run func(ctx context.Context, requestID types.BinaryUUID)) *MockIPFSPinService_DeletePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(types.BinaryUUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_DeletePin_Call) Return(err error) *MockIPFSPinService_DeletePin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSPinService_DeletePin_Call) RunAndReturn(run func(ctx context.Context, requestID types.BinaryUUID) error) *MockIPFSPinService_DeletePin_Call {
	_c.Call.Return(run)
	return _c
}

// GetPinByRequestID provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) GetPinByRequestID(ctx context.Context, requestID types.BinaryUUID) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, requestID)

	if len(ret) == 0 {
		panic("no return value specified for GetPinByRequestID")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, requestID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, requestID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, types.BinaryUUID) error); ok {
		r1 = returnFunc(ctx, requestID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_GetPinByRequestID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPinByRequestID'
type MockIPFSPinService_GetPinByRequestID_Call struct {
	*mock.Call
}

// GetPinByRequestID is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID types.BinaryUUID
func (_e *MockIPFSPinService_Expecter) GetPinByRequestID(ctx interface{}, requestID interface{}) *MockIPFSPinService_GetPinByRequestID_Call {
	return &MockIPFSPinService_GetPinByRequestID_Call{Call: _e.mock.On("GetPinByRequestID", ctx, requestID)}
}

func (_c *MockIPFSPinService_GetPinByRequestID_Call) Run(run func(ctx context.Context, requestID types.BinaryUUID)) *MockIPFSPinService_GetPinByRequestID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(types.BinaryUUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_GetPinByRequestID_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_GetPinByRequestID_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_GetPinByRequestID_Call) RunAndReturn(run func(ctx context.Context, requestID types.BinaryUUID) (*db.IPFSPin, error)) *MockIPFSPinService_GetPinByRequestID_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIPFSPinService_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockIPFSPinService_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockIPFSPinService_Expecter) ID() *MockIPFSPinService_ID_Call {
	return &MockIPFSPinService_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockIPFSPinService_ID_Call) Run(run func()) *MockIPFSPinService_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIPFSPinService_ID_Call) Return(s string) *MockIPFSPinService_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIPFSPinService_ID_Call) RunAndReturn(run func() string) *MockIPFSPinService_ID_Call {
	_c.Call.Return(run)
	return _c
}

// ListPins provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ListPins(ctx context.Context, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.IPFSPin, int64, error) {
	ret := _mock.Called(ctx, filter1, sort, pagination)

	if len(ret) == 0 {
		panic("no return value specified for ListPins")
	}

	var r0 []*db.IPFSPin
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) ([]*db.IPFSPin, int64, error)); ok {
		return returnFunc(ctx, filter1, sort, pagination)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) []*db.IPFSPin); ok {
		r0 = returnFunc(ctx, filter1, sort, pagination)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) int64); ok {
		r1 = returnFunc(ctx, filter1, sort, pagination)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, []queryutil.CrudFilter, []filter.Sort, queryutil.Pagination) error); ok {
		r2 = returnFunc(ctx, filter1, sort, pagination)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockIPFSPinService_ListPins_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPins'
type MockIPFSPinService_ListPins_Call struct {
	*mock.Call
}

// ListPins is a helper method to define mock.On call
//   - ctx context.Context
//   - filter1 []queryutil.CrudFilter
//   - sort []filter.Sort
//   - pagination queryutil.Pagination
func (_e *MockIPFSPinService_Expecter) ListPins(ctx interface{}, filter1 interface{}, sort interface{}, pagination interface{}) *MockIPFSPinService_ListPins_Call {
	return &MockIPFSPinService_ListPins_Call{Call: _e.mock.On("ListPins", ctx, filter1, sort, pagination)}
}

func (_c *MockIPFSPinService_ListPins_Call) Run(run func(ctx context.Context, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination)) *MockIPFSPinService_ListPins_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []queryutil.CrudFilter
		if args[1] != nil {
			arg1 = args[1].([]queryutil.CrudFilter)
		}
		var arg2 []filter.Sort
		if args[2] != nil {
			arg2 = args[2].([]filter.Sort)
		}
		var arg3 queryutil.Pagination
		if args[3] != nil {
			arg3 = args[3].(queryutil.Pagination)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ListPins_Call) Return(iPFSPins []*db.IPFSPin, n int64, err error) *MockIPFSPinService_ListPins_Call {
	_c.Call.Return(iPFSPins, n, err)
	return _c
}

func (_c *MockIPFSPinService_ListPins_Call) RunAndReturn(run func(ctx context.Context, filter1 []queryutil.CrudFilter, sort []filter.Sort, pagination queryutil.Pagination) ([]*db.IPFSPin, int64, error)) *MockIPFSPinService_ListPins_Call {
	_c.Call.Return(run)
	return _c
}

// ReplacePin provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) ReplacePin(ctx context.Context, userId uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin) (*db.IPFSPin, error) {
	ret := _mock.Called(ctx, userId, userIp, oldRequestID, newPin)

	if len(ret) == 0 {
		panic("no return value specified for ReplacePin")
	}

	var r0 *db.IPFSPin
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) (*db.IPFSPin, error)); ok {
		return returnFunc(ctx, userId, userIp, oldRequestID, newPin)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) *db.IPFSPin); ok {
		r0 = returnFunc(ctx, userId, userIp, oldRequestID, newPin)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*db.IPFSPin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uint, string, types.BinaryUUID, *db.IPFSPin) error); ok {
		r1 = returnFunc(ctx, userId, userIp, oldRequestID, newPin)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockIPFSPinService_ReplacePin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReplacePin'
type MockIPFSPinService_ReplacePin_Call struct {
	*mock.Call
}

// ReplacePin is a helper method to define mock.On call
//   - ctx context.Context
//   - userId uint
//   - userIp string
//   - oldRequestID types.BinaryUUID
//   - newPin *db.IPFSPin
func (_e *MockIPFSPinService_Expecter) ReplacePin(ctx interface{}, userId interface{}, userIp interface{}, oldRequestID interface{}, newPin interface{}) *MockIPFSPinService_ReplacePin_Call {
	return &MockIPFSPinService_ReplacePin_Call{Call: _e.mock.On("ReplacePin", ctx, userId, userIp, oldRequestID, newPin)}
}

func (_c *MockIPFSPinService_ReplacePin_Call) Run(run func(ctx context.Context, userId uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin)) *MockIPFSPinService_ReplacePin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uint
		if args[1] != nil {
			arg1 = args[1].(uint)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 types.BinaryUUID
		if args[3] != nil {
			arg3 = args[3].(types.BinaryUUID)
		}
		var arg4 *db.IPFSPin
		if args[4] != nil {
			arg4 = args[4].(*db.IPFSPin)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_ReplacePin_Call) Return(iPFSPin *db.IPFSPin, err error) *MockIPFSPinService_ReplacePin_Call {
	_c.Call.Return(iPFSPin, err)
	return _c
}

func (_c *MockIPFSPinService_ReplacePin_Call) RunAndReturn(run func(ctx context.Context, userId uint, userIp string, oldRequestID types.BinaryUUID, newPin *db.IPFSPin) (*db.IPFSPin, error)) *MockIPFSPinService_ReplacePin_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePinStatus provides a mock function for the type MockIPFSPinService
func (_mock *MockIPFSPinService) UpdatePinStatus(ctx context.Context, requestID types.BinaryUUID, status db.PinningStatus, info datatypes.JSON) error {
	ret := _mock.Called(ctx, requestID, status, info)

	if len(ret) == 0 {
		panic("no return value specified for UpdatePinStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, types.BinaryUUID, db.PinningStatus, datatypes.JSON) error); ok {
		r0 = returnFunc(ctx, requestID, status, info)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockIPFSPinService_UpdatePinStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePinStatus'
type MockIPFSPinService_UpdatePinStatus_Call struct {
	*mock.Call
}

// UpdatePinStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - requestID types.BinaryUUID
//   - status db.PinningStatus
//   - info datatypes.JSON
func (_e *MockIPFSPinService_Expecter) UpdatePinStatus(ctx interface{}, requestID interface{}, status interface{}, info interface{}) *MockIPFSPinService_UpdatePinStatus_Call {
	return &MockIPFSPinService_UpdatePinStatus_Call{Call: _e.mock.On("UpdatePinStatus", ctx, requestID, status, info)}
}

func (_c *MockIPFSPinService_UpdatePinStatus_Call) Run(run func(ctx context.Context, requestID types.BinaryUUID, status db.PinningStatus, info datatypes.JSON)) *MockIPFSPinService_UpdatePinStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 types.BinaryUUID
		if args[1] != nil {
			arg1 = args[1].(types.BinaryUUID)
		}
		var arg2 db.PinningStatus
		if args[2] != nil {
			arg2 = args[2].(db.PinningStatus)
		}
		var arg3 datatypes.JSON
		if args[3] != nil {
			arg3 = args[3].(datatypes.JSON)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockIPFSPinService_UpdatePinStatus_Call) Return(err error) *MockIPFSPinService_UpdatePinStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockIPFSPinService_UpdatePinStatus_Call) RunAndReturn(run func(ctx context.Context, requestID types.BinaryUUID, status db.PinningStatus, info datatypes.JSON) error) *MockIPFSPinService_UpdatePinStatus_Call {
	_c.Call.Return(run)
	return _c
}
