template: testify
template-data:
  unroll-variadic: true
filename: "Mock{{.InterfaceName}}.go"
pkgname: "mocks"
dir: ./internal/testing/mocks
packages:
  go.lumeweb.com/portal-plugin-ipfs/core:
    interfaces:
      Provider: {}
      ReprovideStore: {}
      MetadataStore: {}
      BlockDownloader: {}
      IPFSPinService: {}
      UploadService: {}
      BlockService: {}
      FileManagerService: {}
  go.lumeweb.com/portal-plugin-ipfs/internal/protocol:
    interfaces:
      ProtoNode: {}
  go.lumeweb.com/portal-plugin-ipfs/internal/protocol/ipfs:
    interfaces:
      IPFSNode: {}
  go.lumeweb.com/portal-plugin-ipfs/internal/protocol/store:
    interfaces:
      MockBlockstore: {}
      MockDatastore: {}
  go.lumeweb.com/portal-plugin-ipfs/internal/upload:
    config:
      pkgname: "{{.SrcPackageName}}"
      dir: "{{.InterfaceDir}}"
    interfaces:
      ArchiveExtractor: {}
      StreamingArchiveProcessor: {}