// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protocoltestmocks

import (
	"github.com/ipfs/go-block-format"
	"github.com/ipfs/go-cid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBlockProcessor creates a new instance of MockBlockProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBlockProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBlockProcessor {
	mock := &MockBlockProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBlockProcessor is an autogenerated mock type for the BlockProcessor type
type MockBlockProcessor struct {
	mock.Mock
}

type MockBlockProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBlockProcessor) EXPECT() *MockBlockProcessor_Expecter {
	return &MockBlockProcessor_Expecter{mock: &_m.Mock}
}

// Done provides a mock function for the type MockBlockProcessor
func (_mock *MockBlockProcessor) Done(cid1 cid.Cid) {
	_mock.Called(cid1)
	return
}

// MockBlockProcessor_Done_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Done'
type MockBlockProcessor_Done_Call struct {
	*mock.Call
}

// Done is a helper method to define mock.On call
//   - cid1 cid.Cid
func (_e *MockBlockProcessor_Expecter) Done(cid1 any) *MockBlockProcessor_Done_Call {
	return &MockBlockProcessor_Done_Call{Call: _e.mock.On("Done", cid1)}
}

func (_c *MockBlockProcessor_Done_Call) Run(run func(cid1 cid.Cid)) *MockBlockProcessor_Done_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 cid.Cid
		if args[0] != nil {
			arg0 = args[0].(cid.Cid)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBlockProcessor_Done_Call) Return() *MockBlockProcessor_Done_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockProcessor_Done_Call) RunAndReturn(run func(cid1 cid.Cid)) *MockBlockProcessor_Done_Call {
	_c.Run(run)
	return _c
}

// GetDoneCIDs provides a mock function for the type MockBlockProcessor
func (_mock *MockBlockProcessor) GetDoneCIDs() []cid.Cid {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDoneCIDs")
	}

	var r0 []cid.Cid
	if returnFunc, ok := ret.Get(0).(func() []cid.Cid); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	return r0
}

// MockBlockProcessor_GetDoneCIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDoneCIDs'
type MockBlockProcessor_GetDoneCIDs_Call struct {
	*mock.Call
}

// GetDoneCIDs is a helper method to define mock.On call
func (_e *MockBlockProcessor_Expecter) GetDoneCIDs() *MockBlockProcessor_GetDoneCIDs_Call {
	return &MockBlockProcessor_GetDoneCIDs_Call{Call: _e.mock.On("GetDoneCIDs")}
}

func (_c *MockBlockProcessor_GetDoneCIDs_Call) Run(run func()) *MockBlockProcessor_GetDoneCIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockProcessor_GetDoneCIDs_Call) Return(cids []cid.Cid) *MockBlockProcessor_GetDoneCIDs_Call {
	_c.Call.Return(cids)
	return _c
}

func (_c *MockBlockProcessor_GetDoneCIDs_Call) RunAndReturn(run func() []cid.Cid) *MockBlockProcessor_GetDoneCIDs_Call {
	_c.Call.Return(run)
	return _c
}

// Next provides a mock function for the type MockBlockProcessor
func (_mock *MockBlockProcessor) Next() (blocks.Block, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Next")
	}

	var r0 blocks.Block
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (blocks.Block, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() blocks.Block); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(blocks.Block)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockBlockProcessor_Next_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Next'
type MockBlockProcessor_Next_Call struct {
	*mock.Call
}

// Next is a helper method to define mock.On call
func (_e *MockBlockProcessor_Expecter) Next() *MockBlockProcessor_Next_Call {
	return &MockBlockProcessor_Next_Call{Call: _e.mock.On("Next")}
}

func (_c *MockBlockProcessor_Next_Call) Run(run func()) *MockBlockProcessor_Next_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockProcessor_Next_Call) Return(block blocks.Block, err error) *MockBlockProcessor_Next_Call {
	_c.Call.Return(block, err)
	return _c
}

func (_c *MockBlockProcessor_Next_Call) RunAndReturn(run func() (blocks.Block, error)) *MockBlockProcessor_Next_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type MockBlockProcessor
func (_mock *MockBlockProcessor) Release() {
	_mock.Called()
	return
}

// MockBlockProcessor_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type MockBlockProcessor_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *MockBlockProcessor_Expecter) Release() *MockBlockProcessor_Release_Call {
	return &MockBlockProcessor_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *MockBlockProcessor_Release_Call) Run(run func()) *MockBlockProcessor_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockProcessor_Release_Call) Return() *MockBlockProcessor_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockBlockProcessor_Release_Call) RunAndReturn(run func()) *MockBlockProcessor_Release_Call {
	_c.Run(run)
	return _c
}

// Roots provides a mock function for the type MockBlockProcessor
func (_mock *MockBlockProcessor) Roots() []cid.Cid {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Roots")
	}

	var r0 []cid.Cid
	if returnFunc, ok := ret.Get(0).(func() []cid.Cid); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]cid.Cid)
		}
	}
	return r0
}

// MockBlockProcessor_Roots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Roots'
type MockBlockProcessor_Roots_Call struct {
	*mock.Call
}

// Roots is a helper method to define mock.On call
func (_e *MockBlockProcessor_Expecter) Roots() *MockBlockProcessor_Roots_Call {
	return &MockBlockProcessor_Roots_Call{Call: _e.mock.On("Roots")}
}

func (_c *MockBlockProcessor_Roots_Call) Run(run func()) *MockBlockProcessor_Roots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockBlockProcessor_Roots_Call) Return(cids []cid.Cid) *MockBlockProcessor_Roots_Call {
	_c.Call.Return(cids)
	return _c
}

func (_c *MockBlockProcessor_Roots_Call) RunAndReturn(run func() []cid.Cid) *MockBlockProcessor_Roots_Call {
	_c.Call.Return(run)
	return _c
}
