// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package protocoltestmocks

import (
	"io"

	mock "github.com/stretchr/testify/mock"
	core0 "go.lumeweb.com/portal-plugin-ipfs/core"
	"go.lumeweb.com/portal-plugin-ipfs/internal/protocol/ipfs"
	"go.lumeweb.com/portal/config"
	"go.lumeweb.com/portal/core"
	"gorm.io/gorm"
)

// NewMockProtoNode creates a new instance of MockProtoNode. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtoNode(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtoNode {
	mock := &MockProtoNode{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtoNode is an autogenerated mock type for the ProtoNode type
type MockProtoNode struct {
	mock.Mock
}

type MockProtoNode_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtoNode) EXPECT() *MockProtoNode_Expecter {
	return &MockProtoNode_Expecter{mock: &_m.Mock}
}

// Config provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Config() config.Manager {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Config")
	}

	var r0 config.Manager
	if returnFunc, ok := ret.Get(0).(func() config.Manager); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.Manager)
		}
	}
	return r0
}

// MockProtoNode_Config_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Config'
type MockProtoNode_Config_Call struct {
	*mock.Call
}

// Config is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) Config() *MockProtoNode_Config_Call {
	return &MockProtoNode_Config_Call{Call: _e.mock.On("Config")}
}

func (_c *MockProtoNode_Config_Call) Run(run func()) *MockProtoNode_Config_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_Config_Call) Return(manager config.Manager) *MockProtoNode_Config_Call {
	_c.Call.Return(manager)
	return _c
}

func (_c *MockProtoNode_Config_Call) RunAndReturn(run func() config.Manager) *MockProtoNode_Config_Call {
	_c.Call.Return(run)
	return _c
}

// Context provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Context() core.Context {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Context")
	}

	var r0 core.Context
	if returnFunc, ok := ret.Get(0).(func() core.Context); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.Context)
		}
	}
	return r0
}

// MockProtoNode_Context_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Context'
type MockProtoNode_Context_Call struct {
	*mock.Call
}

// Context is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) Context() *MockProtoNode_Context_Call {
	return &MockProtoNode_Context_Call{Call: _e.mock.On("Context")}
}

func (_c *MockProtoNode_Context_Call) Run(run func()) *MockProtoNode_Context_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_Context_Call) Return(context core.Context) *MockProtoNode_Context_Call {
	_c.Call.Return(context)
	return _c
}

func (_c *MockProtoNode_Context_Call) RunAndReturn(run func() core.Context) *MockProtoNode_Context_Call {
	_c.Call.Return(run)
	return _c
}

// DB provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) DB() *gorm.DB {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DB")
	}

	var r0 *gorm.DB
	if returnFunc, ok := ret.Get(0).(func() *gorm.DB); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}
	return r0
}

// MockProtoNode_DB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DB'
type MockProtoNode_DB_Call struct {
	*mock.Call
}

// DB is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) DB() *MockProtoNode_DB_Call {
	return &MockProtoNode_DB_Call{Call: _e.mock.On("DB")}
}

func (_c *MockProtoNode_DB_Call) Run(run func()) *MockProtoNode_DB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_DB_Call) Return(dB *gorm.DB) *MockProtoNode_DB_Call {
	_c.Call.Return(dB)
	return _c
}

func (_c *MockProtoNode_DB_Call) RunAndReturn(run func() *gorm.DB) *MockProtoNode_DB_Call {
	_c.Call.Return(run)
	return _c
}

// DisplayName provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) DisplayName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DisplayName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtoNode_DisplayName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DisplayName'
type MockProtoNode_DisplayName_Call struct {
	*mock.Call
}

// DisplayName is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) DisplayName() *MockProtoNode_DisplayName_Call {
	return &MockProtoNode_DisplayName_Call{Call: _e.mock.On("DisplayName")}
}

func (_c *MockProtoNode_DisplayName_Call) Run(run func()) *MockProtoNode_DisplayName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_DisplayName_Call) Return(s string) *MockProtoNode_DisplayName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtoNode_DisplayName_Call) RunAndReturn(run func() string) *MockProtoNode_DisplayName_Call {
	_c.Call.Return(run)
	return _c
}

// EncodeFileName provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) EncodeFileName(storageHash core.StorageHash) string {
	ret := _mock.Called(storageHash)

	if len(ret) == 0 {
		panic("no return value specified for EncodeFileName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(core.StorageHash) string); ok {
		r0 = returnFunc(storageHash)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtoNode_EncodeFileName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EncodeFileName'
type MockProtoNode_EncodeFileName_Call struct {
	*mock.Call
}

// EncodeFileName is a helper method to define mock.On call
//   - storageHash core.StorageHash
func (_e *MockProtoNode_Expecter) EncodeFileName(storageHash interface{}) *MockProtoNode_EncodeFileName_Call {
	return &MockProtoNode_EncodeFileName_Call{Call: _e.mock.On("EncodeFileName", storageHash)}
}

func (_c *MockProtoNode_EncodeFileName_Call) Run(run func(storageHash core.StorageHash)) *MockProtoNode_EncodeFileName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.StorageHash
		if args[0] != nil {
			arg0 = args[0].(core.StorageHash)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtoNode_EncodeFileName_Call) Return(s string) *MockProtoNode_EncodeFileName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtoNode_EncodeFileName_Call) RunAndReturn(run func(storageHash core.StorageHash) string) *MockProtoNode_EncodeFileName_Call {
	_c.Call.Return(run)
	return _c
}

// GetConfig provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) GetConfig() config.ProtocolConfig {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetConfig")
	}

	var r0 config.ProtocolConfig
	if returnFunc, ok := ret.Get(0).(func() config.ProtocolConfig); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(config.ProtocolConfig)
		}
	}
	return r0
}

// MockProtoNode_GetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetConfig'
type MockProtoNode_GetConfig_Call struct {
	*mock.Call
}

// GetConfig is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) GetConfig() *MockProtoNode_GetConfig_Call {
	return &MockProtoNode_GetConfig_Call{Call: _e.mock.On("GetConfig")}
}

func (_c *MockProtoNode_GetConfig_Call) Run(run func()) *MockProtoNode_GetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_GetConfig_Call) Return(protocolConfig config.ProtocolConfig) *MockProtoNode_GetConfig_Call {
	_c.Call.Return(protocolConfig)
	return _c
}

func (_c *MockProtoNode_GetConfig_Call) RunAndReturn(run func() config.ProtocolConfig) *MockProtoNode_GetConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetIPNSNode provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) GetIPNSNode() core0.IPNSNodeAccess {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIPNSNode")
	}

	var r0 core0.IPNSNodeAccess
	if returnFunc, ok := ret.Get(0).(func() core0.IPNSNodeAccess); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core0.IPNSNodeAccess)
		}
	}
	return r0
}

// MockProtoNode_GetIPNSNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIPNSNode'
type MockProtoNode_GetIPNSNode_Call struct {
	*mock.Call
}

// GetIPNSNode is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) GetIPNSNode() *MockProtoNode_GetIPNSNode_Call {
	return &MockProtoNode_GetIPNSNode_Call{Call: _e.mock.On("GetIPNSNode")}
}

func (_c *MockProtoNode_GetIPNSNode_Call) Run(run func()) *MockProtoNode_GetIPNSNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_GetIPNSNode_Call) Return(iPNSNodeAccess core0.IPNSNodeAccess) *MockProtoNode_GetIPNSNode_Call {
	_c.Call.Return(iPNSNodeAccess)
	return _c
}

func (_c *MockProtoNode_GetIPNSNode_Call) RunAndReturn(run func() core0.IPNSNodeAccess) *MockProtoNode_GetIPNSNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetMetadataStore provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) GetMetadataStore() core0.MetadataStore {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetMetadataStore")
	}

	var r0 core0.MetadataStore
	if returnFunc, ok := ret.Get(0).(func() core0.MetadataStore); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core0.MetadataStore)
		}
	}
	return r0
}

// MockProtoNode_GetMetadataStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMetadataStore'
type MockProtoNode_GetMetadataStore_Call struct {
	*mock.Call
}

// GetMetadataStore is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) GetMetadataStore() *MockProtoNode_GetMetadataStore_Call {
	return &MockProtoNode_GetMetadataStore_Call{Call: _e.mock.On("GetMetadataStore")}
}

func (_c *MockProtoNode_GetMetadataStore_Call) Run(run func()) *MockProtoNode_GetMetadataStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_GetMetadataStore_Call) Return(metadataStore core0.MetadataStore) *MockProtoNode_GetMetadataStore_Call {
	_c.Call.Return(metadataStore)
	return _c
}

func (_c *MockProtoNode_GetMetadataStore_Call) RunAndReturn(run func() core0.MetadataStore) *MockProtoNode_GetMetadataStore_Call {
	_c.Call.Return(run)
	return _c
}

// GetNode provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) GetNode() ipfs.IPFSNode {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNode")
	}

	var r0 ipfs.IPFSNode
	if returnFunc, ok := ret.Get(0).(func() ipfs.IPFSNode); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ipfs.IPFSNode)
		}
	}
	return r0
}

// MockProtoNode_GetNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNode'
type MockProtoNode_GetNode_Call struct {
	*mock.Call
}

// GetNode is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) GetNode() *MockProtoNode_GetNode_Call {
	return &MockProtoNode_GetNode_Call{Call: _e.mock.On("GetNode")}
}

func (_c *MockProtoNode_GetNode_Call) Run(run func()) *MockProtoNode_GetNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_GetNode_Call) Return(iPFSNode ipfs.IPFSNode) *MockProtoNode_GetNode_Call {
	_c.Call.Return(iPFSNode)
	return _c
}

func (_c *MockProtoNode_GetNode_Call) RunAndReturn(run func() ipfs.IPFSNode) *MockProtoNode_GetNode_Call {
	_c.Call.Return(run)
	return _c
}

// GetNodeFactory provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) GetNodeFactory() *ipfs.NodeFactory {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNodeFactory")
	}

	var r0 *ipfs.NodeFactory
	if returnFunc, ok := ret.Get(0).(func() *ipfs.NodeFactory); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ipfs.NodeFactory)
		}
	}
	return r0
}

// MockProtoNode_GetNodeFactory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNodeFactory'
type MockProtoNode_GetNodeFactory_Call struct {
	*mock.Call
}

// GetNodeFactory is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) GetNodeFactory() *MockProtoNode_GetNodeFactory_Call {
	return &MockProtoNode_GetNodeFactory_Call{Call: _e.mock.On("GetNodeFactory")}
}

func (_c *MockProtoNode_GetNodeFactory_Call) Run(run func()) *MockProtoNode_GetNodeFactory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_GetNodeFactory_Call) Return(nodeFactory *ipfs.NodeFactory) *MockProtoNode_GetNodeFactory_Call {
	_c.Call.Return(nodeFactory)
	return _c
}

func (_c *MockProtoNode_GetNodeFactory_Call) RunAndReturn(run func() *ipfs.NodeFactory) *MockProtoNode_GetNodeFactory_Call {
	_c.Call.Return(run)
	return _c
}

// Hash provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Hash(r io.Reader, size uint64) (core.StorageHash, error) {
	ret := _mock.Called(r, size)

	if len(ret) == 0 {
		panic("no return value specified for Hash")
	}

	var r0 core.StorageHash
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(io.Reader, uint64) (core.StorageHash, error)); ok {
		return returnFunc(r, size)
	}
	if returnFunc, ok := ret.Get(0).(func(io.Reader, uint64) core.StorageHash); ok {
		r0 = returnFunc(r, size)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(core.StorageHash)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(io.Reader, uint64) error); ok {
		r1 = returnFunc(r, size)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProtoNode_Hash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Hash'
type MockProtoNode_Hash_Call struct {
	*mock.Call
}

// Hash is a helper method to define mock.On call
//   - r io.Reader
//   - size uint64
func (_e *MockProtoNode_Expecter) Hash(r interface{}, size interface{}) *MockProtoNode_Hash_Call {
	return &MockProtoNode_Hash_Call{Call: _e.mock.On("Hash", r, size)}
}

func (_c *MockProtoNode_Hash_Call) Run(run func(r io.Reader, size uint64)) *MockProtoNode_Hash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 io.Reader
		if args[0] != nil {
			arg0 = args[0].(io.Reader)
		}
		var arg1 uint64
		if args[1] != nil {
			arg1 = args[1].(uint64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProtoNode_Hash_Call) Return(storageHash core.StorageHash, err error) *MockProtoNode_Hash_Call {
	_c.Call.Return(storageHash, err)
	return _c
}

func (_c *MockProtoNode_Hash_Call) RunAndReturn(run func(r io.Reader, size uint64) (core.StorageHash, error)) *MockProtoNode_Hash_Call {
	_c.Call.Return(run)
	return _c
}

// ID provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) ID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtoNode_ID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ID'
type MockProtoNode_ID_Call struct {
	*mock.Call
}

// ID is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) ID() *MockProtoNode_ID_Call {
	return &MockProtoNode_ID_Call{Call: _e.mock.On("ID")}
}

func (_c *MockProtoNode_ID_Call) Run(run func()) *MockProtoNode_ID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_ID_Call) Return(s string) *MockProtoNode_ID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtoNode_ID_Call) RunAndReturn(run func() string) *MockProtoNode_ID_Call {
	_c.Call.Return(run)
	return _c
}

// Logger provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Logger() *core.Logger {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Logger")
	}

	var r0 *core.Logger
	if returnFunc, ok := ret.Get(0).(func() *core.Logger); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*core.Logger)
		}
	}
	return r0
}

// MockProtoNode_Logger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Logger'
type MockProtoNode_Logger_Call struct {
	*mock.Call
}

// Logger is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) Logger() *MockProtoNode_Logger_Call {
	return &MockProtoNode_Logger_Call{Call: _e.mock.On("Logger")}
}

func (_c *MockProtoNode_Logger_Call) Run(run func()) *MockProtoNode_Logger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_Logger_Call) Return(logger *core.Logger) *MockProtoNode_Logger_Call {
	_c.Call.Return(logger)
	return _c
}

func (_c *MockProtoNode_Logger_Call) RunAndReturn(run func() *core.Logger) *MockProtoNode_Logger_Call {
	_c.Call.Return(run)
	return _c
}

// Name provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockProtoNode_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockProtoNode_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) Name() *MockProtoNode_Name_Call {
	return &MockProtoNode_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockProtoNode_Name_Call) Run(run func()) *MockProtoNode_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_Name_Call) Return(s string) *MockProtoNode_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockProtoNode_Name_Call) RunAndReturn(run func() string) *MockProtoNode_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Operations provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Operations() []core.Operation {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Operations")
	}

	var r0 []core.Operation
	if returnFunc, ok := ret.Get(0).(func() []core.Operation); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.Operation)
		}
	}
	return r0
}

// MockProtoNode_Operations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Operations'
type MockProtoNode_Operations_Call struct {
	*mock.Call
}

// Operations is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) Operations() *MockProtoNode_Operations_Call {
	return &MockProtoNode_Operations_Call{Call: _e.mock.On("Operations")}
}

func (_c *MockProtoNode_Operations_Call) Run(run func()) *MockProtoNode_Operations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_Operations_Call) Return(operations []core.Operation) *MockProtoNode_Operations_Call {
	_c.Call.Return(operations)
	return _c
}

func (_c *MockProtoNode_Operations_Call) RunAndReturn(run func() []core.Operation) *MockProtoNode_Operations_Call {
	_c.Call.Return(run)
	return _c
}

// RestartNode provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) RestartNode() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for RestartNode")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProtoNode_RestartNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestartNode'
type MockProtoNode_RestartNode_Call struct {
	*mock.Call
}

// RestartNode is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) RestartNode() *MockProtoNode_RestartNode_Call {
	return &MockProtoNode_RestartNode_Call{Call: _e.mock.On("RestartNode")}
}

func (_c *MockProtoNode_RestartNode_Call) Run(run func()) *MockProtoNode_RestartNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_RestartNode_Call) Return(err error) *MockProtoNode_RestartNode_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProtoNode_RestartNode_Call) RunAndReturn(run func() error) *MockProtoNode_RestartNode_Call {
	_c.Call.Return(run)
	return _c
}

// SetConfig provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) SetConfig(cfg config.Manager) {
	_mock.Called(cfg)
	return
}

// MockProtoNode_SetConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetConfig'
type MockProtoNode_SetConfig_Call struct {
	*mock.Call
}

// SetConfig is a helper method to define mock.On call
//   - cfg config.Manager
func (_e *MockProtoNode_Expecter) SetConfig(cfg interface{}) *MockProtoNode_SetConfig_Call {
	return &MockProtoNode_SetConfig_Call{Call: _e.mock.On("SetConfig", cfg)}
}

func (_c *MockProtoNode_SetConfig_Call) Run(run func(cfg config.Manager)) *MockProtoNode_SetConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 config.Manager
		if args[0] != nil {
			arg0 = args[0].(config.Manager)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtoNode_SetConfig_Call) Return() *MockProtoNode_SetConfig_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtoNode_SetConfig_Call) RunAndReturn(run func(cfg config.Manager)) *MockProtoNode_SetConfig_Call {
	_c.Run(run)
	return _c
}

// SetContext provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) SetContext(ctx core.Context) {
	_mock.Called(ctx)
	return
}

// MockProtoNode_SetContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetContext'
type MockProtoNode_SetContext_Call struct {
	*mock.Call
}

// SetContext is a helper method to define mock.On call
//   - ctx core.Context
func (_e *MockProtoNode_Expecter) SetContext(ctx interface{}) *MockProtoNode_SetContext_Call {
	return &MockProtoNode_SetContext_Call{Call: _e.mock.On("SetContext", ctx)}
}

func (_c *MockProtoNode_SetContext_Call) Run(run func(ctx core.Context)) *MockProtoNode_SetContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 core.Context
		if args[0] != nil {
			arg0 = args[0].(core.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtoNode_SetContext_Call) Return() *MockProtoNode_SetContext_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtoNode_SetContext_Call) RunAndReturn(run func(ctx core.Context)) *MockProtoNode_SetContext_Call {
	_c.Run(run)
	return _c
}

// SetDB provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) SetDB(db *gorm.DB) {
	_mock.Called(db)
	return
}

// MockProtoNode_SetDB_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetDB'
type MockProtoNode_SetDB_Call struct {
	*mock.Call
}

// SetDB is a helper method to define mock.On call
//   - db *gorm.DB
func (_e *MockProtoNode_Expecter) SetDB(db interface{}) *MockProtoNode_SetDB_Call {
	return &MockProtoNode_SetDB_Call{Call: _e.mock.On("SetDB", db)}
}

func (_c *MockProtoNode_SetDB_Call) Run(run func(db *gorm.DB)) *MockProtoNode_SetDB_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gorm.DB
		if args[0] != nil {
			arg0 = args[0].(*gorm.DB)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtoNode_SetDB_Call) Return() *MockProtoNode_SetDB_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtoNode_SetDB_Call) RunAndReturn(run func(db *gorm.DB)) *MockProtoNode_SetDB_Call {
	_c.Run(run)
	return _c
}

// SetLogger provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) SetLogger(logger *core.Logger) {
	_mock.Called(logger)
	return
}

// MockProtoNode_SetLogger_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetLogger'
type MockProtoNode_SetLogger_Call struct {
	*mock.Call
}

// SetLogger is a helper method to define mock.On call
//   - logger *core.Logger
func (_e *MockProtoNode_Expecter) SetLogger(logger interface{}) *MockProtoNode_SetLogger_Call {
	return &MockProtoNode_SetLogger_Call{Call: _e.mock.On("SetLogger", logger)}
}

func (_c *MockProtoNode_SetLogger_Call) Run(run func(logger *core.Logger)) *MockProtoNode_SetLogger_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *core.Logger
		if args[0] != nil {
			arg0 = args[0].(*core.Logger)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockProtoNode_SetLogger_Call) Return() *MockProtoNode_SetLogger_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockProtoNode_SetLogger_Call) RunAndReturn(run func(logger *core.Logger)) *MockProtoNode_SetLogger_Call {
	_c.Run(run)
	return _c
}

// Workflows provides a mock function for the type MockProtoNode
func (_mock *MockProtoNode) Workflows() []core.WorkflowDefinition {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Workflows")
	}

	var r0 []core.WorkflowDefinition
	if returnFunc, ok := ret.Get(0).(func() []core.WorkflowDefinition); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]core.WorkflowDefinition)
		}
	}
	return r0
}

// MockProtoNode_Workflows_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Workflows'
type MockProtoNode_Workflows_Call struct {
	*mock.Call
}

// Workflows is a helper method to define mock.On call
func (_e *MockProtoNode_Expecter) Workflows() *MockProtoNode_Workflows_Call {
	return &MockProtoNode_Workflows_Call{Call: _e.mock.On("Workflows")}
}

func (_c *MockProtoNode_Workflows_Call) Run(run func()) *MockProtoNode_Workflows_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProtoNode_Workflows_Call) Return(workflowDefinitions []core.WorkflowDefinition) *MockProtoNode_Workflows_Call {
	_c.Call.Return(workflowDefinitions)
	return _c
}

func (_c *MockProtoNode_Workflows_Call) RunAndReturn(run func() []core.WorkflowDefinition) *MockProtoNode_Workflows_Call {
	_c.Call.Return(run)
	return _c
}
