// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package upload

import (
	"context"

	"github.com/ipfs/go-ipld-format"
	mock "github.com/stretchr/testify/mock"
	"go.lumeweb.com/ipfs-content/archive"
)

// NewMockStreamingArchiveProcessor creates a new instance of MockStreamingArchiveProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStreamingArchiveProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStreamingArchiveProcessor {
	mock := &MockStreamingArchiveProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStreamingArchiveProcessor is an autogenerated mock type for the StreamingArchiveProcessor type
type MockStreamingArchiveProcessor struct {
	mock.Mock
}

type MockStreamingArchiveProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStreamingArchiveProcessor) EXPECT() *MockStreamingArchiveProcessor_Expecter {
	return &MockStreamingArchiveProcessor_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type MockStreamingArchiveProcessor
func (_mock *MockStreamingArchiveProcessor) Close() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingArchiveProcessor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockStreamingArchiveProcessor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockStreamingArchiveProcessor_Expecter) Close() *MockStreamingArchiveProcessor_Close_Call {
	return &MockStreamingArchiveProcessor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockStreamingArchiveProcessor_Close_Call) Run(run func()) *MockStreamingArchiveProcessor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingArchiveProcessor_Close_Call) Return(err error) *MockStreamingArchiveProcessor_Close_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingArchiveProcessor_Close_Call) RunAndReturn(run func() error) *MockStreamingArchiveProcessor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// GetProcessedFiles provides a mock function for the type MockStreamingArchiveProcessor
func (_mock *MockStreamingArchiveProcessor) GetProcessedFiles() []FileInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetProcessedFiles")
	}

	var r0 []FileInfo
	if returnFunc, ok := ret.Get(0).(func() []FileInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]FileInfo)
		}
	}
	return r0
}

// MockStreamingArchiveProcessor_GetProcessedFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProcessedFiles'
type MockStreamingArchiveProcessor_GetProcessedFiles_Call struct {
	*mock.Call
}

// GetProcessedFiles is a helper method to define mock.On call
func (_e *MockStreamingArchiveProcessor_Expecter) GetProcessedFiles() *MockStreamingArchiveProcessor_GetProcessedFiles_Call {
	return &MockStreamingArchiveProcessor_GetProcessedFiles_Call{Call: _e.mock.On("GetProcessedFiles")}
}

func (_c *MockStreamingArchiveProcessor_GetProcessedFiles_Call) Run(run func()) *MockStreamingArchiveProcessor_GetProcessedFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStreamingArchiveProcessor_GetProcessedFiles_Call) Return(fileInfos []FileInfo) *MockStreamingArchiveProcessor_GetProcessedFiles_Call {
	_c.Call.Return(fileInfos)
	return _c
}

func (_c *MockStreamingArchiveProcessor_GetProcessedFiles_Call) RunAndReturn(run func() []FileInfo) *MockStreamingArchiveProcessor_GetProcessedFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetRootNode provides a mock function for the type MockStreamingArchiveProcessor
func (_mock *MockStreamingArchiveProcessor) GetRootNode(ctx context.Context) (format.Node, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetRootNode")
	}

	var r0 format.Node
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (format.Node, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) format.Node); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(format.Node)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStreamingArchiveProcessor_GetRootNode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRootNode'
type MockStreamingArchiveProcessor_GetRootNode_Call struct {
	*mock.Call
}

// GetRootNode is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStreamingArchiveProcessor_Expecter) GetRootNode(ctx any) *MockStreamingArchiveProcessor_GetRootNode_Call {
	return &MockStreamingArchiveProcessor_GetRootNode_Call{Call: _e.mock.On("GetRootNode", ctx)}
}

func (_c *MockStreamingArchiveProcessor_GetRootNode_Call) Run(run func(ctx context.Context)) *MockStreamingArchiveProcessor_GetRootNode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStreamingArchiveProcessor_GetRootNode_Call) Return(node format.Node, err error) *MockStreamingArchiveProcessor_GetRootNode_Call {
	_c.Call.Return(node, err)
	return _c
}

func (_c *MockStreamingArchiveProcessor_GetRootNode_Call) RunAndReturn(run func(ctx context.Context) (format.Node, error)) *MockStreamingArchiveProcessor_GetRootNode_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessArchive provides a mock function for the type MockStreamingArchiveProcessor
func (_mock *MockStreamingArchiveProcessor) ProcessArchive(ctx context.Context, extractor archive.ArchiveExtractor) error {
	ret := _mock.Called(ctx, extractor)

	if len(ret) == 0 {
		panic("no return value specified for ProcessArchive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, archive.ArchiveExtractor) error); ok {
		r0 = returnFunc(ctx, extractor)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStreamingArchiveProcessor_ProcessArchive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessArchive'
type MockStreamingArchiveProcessor_ProcessArchive_Call struct {
	*mock.Call
}

// ProcessArchive is a helper method to define mock.On call
//   - ctx context.Context
//   - extractor archive.ArchiveExtractor
func (_e *MockStreamingArchiveProcessor_Expecter) ProcessArchive(ctx any, extractor any) *MockStreamingArchiveProcessor_ProcessArchive_Call {
	return &MockStreamingArchiveProcessor_ProcessArchive_Call{Call: _e.mock.On("ProcessArchive", ctx, extractor)}
}

func (_c *MockStreamingArchiveProcessor_ProcessArchive_Call) Run(run func(ctx context.Context, extractor archive.ArchiveExtractor)) *MockStreamingArchiveProcessor_ProcessArchive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 archive.ArchiveExtractor
		if args[1] != nil {
			arg1 = args[1].(archive.ArchiveExtractor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStreamingArchiveProcessor_ProcessArchive_Call) Return(err error) *MockStreamingArchiveProcessor_ProcessArchive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStreamingArchiveProcessor_ProcessArchive_Call) RunAndReturn(run func(ctx context.Context, extractor archive.ArchiveExtractor) error) *MockStreamingArchiveProcessor_ProcessArchive_Call {
	_c.Call.Return(run)
	return _c
}
