// This file implements application provisioning for Workspace reconciliation:
// application creation/adoption, storage and environment injection, and
// deployment/status polling. It builds on the database phase (ReconcileDatabase)
// and API-key issuance (ReconcileAPIKey), and on the provider-neutral
// coolify.WorkspaceProvider.
//
// Readiness is determined ONLY from the Coolify deployment/application status
// reported by the Coolify API (including health-aware states such as
// "unhealthy"/"degraded"). The portal never performs its own HTTP probe of the
// public workspace URL, and there is no internal health endpoint or token.
// The configured health path is injected into the Coolify/Docker health-check
// settings and is exercised by the container itself (localhost/container
// access), not as a Caddy route.
//
// The service logic here is runtime-generic: the image/tag/port, storage
// mounts, health path, portal API URL, and database environment key names all
// come from WorkspaceConfig, never from hard-coded runtime assumptions.
//
// Secret safety principles (extended from provision.go):
//   - the proxy Basic Auth credentials and the portal API key JWT are never
//     logged; the API key JWT is held only long enough to write it into the
//     application environment and then discarded;
//   - the dedicated database password is never logged or persisted;
//   - the bulk environment payload and its generated response are never
//     logged (SetApplicationEnvironment logs nothing);
//   - proxy Basic Auth credentials ARE persisted on the workspace row because
//     the portal must re-authenticate to the workspace across restarts, but
//     they are generated by the portal and kept separate from the portal API
//     key and the database password.
//
// Provisioning is retryable like the database phase: the application resource
// UUID is persisted immediately after creation, and the deterministic
// application name (scoped to the placement and install namespace) plus the
// installation-scoped Coolify tag let a retry adopt an existing application
// instead of duplicating. Coolify v4.3.19 persists application tags
// (HandlesTagsApi) and supports a server-side tag filter, so tags are a
// supported correctness/recovery mechanism: adoption queries
// GET /applications?tag=<installation-tag> and matches the exact deterministic
// name.
package workspace

import (
	"context"
	"crypto/rand"
	"errors"
	"fmt"
	"strconv"
	"strings"
	"time"

	dashboardCore "go.lumeweb.com/portal-plugin-dashboard/core"
	"go.lumeweb.com/portal-plugin-ipfs/internal/coolify"
	pluginDb "go.lumeweb.com/portal-plugin-ipfs/internal/db"
	"go.lumeweb.com/portal/db"
	"gorm.io/gorm"
)

// Sentinel errors for the application provisioning phase.
var (
	// ErrApplicationAdoptionAmbiguous is returned when more than one existing
	// application matches the workspace's deterministic name. Fail closed
	// rather than guessing which resource to adopt, so an ambiguous create
	// timeout can never silently attach the wrong application.
	ErrApplicationAdoptionAmbiguous = errors.New("workspace: multiple application candidates match the workspace name; refusing to adopt")
	// ErrApplicationCreateNoID is returned when Coolify accepts an application
	// create but returns no resource UUID.
	ErrApplicationCreateNoID = errors.New("workspace: application create returned no resource id")
	// ErrApplicationDomainConflict is returned when Coolify rejects the domain
	// with a 409 conflict. A domain conflict is permanent: we never set
	// force_domain_override=true automatically.
	ErrApplicationDomainConflict = errors.New("workspace: application domain conflict is permanent")
	// ErrDeploymentFailed is returned when the application deployment reaches
	// a terminal failure status.
	ErrDeploymentFailed = errors.New("workspace: application deployment failed")
	// ErrApplicationNotHealthy is returned when the application does not
	// report a running/ready status within the provisioning timeout.
	ErrApplicationNotHealthy = errors.New("workspace: application did not become healthy")
	// ErrApplicationProvisionTimeout is returned when a deployment or
	// application-status poll exceeds the provisioning timeout.
	ErrApplicationProvisionTimeout = errors.New("workspace: application provisioning timed out")
	// ErrProxyCredentialsUnavailable is returned when proxy Basic Auth
	// credentials cannot be generated or persisted.
	ErrProxyCredentialsUnavailable = errors.New("workspace: proxy credentials unavailable")
)

// ReconcileApplication advances the application provisioning phase for ws to a
// created state. It is retryable and idempotent:
//
//   - when ApplicationResourceID is nil it provisions (create or adopt),
//     persists the returned UUID immediately, and generates/uses the proxy
//     Basic Auth credentials; a retry after a partial failure never creates a
//     second application because the ID is already persisted;
//   - when ApplicationResourceID is set it simply returns the application
//     resource for the already-adopted ID.
//
// A Coolify 409 domain conflict is permanent (ErrApplicationDomainConflict)
// and is never auto-resolved with force_domain_override.
func (s *WorkspaceService) ReconcileApplication(ctx context.Context, ws *pluginDb.Workspace) (*coolify.ApplicationResource, error) {
	if s.provider == nil {
		return nil, fmt.Errorf("workspace: provider not available")
	}
	if ws.ApplicationResourceID == nil {
		if err := s.provisionApplication(ctx, ws); err != nil {
			return nil, err
		}
	}
	appID := *ws.ApplicationResourceID
	res, err := s.provider.GetApplication(ctx, appID)
	if err != nil {
		return nil, err
	}
	return &res, nil
}

// provisionApplication creates (or safely adopts) the workspace application,
// persists its resource UUID immediately, and generates/uses the proxy Basic
// Auth credentials. It never creates a second application once an ID is
// persisted.
func (s *WorkspaceService) provisionApplication(ctx context.Context, ws *pluginDb.Workspace) error {
	// The hostname is derived from the workspace label and its PlatformDomain,
	// so ensure the relationship is loaded before building the create request.
	if err := s.ensurePlatformDomain(ctx, ws); err != nil {
		return err
	}

	// 1. Search for an existing exact resource name/tag before creation, so a
	// retry after an ambiguous create can adopt instead of duplicating.
	candidate, err := s.findCandidateApplication(ctx, ws)
	if err != nil {
		return err
	}
	if candidate != nil && candidate.ID != "" {
		return s.setApplicationResourceID(ctx, ws, candidate.ID)
	}

	// 2. Generate (or reuse) the proxy Basic Auth credentials, separate from
	// the portal API key.
	username, password, err := s.proxyCredentials(ctx, ws)
	if err != nil {
		return fmt.Errorf("%w: %v", ErrProxyCredentialsUnavailable, err)
	}

	// 3. Create with instant_deploy=false and deterministic name/tag.
	created, err := s.provider.CreateApplication(ctx, s.buildCreateApplicationRequest(ws, username, password))
	if err != nil {
		// A 409 domain conflict is permanent; do not auto-resolve it.
		if coolify.IsConflict(err) {
			var conflictErr error = fmt.Errorf("%w: %v", ErrApplicationDomainConflict, err)
			_ = s.recordLastError(ctx, ws, conflictErr)
			return conflictErr
		}
		// An indeterminate failure (e.g. transport timeout) may have created
		// the resource before the response was lost. Recover by searching the
		// deterministic name/tag once more before surfacing the error.
		if recovered, rerr := s.findCandidateApplication(ctx, ws); rerr == nil && recovered != nil && recovered.ID != "" {
			return s.setApplicationResourceID(ctx, ws, recovered.ID)
		}
		return err
	}
	if created.UUID == "" {
		return ErrApplicationCreateNoID
	}

	// 4. Persist the UUID immediately so a retry never re-creates the resource.
	return s.setApplicationResourceID(ctx, ws, created.UUID)
}

// findCandidateApplication returns the single existing application matching the
// workspace's deterministic name scoped to this installation's tag, or nil when
// there is none. When no installation tag is configured, it falls back to a
// deterministic-name listing. It fails closed (ErrApplicationAdoptionAmbiguous)
// when several match, because an ambiguous create timeout could otherwise be
// followed by an adoption that guesses wrong.
//
// The configured server/project/environment/destination fields are deliberately
// not further filtered here: the GET /applications?tag=... response does not
// expose those placement UUIDs, so the tag (which is installation-scoped and
// combined with the namespace-prefixed deterministic name) is the reliable
// discriminator. The exact-name match within the tag-scoped result set keeps
// adoption unambiguous.
func (s *WorkspaceService) findCandidateApplication(ctx context.Context, ws *pluginDb.Workspace) (*coolify.Resource, error) {
	name := s.applicationName(ws.ID)
	var resources []coolify.Resource
	if tag := s.applicationTag(); tag != "" {
		// Tag-scoped recovery on v4.3.19+: only applications this installation
		// tagged are candidates, so a same-named resource in another
		// installation is never adopted.
		var err error
		resources, err = s.provider.FindApplicationsByTag(ctx, tag)
		if err != nil {
			return nil, err
		}
	} else {
		// No installation tag configured: a tagged lookup is unavailable, so
		// fall back to a full listing filtered by the deterministic name.
		var err error
		resources, err = s.provider.FindApplicationByName(ctx, name)
		if err != nil {
			return nil, err
		}
	}
	var matches []coolify.Resource
	for _, r := range resources {
		if r.Name == name {
			matches = append(matches, r)
		}
	}
	switch len(matches) {
	case 0:
		return nil, nil
	case 1:
		return &matches[0], nil
	default:
		return nil, ErrApplicationAdoptionAmbiguous
	}
}

// buildCreateApplicationRequest maps the workspace/runtime config and the
// proxy credentials into a provider-neutral create request. The domain is the
// workspace hostname over HTTPS with HTTPS forced, no generated domain, no
// forced domain override, HTTP Basic Auth enabled, Docker/Coolify health-check
// settings, app resource limits, and noindex for the hostname. The
// deterministic name (with any install-namespace prefix) plus the
// installation-scoped tag is the adoption/recovery key; Coolify v4.3.19
// persists application tags, so they are sent to enable tag-scoped recovery.
//
// The health-check settings are the Docker/Coolify container health check:
// the path comes from config, and the port/method/return code are wired from
// the runtime port and fixed GitOps defaults. These are exercised by the
// container against itself (localhost/container access) and are NOT exposed as
// a public Caddy route; Coolify Basic Auth is deliberately not applied to this
// path. The workspace service never HTTP-probes this path itself.
func (s *WorkspaceService) buildCreateApplicationRequest(ws *pluginDb.Workspace, username, password string) coolify.CreateApplicationRequest {
	prov := s.config.Provider
	rt := s.config.Runtime
	hostname := ws.Hostname()
	return coolify.CreateApplicationRequest{
		ServerUUID:            prov.ServerUUID,
		ProjectUUID:           prov.ProjectUUID,
		EnvironmentUUID:       prov.EnvironmentUUID,
		DestinationUUID:       prov.DestinationUUID,
		Name:                  s.applicationName(ws.ID),
		Image:                 rt.Image,
		Tag:                   rt.Tag,
		Port:                  strconv.Itoa(int(rt.Port)),
		Domain:                "https://" + hostname,
		BasicAuthUsername:     username,
		BasicAuthPassword:     password,
		HealthCheckEnabled:    rt.HealthPath != "",
		HealthCheckPath:       rt.HealthPath,
		HealthCheckPort:       strconv.Itoa(int(rt.Port)),
		HealthCheckMethod:     "GET",
		HealthCheckReturnCode: 200,
		MemoryLimit:           rt.MemoryLimit,
		MemoryReservation:     rt.MemoryReservation,
		CPULimit:              rt.CPULimit,
		NoindexDomains:        []string{hostname},
		Tags:                  s.applicationTags(),
	}
}

// setApplicationResourceID persists the provider application resource ID on the
// workspace and updates the in-memory pointer so the caller observes it.
func (s *WorkspaceService) setApplicationResourceID(ctx context.Context, ws *pluginDb.Workspace, resourceID string) error {
	err := db.RetryableComponentTransaction(s, ctx, func(tx *gorm.DB) *gorm.DB {
		update := tx.Model(&pluginDb.Workspace{}).
			Where("id = ? AND application_resource_id IS NULL", ws.ID).
			Update("application_resource_id", resourceID)
		if update.RowsAffected == 0 {
			// Already claimed (e.g. by a concurrent reconciler) — reload.
			_ = tx.Preload("PlatformDomain").First(ws, ws.ID)
		}
		return tx
	})
	if err != nil {
		return fmt.Errorf("workspace: failed to persist application resource id: %w", err)
	}
	ws.ApplicationResourceID = &resourceID
	return nil
}

// ensurePlatformDomain loads the workspace's PlatformDomain relationship when
// it has not been loaded yet, so the hostname can be derived from it.
func (s *WorkspaceService) ensurePlatformDomain(ctx context.Context, ws *pluginDb.Workspace) error {
	if ws.PlatformDomain.Domain != "" {
		return nil
	}
	return db.RetryableComponentTransaction(s, ctx, func(tx *gorm.DB) *gorm.DB {
		if err := tx.Preload("PlatformDomain").First(ws, ws.ID).Error; err != nil {
			_ = tx.AddError(err)
		}
		return tx
	})
}

// proxyCredentials returns the persisted proxy Basic Auth credentials,
// generating and persisting them on first use. They are created once at
// application creation and reused thereafter so the /access endpoint can
// authenticate across reconcile passes and processes.
func (s *WorkspaceService) proxyCredentials(ctx context.Context, ws *pluginDb.Workspace) (string, string, error) {
	if ws.ProxyUsername != nil && ws.ProxyPassword != nil {
		return *ws.ProxyUsername, *ws.ProxyPassword, nil
	}
	username, password, err := generateProxyCredentials()
	if err != nil {
		return "", "", err
	}
	if err := s.setProxyCredentials(ctx, ws, username, password); err != nil {
		return "", "", err
	}
	return username, password, nil
}

// setProxyCredentials persists the proxy Basic Auth credentials on the
// workspace (only when not already set, so a concurrent reconciler cannot
// overwrite them) and updates the in-memory pointers.
func (s *WorkspaceService) setProxyCredentials(ctx context.Context, ws *pluginDb.Workspace, username, password string) error {
	err := db.RetryableComponentTransaction(s, ctx, func(tx *gorm.DB) *gorm.DB {
		update := tx.Model(&pluginDb.Workspace{}).
			Where("id = ? AND proxy_username IS NULL", ws.ID).
			Updates(map[string]any{
				"proxy_username": username,
				"proxy_password": password,
			})
		if update.RowsAffected == 0 {
			return tx.Preload("PlatformDomain").First(ws, ws.ID)
		}
		return tx
	})
	if err != nil {
		return fmt.Errorf("workspace: failed to persist proxy credentials: %w", err)
	}
	ws.ProxyUsername = &username
	ws.ProxyPassword = &password
	return nil
}

// generateProxyCredentials returns a random proxy Basic Auth username and a
// strong random password, both DNS/http-safe.
func generateProxyCredentials() (string, string, error) {
	username, err := randomToken("ws", 12)
	if err != nil {
		return "", "", err
	}
	password, err := randomToken("", 32)
	if err != nil {
		return "", "", err
	}
	return username, password, nil
}

// randomToken returns a URL-safe random token with an optional lowercase
// prefix (used for a human-recognizable username).
func randomToken(prefix string, n int) (string, error) {
	if n <= 0 {
		return "", errors.New("random token length must be positive")
	}
	const alphabet = "abcdefghijklmnopqrstuvwxyz0123456789"
	buf := make([]byte, n)
	if _, err := rand.Read(buf); err != nil {
		return "", fmt.Errorf("failed to generate random token: %w", err)
	}
	var sb strings.Builder
	sb.Grow(len(prefix) + n)
	sb.WriteString(prefix)
	if prefix != "" {
		sb.WriteString("-")
	}
	for _, v := range buf {
		sb.WriteByte(alphabet[int(v)%len(alphabet)])
	}
	return sb.String(), nil
}

// ReconcileApplicationStorage ensures every configured storage mount exists on
// the application's storage. It is idempotent: the provider
// lists existing storage and creates only missing mounts keyed by mount path,
// so repeated calls never create duplicate volumes.
func (s *WorkspaceService) ReconcileApplicationStorage(ctx context.Context, ws *pluginDb.Workspace, appID string) error {
	if s.provider == nil {
		return fmt.Errorf("workspace: provider not available")
	}
	return s.provider.EnsureApplicationStorage(ctx, appID, s.desiredStorageMounts(ws))
}

// desiredStorageMounts maps the configured runtime storage into deterministic,
// provider-neutral mount requests. The volume name is derived from the
// workspace ID plus the configured suffix so it is stable across retries.
func (s *WorkspaceService) desiredStorageMounts(ws *pluginDb.Workspace) []coolify.StorageMount {
	cfg := s.config.Runtime.Storage
	mounts := make([]coolify.StorageMount, 0, len(cfg))
	ns := ""
	if s.config != nil {
		ns = s.config.Provider.InstallNamespace
	}
	for _, sc := range cfg {
		mounts = append(mounts, coolify.StorageMount{
			Name:      deterministicVolumeName(ns, ws.ID, sc.NameSuffix),
			MountPath: sc.MountPath,
		})
	}
	return mounts
}

// SetApplicationEnvironment upserts the workspace runtime environment from the
// configuration, the reconciled database credentials, and the issued portal
// API key. It marks secrets (the portal API key and the database password) as
// shown-once when supported and never logs the payload or its response.
func (s *WorkspaceService) SetApplicationEnvironment(ctx context.Context, ws *pluginDb.Workspace, appID string, dbCreds *DatabaseCredentials, apiKey *dashboardCore.IssuedAPIKey) error {
	if s.provider == nil {
		return fmt.Errorf("workspace: provider not available")
	}
	if dbCreds == nil {
		return errors.New("workspace: database credentials are required to build the environment")
	}
	if apiKey == nil {
		return errors.New("workspace: portal api key is required to build the environment")
	}
	if err := s.ensurePlatformDomain(ctx, ws); err != nil {
		return err
	}
	return s.provider.SetApplicationEnvironment(ctx, appID, s.buildEnvironment(ws, dbCreds, apiKey))
}

// buildEnvironment constructs the desired runtime environment. The fixed
// PORTAL_* keys and the configured database environment key names are all
// injected here; the configured database key names come from the runtime
// config so the service remains runtime-generic.
func (s *WorkspaceService) buildEnvironment(ws *pluginDb.Workspace, dbCreds *DatabaseCredentials, apiKey *dashboardCore.IssuedAPIKey) []coolify.EnvironmentVariable {
	dbEnv := s.config.Runtime.DatabaseEnv
	hostname := ws.Hostname()
	// Runtime identity comes from Coolify itself: Coolify automatically injects
	// COOLIFY_RESOURCE_UUID (the application/container resource UUID) into the
	// container, so the portal never injects a duplicate workspace/resource ID
	// variable here. The container identifies itself to the portal with that
	// COOLIFY_RESOURCE_UUID plus its PORTAL_API_KEY, and, when needed, queries
	// the portal API for any current Website relationship. No workspace or
	// Website numeric ID is ever injected as a runtime environment variable.
	// The authoring hostname (PORTAL_WORKSPACE_URL) is always the workspace's
	// own platform hostname, independent of any published website domain.
	env := []coolify.EnvironmentVariable{
		{Key: "PORTAL_API_URL", Value: s.config.PortalAPIURL},
		{Key: "PORTAL_API_KEY", Value: apiKey.Token, Secret: true},
		{Key: "PORTAL_WORKSPACE_URL", Value: "https://" + hostname},

		{Key: dbEnv.Host, Value: dbCreds.Host},
		{Key: dbEnv.Port, Value: strconv.Itoa(int(dbCreds.Port))},
		{Key: dbEnv.Name, Value: dbCreds.Database},
		{Key: dbEnv.User, Value: dbCreds.Username},
		{Key: dbEnv.Password, Value: dbCreds.Password, Secret: true},
	}
	return env
}

// StartAndObserveApplication starts the application, polls the deployment to a
// terminal state, waits for the application to report a ready/healthy status
// via the Coolify API, and only then marks the workspace ready. Readiness is
// decided purely from Coolify's deployment and application status — the portal
// performs no HTTP probe of the public workspace URL. The deployment UUID is
// held in memory only; after a service restart that loses it, reconciliation
// falls back to the application status poll.
func (s *WorkspaceService) StartAndObserveApplication(ctx context.Context, ws *pluginDb.Workspace, appID string) error {
	if s.provider == nil {
		return fmt.Errorf("workspace: provider not available")
	}

	// 1. Start the application and record the deployment UUID in memory.
	dep, err := s.provider.StartApplication(ctx, appID)
	if err != nil {
		return err
	}

	// 2. Poll the deployment to a terminal state when we have its UUID.
	if dep.ID != "" {
		if err := s.waitDeploymentFinished(ctx, dep.ID); err != nil {
			if isApplicationFailure(err) {
				_ = s.recordLastError(ctx, ws, err)
			}
			return err
		}
	}

	// 3. Wait for the application to report running/ready (or a health-aware
	// terminal state) from the Coolify API.
	if err := s.waitApplicationRunning(ctx, appID); err != nil {
		if isApplicationFailure(err) {
			_ = s.recordLastError(ctx, ws, err)
		}
		return err
	}

	// 4. Mark the workspace ready only on success.
	return s.markReady(ctx, ws)
}

// waitDeploymentFinished polls GET /deployments/{uuid} until the deployment is
// terminal: success on `finished`, failure on `failed`/`error`/`cancelled`.
func (s *WorkspaceService) waitDeploymentFinished(ctx context.Context, deploymentID string) error {
	poll := s.config.PollInterval
	if poll <= 0 {
		poll = 5 * time.Second
	}
	deadline := time.Now().Add(s.provisionTimeout())

	for {
		dep, err := s.provider.GetDeployment(ctx, deploymentID)
		if err != nil {
			if ctx.Err() != nil {
				return ctx.Err()
			}
			if time.Now().After(deadline) {
				return ErrApplicationProvisionTimeout
			}
			if !sleepContext(ctx, poll) {
				return ctx.Err()
			}
			continue
		}
		switch dep.Status {
		case coolify.ResourceStatusFinished:
			return nil
		case coolify.ResourceStatusFailed, "error", "cancelled":
			return fmt.Errorf("%w: deployment %s reached %s", ErrDeploymentFailed, deploymentID, dep.Status)
		default:
			// queued / in_progress / unknown: keep waiting.
			if time.Now().After(deadline) {
				return ErrApplicationProvisionTimeout
			}
			if !sleepContext(ctx, poll) {
				return ctx.Err()
			}
		}
	}
}

// waitApplicationRunning polls GET /applications/{uuid} until the application
// reports a ready/running (or healthy) status, a terminal or health failure
// (failed/unhealthy/degraded/exited), or the provisioning timeout elapses. The
// status is Coolify's raw application status string (the generated
// Application.Status is free-form; when a Docker healthcheck is enabled,
// Coolify reports "healthy"/"unhealthy"; otherwise "running"/"exited"/etc.).
//
// Readiness is decided solely from this Coolify status — the portal performs
// no HTTP probe of the public workspace URL.
func (s *WorkspaceService) waitApplicationRunning(ctx context.Context, appID string) error {
	poll := s.config.PollInterval
	if poll <= 0 {
		poll = 5 * time.Second
	}
	deadline := time.Now().Add(s.provisionTimeout())

	for {
		res, err := s.provider.GetApplication(ctx, appID)
		if err != nil {
			if ctx.Err() != nil {
				return ctx.Err()
			}
			if time.Now().After(deadline) {
				return ErrApplicationProvisionTimeout
			}
			if !sleepContext(ctx, poll) {
				return ctx.Err()
			}
			continue
		}
		switch res.Status {
		case coolify.ResourceStatusRunning, coolify.ResourceStatusReady,
			coolify.ResourceStatusHealthy:
			// Ready/running/healthy: the workspace may be marked ready.
			return nil
		case coolify.ResourceStatusFailed, coolify.ResourceStatusUnhealthy,
			coolify.ResourceStatusDegraded, coolify.ResourceStatusExited:
			// Terminal or health failure: the application did not become
			// healthy within the provisioning window.
			return fmt.Errorf("%w: application %s is in %s status", ErrApplicationNotHealthy, appID, res.Status)
		default:
			// starting / queued / restarting / stopping / stopped / unknown:
			// keep waiting.
			if time.Now().After(deadline) {
				return ErrApplicationProvisionTimeout
			}
			if !sleepContext(ctx, poll) {
				return ctx.Err()
			}
		}
	}
}

// markReady transitions the workspace to ready and clears any recorded error.
// It is the only place a workspace becomes ready, and it must be reached only
// after the Coolify deployment/application status reports a ready state.
func (s *WorkspaceService) markReady(ctx context.Context, ws *pluginDb.Workspace) error {
	err := db.RetryableComponentTransaction(s, ctx, func(tx *gorm.DB) *gorm.DB {
		return tx.Model(&pluginDb.Workspace{}).
			Where("id = ?", ws.ID).
			Updates(map[string]any{
				"status":     pluginDb.WorkspaceStatusReady,
				"last_error": "",
			})
	})
	if err != nil {
		return fmt.Errorf("workspace: failed to mark workspace ready: %w", err)
	}
	ws.Status = pluginDb.WorkspaceStatusReady
	ws.LastError = ""
	return nil
}

// isApplicationFailure reports whether err is a terminal application failure
// that should be recorded, as opposed to a transient/retryable condition.
func isApplicationFailure(err error) bool {
	if err == nil {
		return false
	}
	return errors.Is(err, ErrApplicationDomainConflict) ||
		errors.Is(err, ErrDeploymentFailed) ||
		errors.Is(err, ErrApplicationNotHealthy)
}

// applicationName returns the deterministic resource name for a workspace's
// application, optionally prefixed with the install namespace so two portal
// installations sharing the same Coolify placement never collide. It is
// bounded (<= 63 chars) and DNS/Coolify-resource-name safe, and together with
// the installation-scoped tag it is the adoption/recovery key.
func (s *WorkspaceService) applicationName(id uint) string {
	ns := ""
	if s.config != nil {
		ns = s.config.Provider.InstallNamespace
	}
	return deterministicApplicationName(ns, id)
}

// deterministicApplicationName builds the bounded, DNS-safe deterministic
// application name from an optional install-namespace prefix and the workspace
// ID. The full name never exceeds Coolify's 63-char resource-name ceiling.
func deterministicApplicationName(ns string, id uint) string {
	if ns == "" {
		return fmt.Sprintf("workspace-%d-app", id)
	}
	return fmt.Sprintf("%s-workspace-%d-app", ns, id)
}

// applicationTag returns the single installation-scoped Coolify tag applied to
// every application this installation provisions, following the recommended
// format "<install-namespace>-workspaces". It is empty when no install
// namespace is configured, in which case no tag is sent and adoption falls back
// to a deterministic-name listing.
func (s *WorkspaceService) applicationTag() string {
	ns := ""
	if s.config != nil {
		ns = s.config.Provider.InstallNamespace
	}
	return deterministicWorkspaceTag(ns)
}

// applicationTags returns the tag slice for the create request. It is empty
// when no install namespace is configured, so the create payload carries no
// noisy per-workspace tags.
func (s *WorkspaceService) applicationTags() []string {
	if tag := s.applicationTag(); tag != "" {
		return []string{tag}
	}
	return nil
}

// deterministicWorkspaceTag derives the installation-scoped Coolify tag from
// the install namespace. It is a single installation-level tag shared by all
// workspaces ("<ns>-workspaces"); per-workspace tags are deliberately avoided
// to keep the tag space quiet, and the exact deterministic application name
// provides per-workspace identity within the tag.
func deterministicWorkspaceTag(ns string) string {
	if ns == "" {
		return ""
	}
	return ns + "-workspaces"
}

// deterministicVolumeName is the deterministic persistent volume name for one
// of a workspace's storage mounts, optionally prefixed with the install
// namespace to stay unique across installations sharing a placement.
func deterministicVolumeName(ns string, id uint, suffix string) string {
	if ns == "" {
		return fmt.Sprintf("workspace-%d-%s", id, suffix)
	}
	return fmt.Sprintf("%s-workspace-%d-%s", ns, id, suffix)
}
