name: Build

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: LumeWeb/workflows/.github/workflows/build-plugin.yml@develop
    secrets: inherit
    with:
      replacements: 'github.com/libp2p/go-libp2p=github.com/LumeWeb/go-libp2p@v0.0.0-20260902043403-e59b50d42d53'
      setup_script: |
        KUBO_VERSION=$(wget -qO- https://api.github.com/repos/ipfs/kubo/releases/latest | jq -r '.tag_name')
        wget -q https://github.com/ipfs/kubo/releases/download/${KUBO_VERSION}/kubo_${KUBO_VERSION}_linux-amd64.tar.gz
        tar -xzf kubo_${KUBO_VERSION}_linux-amd64.tar.gz
        cp kubo/ipfs /usr/local/bin/
        ipfs init
